'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
let playwright;try{playwright=require('playwright');}catch{playwright=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'', 'playwright'));}
const ROOT=path.join(__dirname,'..'),out=path.join(ROOT,'verification');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(req.url.split('?')[0]),f=path.resolve(ROOT,'.'+(pathname==='/'?'/index.html':pathname));if(!f.startsWith(ROOT+path.sep)){res.statusCode=403;res.end();return;}try{res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html; charset=utf-8');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await playwright.chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(120000);const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.route('https://**/*',r=>r.abort());
 // Controlled animation time: exercise the real update loop without wall-clock or GPU-speed dependence.
 await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;localStorage.setItem('marlon.rebuild.settings',JSON.stringify({quality:'performance',sound:false}));});
 const boot=async()=>{await page.goto('http://127.0.0.1:'+server.address().port+'/?test=1');await page.waitForFunction(()=>!!window.__TEST,null,{polling:100});await page.evaluate(()=>{window.g=__TEST.game;window.advance=seconds=>{const render=g.renderer.render;g.renderer.render=()=>{};try{for(let i=0;i<Math.ceil(seconds*60);i++)g.frame(1/60);}finally{g.renderer.render=render;}g.ui.update();g.renderer.render(g.scene,g.camera);};window.setPad=()=>{window.fakePad={id:'DualSense Wireless Controller',mapping:'standard',index:0,connected:true,axes:[0,0,0,0],buttons:Array.from({length:18},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[window.fakePad]});};});};
 async function test(name,fn){try{await fn();checks.push({name,ok:true});console.log('PASS '+name);}catch(e){checks.push({name,ok:false,error:e.message});console.log('FAIL '+name+' '+e.message);}}
 try{await boot();
 await test('Démarrage hors réseau : ville et ressources locales',async()=>{const s=await page.evaluate(()=>{g.frame(.1);return __TEST.snapshot();});assert.equal(s.mode,'front');assert.equal(s.buildings,253);assert.equal(s.cars,34);assert(s.triangles>100000);assert(await page.locator('#play').isVisible());});
 await test('Entrée depuis le bouton et HUD actif',async()=>{await page.evaluate(()=>{document.getElementById('play').click();advance(.2)});assert.equal(await page.evaluate(()=>g.mode),'play');assert(await page.locator('#hud').isVisible());});
 await test('DualSense simulée : quatre orientations sans inversion ni rotation parasite',async()=>{const r=await page.evaluate(()=>{setPad();return [0,Math.PI/2,Math.PI,Math.PI*1.5].map(yaw=>{__TEST.teleport(-150,250,yaw);fakePad.axes=[0,-1,0,0];advance(1.2);return{x:g.player.x+150,z:g.player.z-250,yaw:g.cam.yaw,expected:yaw};});});for(const a of r){assert(a.x*Math.sin(a.expected)-a.z*Math.cos(a.expected)>3.5);assert(Math.abs(a.x*Math.cos(a.expected)+a.z*Math.sin(a.expected))<.03);assert(Math.abs(a.yaw-a.expected)<1e-6);}});
 await test('DualSense simulée : stick droit ne déplace pas le personnage',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-150,250,0);fakePad.axes=[0,0,1,0];advance(1);return{x:g.player.x,z:g.player.z,yaw:g.cam.yaw};});assert.equal(r.x,-150);assert.equal(r.z,250);assert(r.yaw>2);});
 await test('DualSense simulée : bruit au repos et gâchette ne font pas marcher',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-150,250,0);fakePad.axes=[.03,-.04,.06,-.03];fakePad.buttons[7]={pressed:true,value:1};advance(.5);fakePad.buttons[7]={pressed:false,value:0};return{x:g.player.x,z:g.player.z};});assert.equal(r.x,-150);assert.equal(r.z,250);});
 await test('Entrer, accélérer, tourner et sortir du véhicule',async()=>{const r=await page.evaluate(()=>{fakePad.axes=[0,0,0,0];__TEST.teleport(-219,253,Math.PI/2);g.interact();advance(1.6);const entered=!!g.vehicle;if(!entered)return{entered};const c=g.vehicle,start=c.x,yaw=c.yaw;fakePad.buttons[7]={pressed:true,value:.8};advance(2);const moved=c.x-start;fakePad.axes[0]=.5;advance(.5);const turned=c.yaw-yaw;fakePad.axes[0]=0;fakePad.buttons[7]={pressed:false,value:0};c.speed=0;g.interact();advance(1.6);return{entered,moved,turned,exited:!g.vehicle,free:g.world.grid.free(g.player.x,g.player.z,.34)};});assert(r.entered);assert(r.moved>5);assert(r.turned>.02);assert(r.exited);assert(r.free);});
 await test('Déconnexion : pause, aucune commande résiduelle',async()=>{const r=await page.evaluate(()=>{fakePad.axes[1]=-1;advance(.1);fakePad=null;advance(.2);return{mode:g.mode,u:g.lastInput};});assert.equal(r.mode,'pause');assert.equal(r.u.forward,0);assert.equal(r.u.gas,0);await page.evaluate(()=>g.setMode('play'));});
 await test('Caméra : rétraction devant la façade du garage',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-225,271,0);advance(.2);return{z:g.camera.position.z,d:g.cam.actual};});assert(r.z<272.25,JSON.stringify(r));assert(r.d<1.4);});
 await test('Collision personnage : mur infranchissable et déplacement latéral libre',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-225,270,0);g.input.keys.add('KeyS');advance(3);g.input.keys.clear();return{z:g.player.z};});assert(r.z<272.2);});
 await test('Recrutement réellement facturé et plafonné à trois',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-225,250,0);g.cash=900;for(let i=0;i<4;i++)g.recruit();advance(.1);return{cash:g.cash,n:g.allies.length};});assert.equal(r.n,3);assert.equal(r.cash,300);});
 await test('Véhicules : couverture balistique et moteur détruit immobilisé',async()=>{const r=await page.evaluate(()=>{const c=g.cars[0];__TEST.teleport(c.x,c.z+3.2,0);g.interact();advance(1.6);const entered=g.vehicle===c;if(!entered)return{entered};c.health=0;c.speed=0;setPad();fakePad.buttons[7]={pressed:true,value:1};advance(.4);const speed=c.speed;fakePad.buttons[7]={pressed:false,value:0};g.interact();advance(1.6);c.health=100;__TEST.teleport(c.x,c.z+7,0);g.camera.position.set(c.x,1.2,c.z+6);g.camera.lookAt(c.x,1.2,c.z);g.camera.updateMatrixWorld();g.player.fireCd=0;g.player.reload=0;g.player.mag=24;g.fire();const damage=100-c.health;return{entered,speed,damage};});assert(r.entered);assert.equal(r.speed,0);assert(r.damage>0);});
 await test('Tir : dégâts, munitions et obstacle au canon',async()=>{const r=await page.evaluate(()=>{const p=g.player,e=g.enemies.filter(e=>e.home===9)[1];__TEST.teleport(-75,218,0);e.x=-75;e.z=201;e.health=80;g.camera.position.set(-74.42,1.43,220);g.camera.lookAt(-75,1.2,201);g.camera.updateMatrixWorld();p.mag=24;p.reload=0;p.fireCd=0;g.fire();const damage=80-e.health,mag=p.mag;__TEST.teleport(-225,269,Math.PI);e.x=-225;e.z=280;e.health=80;g.camera.position.set(-225,1.4,268);g.camera.lookAt(-225,1.2,280);g.camera.updateMatrixWorld();p.fireCd=0;g.fire();const blocked=e.health===80;e.x=-75;e.z=201;return{damage,mag,blocked};});assert(r.damage>0);assert.equal(r.mag,23);assert(r.blocked);});
 await test('Rechargement transfère uniquement les munitions disponibles',async()=>{const r=await page.evaluate(()=>{g.player.mag=2;g.player.ammo=10;g.reload();advance(1.6);return{mag:g.player.mag,ammo:g.player.ammo};});assert.deepEqual(r,{mag:12,ammo:0});});
 await test('Capture contestée puis conquête physique avec équipe',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-75,200,0);for(const a of g.allies){a.x=-73;a.z=202;}g.player.invincible=100;g.sectors[9].capture=0;g.strategy(1);const contested=g.sectors[9].capture===0;for(const e of g.enemies)if(e.home===9){e.health=0;e.dead=0;}const before=g.cash;for(let i=0;i<20*60;i++)g.strategy(1/60);return{contested,owned:g.sectors[9].owner,cash:g.cash-before};});assert(r.contested);assert.equal(r.owned,'player');assert.equal(r.cash,350);});
 await test('Fortification et attaque annoncée absorbée',async()=>{const r=await page.evaluate(()=>{g.selected=9;g.cash=1000;g.fortify(9);const level=g.sectors[9].level;g.raid={id:9,warning:.01,remaining:.02,spawned:false};g.strategy(.02);g.strategy(.1);return{level,after:g.sectors[9].level,owned:g.sectors[9].owner,ended:g.raid===null};});assert.equal(r.level,1);assert.equal(r.after,0);assert.equal(r.owned,'player');assert(r.ended);});
 await test('Opération livraison : véhicule obligatoire, récompense unique',async()=>{const r=await page.evaluate(()=>{g.operation=null;g.startOperation('courier');__TEST.teleport(-225,200,0);g.updateOperation(.1);const indexOnFoot=g.operation.index;g.vehicle=g.cars[0];g.player.x=-225;g.player.z=200;g.updateOperation(.1);g.player.x=225;g.player.z=200;const before=g.cash;g.updateOperation(.1);const reward=g.cash-before;g.updateOperation(.1);const extra=g.cash-before-reward;g.vehicle=null;g.actor.root.visible=true;return{indexOnFoot,reward,extra,done:g.completed.includes('courier')};});assert.equal(r.indexOnFoot,0);assert.equal(r.reward,450);assert.equal(r.extra,0);assert(r.done);});
 await test('Carte : douze secteurs sélectionnables et repère actif',async()=>{await page.evaluate(()=>{g.setMode('map');document.querySelector('[data-sector="6"]').click();document.getElementById('track').click();});assert.equal(await page.evaluate(()=>g.waypoint),6);assert.equal(await page.evaluate(()=>g.mode),'play');});
 await test('Sauvegarde et rechargement de page : portefeuille à zéro et conquête',async()=>{await page.evaluate(()=>{g.cash=0;__TEST.teleport(-225,250,0);g.save();});await boot();const r=await page.evaluate(()=>({cash:g.cash,owner:g.sectors[9].owner,completed:g.completed,squad:g.allies.length}));assert.equal(r.cash,0);assert.equal(r.owner,'player');assert(r.completed.includes('courier'));assert.equal(r.squad,3);});
 await test('Captures de la véritable scène et des véhicules',async()=>{await page.evaluate(()=>{g.setQuality('high');g.frame(.1);g.ui.update();});await page.screenshot({path:path.join(out,'01-accueil.png')});await page.evaluate(()=>{g.start();advance(.3);document.getElementById('toast').classList.remove('show');});await page.screenshot({path:path.join(out,'02-jeu.png')});await page.evaluate(()=>{__TEST.teleport(-222,250,Math.PI*1.27);g.cam.pitch=.12;g.updateCamera(1);g.ui.update();g.renderer.render(g.scene,g.camera);});await page.screenshot({path:path.join(out,'03-vehicule.png')});await page.evaluate(()=>{g.setMode('map');});await page.screenshot({path:path.join(out,'04-carte.png')});});
 await test('Interface mobile : absence de débordement horizontal',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{g.setQuality('performance');g.setMode('settings');g.ui.update();});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.evaluate(()=>g.setMode('map'));const overflow=await page.evaluate(()=>document.querySelector('.panel').scrollWidth-document.querySelector('.panel').clientWidth);assert(overflow<=1);await page.screenshot({path:path.join(out,'05-mobile.png')});});
 await test('Transition véhicule : pause, portière, verrouillage et conducteur assis',async()=>{const r=await page.evaluate(()=>{g.setMode('play');g.operation=null;g.raid=null;fakePad=null;g.input.pad=null;g.input.last='keyboard';g.vehicle=null;const c=g.cars[0];c.x=-219;c.z=250;c.yaw=Math.PI/2;c.health=100;c.speed=0;__TEST.teleport(-219,253,Math.PI/2);g.interact();advance(.5);const opened=c.model.doors.some(d=>Math.abs(d.hinge.rotation.y)>.2),before=g.action.time;g.setMode('pause');advance(1);const paused=g.action.time===before;g.setMode('play');g.input.keys.add('KeyW');advance(1.05);const seated=g.vehicle===c&&g.actor.animator.state==='driving';g.input.keys.clear();c.speed=0;g.interact();advance(1.6);return{opened,paused,seated,exited:g.vehicle===null,doors:c.model.doors.every(d=>Math.abs(d.hinge.rotation.y)<.01)};});assert(r.opened);assert(r.paused);assert(r.seated);assert(r.exited);assert(r.doors);});
 await test('Contact de mêlée différé et dégâts attribués une seule fois',async()=>{const r=await page.evaluate(()=>{g.player.invincible=100;g.input.clear();__TEST.teleport(-75,210,0);const e=g.enemies.find(e=>e.home===9);for(const other of g.enemies)if(other.home===9){other.health=0;other.dead=0;}e.x=-75;e.z=208.6;e.health=80;g.player.reload=0;g.player.melee=0;for(const a of g.allies){a.x=-225;a.z=250;}g.melee();const before=e.health;const u={x:0,forward:0,lookX:0,lookY:0,mouseX:0,mouseY:0,aim:false,fire:false,edges:new Set};for(let i=0;i<10;i++){g.t+=1/60;g.updatePlayer(u,1/60);}const early=e.health;for(let i=0;i<7;i++){g.t+=1/60;g.updatePlayer(u,1/60);}const after=e.health;for(let i=0;i<30;i++){g.t+=1/60;g.updatePlayer(u,1/60);}return{before,early,after,final:e.health};});assert.equal(r.before,r.early);assert(r.after<r.before);assert.equal(r.after,r.final);});
 await test('Équipier à terre, réanimation temporisée et capture conditionnée à un vivant',async()=>{const r=await page.evaluate(()=>{__TEST.teleport(-225,250,0);g.player.invincible=100;const a=g.allies[0];a.x=-224;a.z=250;g.hurtAlly(a,200);const down=a.health===0&&a.downTime===60;g.recruit();const action=g.action?.kind;advance(1);const early=a.health;advance(1.8);return{down,action,early,health:a.health,done:g.action===null};});assert(r.down);assert.equal(r.action,'revive');assert.equal(r.early,0);assert.equal(r.health,45);assert(r.done);});
 await test('Expiration du secours : équipier retiré sans exception',async()=>{const r=await page.evaluate(()=>{const a=g.allies[0],before=g.allies.length;g.hurtAlly(a,200);a.downTime=.01;g.updateAllies(.02);const after=g.allies.length;g.addAlly();return{before,after};});assert.equal(r.after,r.before-1);});
 await test('Campagne complète restaurée : mission, attaque, voiture et ennemis neutralisés',async()=>{await page.evaluate(()=>{g.action=null;g.operation={type:'courier',ids:[8,11],index:1,remaining:93};g.raid={id:9,warning:23,remaining:70,spawned:false};g.cars[0].health=37;g.cars[0].x=-200;g.cars[0].z=250;g.cars[0].speed=0;g.vehicle=g.cars[0];g.player.x=-200;g.player.z=250;g.enemies[0].health=0;g.enemies[0].dead=0;g.save();});await boot();const r=await page.evaluate(()=>({op:g.operation,raid:g.raid,car:g.vehicle?.health,enemy:g.enemies[0].health}));assert.equal(r.op.index,1);assert.equal(r.op.remaining,93);assert.equal(r.raid.warning,23);assert.equal(r.car,37);assert.equal(r.enemy,0);});
 await test('Corruption de sauvegarde : reprise sur la copie précédente',async()=>{await page.evaluate(()=>{g.cash=411;g.save();g.cash=277;g.save();localStorage.setItem('marlon.rebuild.save.v3','corrupted');});await boot();const r=await page.evaluate(()=>({cash:g.cash,source:g.store.source}));assert.equal(r.cash,411);assert.equal(r.source,'backup');});
 await test('Studio : dix cycles accessibles et rechargement animé',async()=>{const studio=await browser.newPage({viewport:{width:1280,height:800}});studio.setDefaultTimeout(60000);studio.on('pageerror',e=>errors.push(e.message));await studio.addInitScript(()=>window.requestAnimationFrame=()=>0);await studio.goto('http://127.0.0.1:'+server.address().port+'/studio.html');await studio.waitForFunction(()=>!!window.__STUDIO,null,{polling:100});assert.equal(await studio.locator('[data-clip]').count(),10);const states=await studio.evaluate(()=>{const s=__STUDIO,out={};for(const id of ['walk','run','aim','reload','jump','revive','death','drive']){s.setClip(id);for(let i=0;i<40;i++)s.tick(1/60,true);out[id]=s.rig.animator.state;}return out;});assert.equal(states.run,'run');assert.equal(states.reload,'reload');assert.equal(states.revive,'revive');assert.equal(states.drive,'driving');await studio.evaluate(()=>{__STUDIO.setClip('aim');for(let i=0;i<60;i++)__STUDIO.tick(1/60,true);});await studio.screenshot({path:path.join(out,'06-studio.png')});await studio.close();});
 await test('Boucle réelle : démarrage et déplacement clavier sans horloge simulée',async()=>{const live=await browser.newPage({viewport:{width:800,height:500}});live.setDefaultTimeout(60000);live.on('pageerror',e=>errors.push(e.message));await live.addInitScript(()=>localStorage.setItem('marlon.rebuild.settings',JSON.stringify({quality:'performance',sound:false})));await live.goto('http://127.0.0.1:'+server.address().port+'/?test=1');await live.waitForFunction(()=>!!window.__TEST,null,{polling:100});await live.click('#play',{force:true,noWaitAfter:true});await live.keyboard.down('KeyW');await live.waitForFunction(()=>__TEST.game.player.z<249.3,null,{polling:100});await live.keyboard.up('KeyW');assert.equal(await live.evaluate(()=>__TEST.game.mode),'play');await live.close();});
 await test('Aucune exception JavaScript ni erreur de compilation des shaders',async()=>assert.deepEqual(errors,[]));
 }finally{fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({environment:'Chromium headless / SwiftShader / WebGL 1, controlled simulation clock; not a hardware FPS benchmark',checks,errors},null,2));await browser.close();server.close();}
 console.log(JSON.stringify({passed:checks.filter(x=>x.ok).length,failed:checks.filter(x=>!x.ok).length}));if(checks.some(x=>!x.ok))process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
