'use strict';const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('node:assert/strict');const root=path.join(__dirname,'..'),context={console,Math,JSON,Set,Number,String};context.Marlon={clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),validateState:a=>a?{...a}:null};vm.createContext(context);for(const name of ['city-data','board-games'])vm.runInContext(fs.readFileSync(path.join(root,'src',name+'.js'),'utf8'),context);const M=context.Marlon;let count=0;function test(n,fn){fn();console.log('PASS '+n);count++;}
test('Catalogues : identifiants uniques, 14 véhicules achetables et puissances distinctes',()=>{assert.equal(M.CARS.filter(c=>c.price>0).length,14);assert.equal(new Set(M.CARS.map(c=>c.id)).size,M.CARS.length);assert(new Set(M.CARS.map(c=>c.maxSpeed)).size>8);});
test('Questions : identifiants uniques, réponses présentes et choix sans doublon',()=>{assert(M.QUESTIONS.length>450);assert.equal(new Set(M.QUESTIONS.map(q=>q.id)).size,M.QUESTIONS.length);for(const q of M.QUESTIONS){assert(q.choices.includes(q.answer));assert.equal(new Set(q.choices).size,q.choices.length);}});
test('Questions : prochaine question exclut les réponses déjà récompensées',()=>{const s=M.newCity(),q=M.nextQuestion(s,'maths');s.answered.push(q.id);for(let i=0;i<300;i++)assert.notEqual(M.nextQuestion(s,'maths').id,q.id);});
test('Sauvegarde urbaine : bornes, catalogue et noms contrôlés',()=>{const s=M.validCity({...M.newCity(),bank:-12,strength:999,wanted:99,pets:[{name:'<x>',kind:'dog'}],cars:[{id:'bad',color:'bad',upgrades:['turbo','bad']}],outfit:{top:'bad'}});assert.equal(s.bank,0);assert.equal(s.strength,100);assert.equal(s.wanted,3);assert.equal(s.pets[0].name,'x');assert.equal(s.cars[0].upgrades.length,1);assert.equal(s.outfit.top,'tank');});
test('Persistance : vêtements achetés, compte et véhicules conservés',()=>{const s=M.newCity();s.bank=765;s.closet.push('shirt');s.outfit.top='shirt';s.cars=[{id:'sport',color:'#ff698d',owned:true,upgrades:['engine','turbo']}];const r=M.validCity(JSON.parse(JSON.stringify(s)));assert.equal(r.bank,765);assert.equal(r.outfit.top,'shirt');assert.equal(r.cars[0].id,'sport');assert(r.cars[0].owned);});
test('Échecs : 20 coups initiaux et déplacement illégal refusé',()=>{const b=new M.Board('chess');assert.equal(b.legal().length,20);assert(!b.play(56,0));assert(b.play(52,36));});
test('Échecs : le roi ne peut rester en échec',()=>{const b=new M.Board('chess');b.board.fill(0);b.board[60]=6;b.board[4]=-4;b.board[0]=-6;b.board[61]=4;assert(b.attacked(60,-1));assert(!b.play(61,53));});
test('Dames : prises obligatoires et capture retirée',()=>{const b=new M.Board('checkers');b.board.fill(0);b.board[42]=1;b.board[35]=-1;b.board[17]=-1;const moves=b.legal();assert.equal(moves.length,1);assert(b.play(42,28));assert.equal(b.board[35],0);});
test('Poker : couleur, paire et quinte flush distinguées',()=>{assert.equal(M.pokerRank([0,1,2,3,4]).mult,50);assert.equal(M.pokerRank([0,13,4,20,36]).mult,1);assert.equal(M.pokerRank([0,2,5,8,11]).mult,6);});
console.log(count+' tests réussis.');
