'use strict';
// Independent browser checks: user actions use actual DOM keyboard events.
// Scenario setup uses the explicit ?test=1 diagnostic surface.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const pw=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'','playwright'));
const root=path.resolve(__dirname,'..'),out=path.join(root,'verification'),checks=[],errors=[],metrics={};
const server=http.createServer((req,res)=>{const u=req.url.split('?')[0],file=path.resolve(root,'.'+(u==='/'?'/index.html':u));if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end();}try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await pw.chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/workspace/scratch/6a513a53bc11/browser-runtime/chromium',args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--disable-dev-shm-usage']});
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.setDefaultTimeout(120000);
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;localStorage.setItem('marlon.rebuild.settings',JSON.stringify({quality:'performance',sound:true}));});
 const step=async seconds=>page.evaluate(seconds=>qa.advance(seconds),seconds);
 const key=async(code,seconds=.025)=>{await page.keyboard.down(code);await step(seconds);await page.keyboard.up(code);await step(1/60);};
 const test=async(name,fn)=>{const t=Date.now();try{const details=await fn();checks.push({name,ok:true,ms:Date.now()-t,...(details?{details}:{})});console.log('PASS '+name);}catch(e){checks.push({name,ok:false,ms:Date.now()-t,error:e.stack});console.log('FAIL '+name+' '+e.message);}};
 const render=async()=>page.evaluate(()=>{g.updateCamera(.4);g.ui.update();g.renderer.render(g.scene,g.camera);});
 const shot=async name=>{await render();await page.screenshot({path:path.join(out,'v5-'+name+'.png')});};
 const boot=async()=>{await page.goto('http://127.0.0.1:'+server.address().port+'/?test=1');await page.waitForFunction(()=>!!window.__TEST,null,{polling:100});await page.evaluate(()=>{window.g=__TEST.game;window.qa={advance(seconds){const render=g.renderer.render;g.renderer.render=()=>{};for(let i=0;i<Math.ceil(seconds*60);i++)g.frame(1/60);g.renderer.render=render;},place(x,z,y=0,yaw=0){g.vehicle=null;g.action=null;g.cityTask=null;g.heliFlying=false;g.input.clear();g.setMode('play');Object.assign(g.player,{x,z,y,yaw,vx:0,vz:0,vy:0,health:100,invincible:0,armed:false,aim:false});g.cam.yaw=yaw;g.cam.pitch=.15;g.cam.target.set(x,y+1.4,z);g.actor.root.visible=true;g.actor.root.position.set(x,y,z);g.actor.root.rotation.y=Math.PI-yaw;Marlon.animateCharacter(g.actor,0,.1,g.t,false,false,0,0,{});},visit(id){const b=g.world.services.find(b=>b.id===id);this.place(b.service.x,b.service.z,.22);return b;}};});};
 try{
  await boot();
  await test('Démarrage par le bouton Jouer et monde initialisé',async()=>{await page.locator('#play').click();await step(.1);const r=await page.evaluate(()=>({mode:g.mode,services:g.world.services.length,cars:g.cars.length,npcs:g.npcs.length,questions:Marlon.QUESTIONS.length}));assert.equal(r.mode,'play');assert.equal(r.services,20);assert.equal(r.cars,34);assert(r.npcs>=92);assert.equal(r.questions,494);return r;});
  await test('Clavier réel : déplacement ZQSD et arrêt sans dérive',async()=>{await page.evaluate(()=>qa.place(-225,250));await key('KeyZ',1);const moving=await page.evaluate(()=>({x:g.player.x,z:g.player.z}));await step(.9);const still=await page.evaluate(()=>({x:g.player.x,z:g.player.z}));assert(Math.hypot(moving.x+225,moving.z-250)>2);assert(Math.hypot(still.x-moving.x,still.z-moving.z)<.55);return{moving,still};});
  await test('Clavier réel : saut au sol, atterrissage et santé conservée',async()=>{await page.evaluate(()=>qa.place(-225,250));await key('Space',.16);const air=await page.evaluate(()=>g.player.y);await step(2);const r=await page.evaluate(()=>({y:g.player.y,health:g.player.health,action:g.action?.kind}));assert(air>.3);assert(r.y<.25);assert.equal(r.health,100);assert(!r.action);return{air,...r};});
  await test('Clavier réel : pause suspend la simulation et Échap reprend',async()=>{await key('Escape');const t=await page.evaluate(()=>g.t);await step(2);assert.equal(await page.evaluate(()=>g.t),t);await key('Escape');assert.equal(await page.evaluate(()=>g.mode),'play');});
  await test('Manette simulée : déplacement dans quatre orientations et caméra indépendante',async()=>{const r=await page.evaluate(()=>{window.qaPad={id:'DualSense Wireless Controller',mapping:'standard',index:0,connected:true,axes:[0,0,0,0],buttons:Array.from({length:18},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[qaPad]});const rows=[];for(const yaw of [0,Math.PI/2,Math.PI,Math.PI*1.5]){qa.place(-150,250,0,yaw);qaPad.axes=[0,-1,0,0];qa.advance(.8);rows.push({dx:g.player.x+150,dz:g.player.z-250,yaw,camera:g.cam.yaw});}qaPad.axes=[0,0,0,0];qa.place(-150,250);qaPad.axes=[0,0,1,0];qa.advance(.5);const isolated=Math.hypot(g.player.x+150,g.player.z-250)<.01;qaPad.axes=[0,0,0,0];Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[]});g.input.last='keyboard';g.input.pad=null;return{rows,isolated};});assert(r.isolated);for(const p of r.rows){assert(p.dx*Math.sin(p.yaw)-p.dz*Math.cos(p.yaw)>1.5);assert(Math.abs(p.camera-p.yaw)<.01);}return r;});
  await test('Chute depuis 14 m : retour au sol sans mort ni téléportation',async()=>{await page.evaluate(()=>qa.place(-225,250,14));await key('KeyD',.3);await step(3);const r=await page.evaluate(()=>({x:g.player.x,z:g.player.z,y:g.player.y,health:g.player.health,action:g.action?.kind,visible:g.actor.root.visible}));assert.equal(r.health,100);assert(r.y>=0&&r.y<.3);assert(!r.action);assert(r.visible);assert(Math.hypot(r.x+225,r.z-250)<8);return r;});
  await test('École : entrée par E et bonne réponse créditée une fois',async()=>{await page.evaluate(()=>{qa.visit('school');g.ui.speak=()=>{};});await key('KeyE');assert.equal(await page.evaluate(()=>g.place),'school');await page.evaluate(()=>g.ui.schoolQuestion('maths'));const answer=await page.evaluate(()=>g.ui.currentQuestion.answer),cash=await page.evaluate(()=>g.cash);await page.locator('#answers button').filter({hasText:new RegExp('^'+answer.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')}).click();assert.equal(await page.evaluate(()=>g.cash)-cash,5);await shot('school');});
  await test('Bouton Son : activation par geste utilisateur et coupure',async()=>{await page.evaluate(()=>qa.place(-225,250));await page.locator('#soundToggle').click();assert.equal(await page.evaluate(()=>g.audio.enabled),false);await page.locator('#soundToggle').click();assert.equal(await page.evaluate(()=>g.audio.enabled),true);await step(.1);await page.waitForFunction(()=>!__TEST.game.audio.ctx||__TEST.game.audio.ctx.state==='running',null,{polling:100,timeout:5000});const r=await page.evaluate(()=>({state:g.audio.ctx?.state||null,enabled:g.audio.enabled}));assert(r.state==='running'||r.state===null);return r;});
  await test('Trafic : conducteur matérialisé et assis dans chaque voiture active',async()=>{const r=await page.evaluate(()=>g.cars.filter(c=>c.traffic).map(c=>({id:g.cars.indexOf(c),kind:c.spec.id,driver:!!c.driver?.actor?.root,parented:c.driver?.actor?.root.parent===c.model.body,visible:c.driver?.actor?.root.visible})));assert(r.length>5);assert(r.every(c=>c.driver&&c.parented&&c.visible));return r;});
  await test('Clavier réel : vol avec extraction du conducteur, portière et une étoile',async()=>{await page.evaluate(()=>{qa.place(-219,253);g.cars[0].x=-260;g.cars[0].z=250;g.animateCar(g.cars[0],0);const c=g.cars[14];c.x=-219;c.z=250;c.yaw=Math.PI/2;c.speed=0;c.health=100;c.traffic=true;c.owned=false;c.driverRemoved=false;g.city.wanted=0;g.city.heat=0;g.policeCooldown=100;g.animateCar(c,0);});await key('KeyE',.1);const started=await page.evaluate(()=>({kind:g.action?.kind,jacking:g.action?.jacking,duration:g.action?.duration}));assert.equal(started.kind,'enter');assert(started.jacking);await step(.7);const mid=await page.evaluate(()=>({door:g.cars[14].model.doors.map(d=>d.hinge.rotation.y),driver:g.cars[14].driver?.actor?.root.position.toArray()}));assert(mid.door.some(v=>Math.abs(v)>.1));await shot('carjack');await step(2.1);const r=await page.evaluate(()=>({entered:g.vehicle===g.cars[14],wanted:g.city.wanted,removed:g.cars[14].driverRemoved,displaced:g.displacedDrivers.length,doors:g.cars[14].model.doors.map(d=>d.hinge.rotation.y),events:g.vehicleEvents.filter(e=>e.kind==='jack').length}));assert(r.entered&&r.removed);assert.equal(r.wanted,1);assert(r.displaced>=1);assert(r.doors.every(v=>Math.abs(v)<.001));assert(r.events>=1);return{started,mid,...r};});
  await test('Clavier réel : freinage provoque tangage et fumée blanche',async()=>{await page.evaluate(()=>{const c=g.vehicle;c.x=-150;c.z=250;c.yaw=Math.PI/2;c.speed=25;c.health=100;g.player.x=c.x;g.player.z=c.z;g.city.wanted=0;g.city.heat=0;});await key('KeyS',.25);const r=await page.evaluate(()=>({speed:g.vehicle.speed,pitch:g.vehicle.suspension.pitch,braking:g.vehicle.braking,events:g.vehicleEvents.filter(e=>e.kind==='brake').length,pool:g.vehicleFX.pool.length}));assert(r.speed<24);assert(Math.abs(r.pitch)>.001);assert(r.events>=1);assert(r.pool<=96);await shot('braking');return r;});
  await test('Clavier réel : sortie sûre et fermeture des deux portières',async()=>{await page.evaluate(()=>g.vehicle.speed=0);await key('KeyE',.05);await step(1.6);const r=await page.evaluate(()=>({exited:!g.vehicle,free:g.world.grid.free(g.player.x,g.player.z,.4),doors:g.cars[14].model.doors.map(d=>d.hinge.rotation.y),visible:g.actor.root.visible}));assert(r.exited&&r.free&&r.visible);assert(r.doors.every(v=>Math.abs(v)<.001));return r;});
  await test('Collision réelle : dégâts, explosion unique et véhicule immobilisé',async()=>{await page.evaluate(()=>{qa.place(-231,299);const c=g.cars[0];c.x=-231;c.z=299;c.yaw=0;c.health=1;c.speed=28;c.owned=true;c.traffic=false;c.wrecked=false;g.vehicle=c;g.player.x=c.x;g.player.z=c.z;g.player.health=100;g.city.wanted=0;g.city.heat=0;g.accident=null;g.policeCooldown=100;g.qaExplosionStart=g.vehicleEvents.filter(e=>e.kind==='explosion').length;});await key('KeyZ',.8);const r=await page.evaluate(()=>{const c=g.cars[0];return{x:c.x,z:c.z,kind:c.spec.id,mode:g.mode,inCar:g.vehicle===c,health:c.health,wrecked:c.wrecked,stage:c.damageStage,speed:c.speed,events:g.vehicleEvents.filter(e=>e.kind==='explosion').length-g.qaExplosionStart,playerHealth:g.player.health,pool:g.vehicleFX.pool.length};});assert.equal(r.health,0,JSON.stringify(r));assert(r.wrecked);assert.equal(r.events,1);assert(Math.abs(r.speed)<.1);assert(r.playerHealth>0);assert(r.pool<=96);await shot('explosion');await step(1);assert.equal(await page.evaluate(()=>g.vehicleEvents.filter(e=>e.kind==='explosion').length-g.qaExplosionStart),1);return r;});
  await test('Vie du quartier : gangs distincts, chiens errants et bots supplémentaires',async()=>{const r=await page.evaluate(()=>({people:g.lifePeople.length,strays:g.strays.length,gangs:g.lifePeople.filter(n=>n.faction).length}));assert(r.people>=42);assert(r.strays>=5);assert(r.gangs>=12);return r;});
  await test('Clavier réel : rencontre avec le chef de bande aux docks',async()=>{await page.evaluate(()=>qa.place(-219,-222));await key('KeyE');const r=await page.evaluate(()=>({mode:g.mode,place:g.place,body:document.getElementById('panelBody').textContent.slice(0,250)}));assert.equal(r.mode,'city');assert.equal(r.place,'life-person');await shot('gang');return r;});
  await test('Clavier réel : rencontre avec un chien errant',async()=>{await page.evaluate(()=>{const d=g.strays[0];qa.place(d.x+.7,d.z);});await key('KeyE');const r=await page.evaluate(()=>({mode:g.mode,place:g.place}));assert.equal(r.mode,'city');assert.equal(r.place,'life-dog');await shot('stray');return r;});
  await test('Chien errant : caresse animée et confiance obtenue',async()=>{await page.getByRole('button',{name:'RASSURER ET CARESSER',exact:true}).click();await step(.6);assert.equal(await page.evaluate(()=>g.lifeAction?.kind),'pet');await step(2.1);assert(await page.evaluate(()=>g.strays[0].fed));assert.equal(await page.evaluate(()=>g.lifeAction),null);});
  await test('Banc : interaction E, position assise et lever avec E',async()=>{const found=await page.evaluate(()=>{for(const b of g.world.props.filter(p=>p.kind==='bench')){qa.place(b.x,b.z+.7);const n=g.lifeNearby();if(n?.kind==='prop'&&n.target===b)return true;}return false;});assert(found);await key('KeyE');assert.equal(await page.evaluate(()=>g.place),'life-prop');await page.getByRole('button',{name:'S’ASSEOIR · E POUR SE LEVER',exact:true}).click();await step(.5);assert.equal(await page.evaluate(()=>g.lifeAction?.kind),'sit');await shot('bench');await key('KeyE');assert.equal(await page.evaluate(()=>g.lifeAction),null);});
  await test('Sauvegarde : état relu après véritable rechargement',async()=>{await page.evaluate(()=>{qa.place(-225,250);g.city.bank=2345;g.city.strength=30;g.cash=876;g.save();g.skipExitSave=true;});await boot();await page.locator('#play').click();const r=await page.evaluate(()=>({bank:g.city.bank,strength:g.city.strength,cash:g.cash}));assert.deepEqual(r,{bank:2345,strength:30,cash:876});return r;});
  await test('Interface mobile : aucun débordement du concessionnaire',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>g.openPlace('dealer'));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'v5-mobile.png')});await page.setViewportSize({width:1280,height:800});});
  await test('Ultra HD : tampon 3840 × 2160 sur un affichage 1280 × 720',async()=>{await page.setViewportSize({width:1280,height:720});const r=await page.evaluate(()=>{g.setQuality('ultra');const v=g.renderer.getDrawingBufferSize(new THREE.Vector2());const result={width:v.x,height:v.y};g.setQuality('performance');return result;});assert.deepEqual(r,{width:3840,height:2160});await page.setViewportSize({width:1280,height:800});return r;});
  await test('Captures du rendu courant et mesures GPU logicielles',async()=>{await page.evaluate(()=>{qa.place(-175,249);g.city.weather='sun';g.city.clock=11;g.updateCity(.1);g.setQuality('high');});await shot('showroom');await page.evaluate(()=>{qa.place(-215,250);g.camera.position.set(-215,1.45,246.4);g.camera.lookAt(-215,.96,250);g.renderer.render(g.scene,g.camera);g.ui.update();});await page.screenshot({path:path.join(out,'v5-character.png')});const r=await page.evaluate(()=>({calls:g.renderer.info.render.calls,triangles:g.renderer.info.render.triangles,geometries:g.renderer.info.memory.geometries,textures:g.renderer.info.memory.textures}));Object.assign(metrics,r);await page.evaluate(()=>{qa.place(-224,-218);qa.advance(.2);g.camera.position.set(-250,18,-194);g.camera.lookAt(-225,2,-229);g.renderer.render(g.scene,g.camera);g.ui.update();});await page.screenshot({path:path.join(out,'v5-docks.png')});await page.evaluate(()=>{qa.place(125,145);qa.advance(.2);g.camera.position.set(150,17,156);g.camera.lookAt(126,2,125);g.renderer.render(g.scene,g.camera);g.ui.update();});await page.screenshot({path:path.join(out,'v5-villa.png')});return r;});
  await test('Boucle temps réel : jeu au clavier avec requestAnimationFrame native',async()=>{const live=await browser.newPage({viewport:{width:960,height:600}});try{live.on('pageerror',e=>errors.push(e.message));await live.addInitScript(()=>localStorage.setItem('marlon.rebuild.settings',JSON.stringify({quality:'performance',sound:false})));await live.goto('http://127.0.0.1:'+server.address().port+'/?test=1');await live.waitForFunction(()=>!!window.__TEST,null,{polling:100,timeout:120000});await live.locator('#play').click({force:true,timeout:120000});await live.evaluate(()=>{const g=__TEST.game;window.liveStart={x:g.player.x,z:g.player.z,t:g.t};});await live.keyboard.down('KeyZ');await live.waitForFunction(()=>{const g=__TEST.game;return Math.hypot(g.player.x-liveStart.x,g.player.z-liveStart.z)>.7;},null,{polling:100,timeout:30000});await live.keyboard.up('KeyZ');const r=await live.evaluate(()=>({distance:Math.hypot(__TEST.game.player.x-liveStart.x,__TEST.game.player.z-liveStart.z),simulationSeconds:__TEST.game.t-liveStart.t,health:__TEST.game.player.health}));assert(r.distance>.7);assert(r.health>0);await live.screenshot({path:path.join(out,'v5-live.png')});return r;}finally{await live.close();}});
  await test('Aucune exception JavaScript pendant les parcours',async()=>assert.deepEqual(errors,[]));
 }finally{
  fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'v5-browser-results.json'),JSON.stringify({date:new Date().toISOString(),checks,errors,metrics,environment:'Chromium headless / SwiftShader. Simulation fixe contrôlée ; vraies touches clavier et boutons DOM ; manette simulée, aucune manette physique. Les placements de scénario utilisent ?test=1.'},null,2));await browser.close();server.close();
 }
 console.log(JSON.stringify({passed:checks.filter(c=>c.ok).length,failed:checks.filter(c=>!c.ok).length}));if(checks.some(c=>!c.ok))process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
