'use strict';
// Ouvre le jeu dans un vrai Chromium, joue quelques secondes et prend des captures.
// three.js est servi en local (le CDN n'est pas joignable depuis cet environnement).
const fs = require('fs'), path = require('path'), http = require('http');
const { chromium } = require('/opt/node22/lib/node_modules/playwright');

const ROOT = path.join(__dirname, '..');
const OUT = process.env.SHOT_DIR || path.join(ROOT, 'shots');
fs.mkdirSync(OUT, { recursive: true });

// vues : [nom, x, y, z du joueur, orientation]
const VIEWS = JSON.parse(fs.readFileSync(process.env.VUES || path.join(__dirname, 'views.json'), 'utf8'));


const HOOK = `
window.__SHOT = {
  ready: true,
  go(v) {
    // le champ de chat garde le focus d'un test a l'autre et avale alors toutes les
    // touches (le jeu ignore les keydown quand chatIn est actif) : on le relache.
    if (document.activeElement && document.activeElement.blur) document.activeElement.blur();
    // un test precedent peut laisser le joueur au volant, assis ou une fenetre ouverte :
    // on repart d'un etat propre, sinon les touches sont ignorees.
    try {
      if (uiOpen) closeUI();
      if (typeof city !== 'undefined' && city.rideBot && typeof botDescendre === 'function') botDescendre(city.rideBot, true);
      if (drive.car) exitCar();
      P.sit = null; P.swing = null; P.ride = null; P.eat = null; P.deco = null;
      P.run = false; P.court = false; P.essouffle = false; P.energie = 100;
      if (typeof gym !== 'undefined') gym.on = null;
    } catch (e) {}
    if (v.world != null && worldIdx !== v.world) loadWorld(v.world);
    document.body.classList.remove('lobby');
    document.getElementById('start').classList.add('hidden');
    document.getElementById('worlds').classList.add('hidden');
    running = true; paused = false; dead = false;
    // Un chef de gang peut donner rendez-vous et, quand on arrive sur place, la fenetre de
    // reunion MET LE JEU EN PAUSE : tous les tests qui suivaient echouaient alors sans
    // rapport avec ce qu'ils mesuraient. On repousse les rendez-vous spontanes ; le test de
    // la guerre des gangs, lui, appelle proposeReunion() explicitement.
    try {
      if (typeof guerre !== 'undefined') { guerre.reunion = null; guerre.prochaineReunion = simTime + 1e6; }
      if (typeof gangs !== 'undefined') for (const g of gangs) g.reunionT = simTime + 1e6;
    } catch (e) {}
    // Un test precedent peut laisser un bot au volant avec le joueur en passager : la boucle
    // de rendu replace alors l'avatar SUR LE BOT, a plusieurs metres de la ou il devrait
    // etre. Idem pour un coup en preparation, une mission de gang ou un defi en cours : tout
    // cela survit a loadWorld et faussait les tests suivants.
    try {
      if (typeof bots !== 'undefined') for (const b of bots) {
        if (b.drive && b.drive.car) { try { libereVoiture(b.drive.car); } catch (e2) {} }
        b.drive = null; b.rdv = null; b.rdvRoute = null; b.ordre = null; b.gangMission = null;
        b.activite = null; b.bagarre = null; b.garde = 0; b.fight = null;
        // Un bot laisse par le test precedent avec 3 PV, KO au sol, garde du corps ou poste
        // devant la villa faussait le test suivant sans aucun rapport avec ce qu'il mesurait.
        b.hp = 100; b.ko = 0; b.mort = 0; b.robbed = false;
        b.gardeCorps = 0; b.gardeVilla = 0; b.gardeArme = 0; b.protege = null; b.soin = 0;
        b.arme = false; b.journal = null; b.sport = null;
        if (!v.garderSauvegarde) b.perf = null;   // sauf quand le test verifie que la sauvegarde rend son niveau a chacun
        if (b.av) { b.av.group.rotation.x = 0; b.av.group.visible = true; }
      }
      if (typeof gang !== 'undefined') { if (!v.garderSauvegarde) gang.membres.length = 0; gang.mission = null; gang.rates = 0; if (gang.missions) gang.missions.length = 0; }
      // les effets d'impact survivent au changement de test (ils vieillissent dans la boucle
      // de rendu, qui tourne a peine dans le banc d'essai) : on repart d'une scene propre
      if (typeof fxClear === 'function') { try { fxClear(); } catch (e7) {} }
      // la deco posee et les colis livres par un test precedent changeaient le SOL sous les
      // pieds du test suivant : on repart d'un terrain nu
      try {
        for (const d of (city.placed || [])) { if (d.g) worldGroup.remove(d.g); if (d.solid) { const i = solids.indexOf(d.solid); if (i >= 0) solids.splice(i, 1); } }
        city.placed = [];
        for (const pc of (city.parcels || [])) worldGroup.remove(pc.g);
        city.parcels = [];
        localStorage.removeItem('superobby.decor'); localStorage.removeItem('superobby.colis');
        // la voiture et l'equipe rechargees par la sauvegarde ne doivent pas deborder d'un test a
        // l'autre — sauf quand le test verifie justement la sauvegarde (garderSauvegarde)
        if (!v.garderSauvegarde) { localStorage.removeItem('superobby.mavoiture'); if (typeof guerre !== 'undefined') guerre.sauvePerf = []; }
      } catch (e8) {}
      for (const b of bots) b.gangMission = null;
      // une partie de tennis ou de foot laissee en cours faussait le test suivant
      if (typeof finDuel === 'function') { try { finDuel('tennis'); finDuel('foot'); } catch (e4) {} }
      if (typeof P !== 'undefined' && P.racket) { P.racket = false; try { setRacket(me, false); } catch (e5) {} }
      if (typeof city !== 'undefined' && city.safes) { for (const sf of city.safes) { sf.progress = 0; sf.alerte = false; } city.safeNear = null; }
      if (typeof city !== 'undefined') { city.rideBot = null; city.botCarNear = null; }
      // Une voiture de police laissee au milieu de la rue par le test precedent « voit » le
      // joueur : la clemence sur les petits delits ne s'appliquait plus et le test suivant
      // echouait sans rapport avec ce qu'il mesurait. On renvoie tout le monde au poste.
      if (typeof police !== 'undefined') {
        try { clearWanted(); } catch (e2) {}
        police.avert = 0; police.avertT = -999; police.usure = 0; police.sait = null; police.lastSeen = null;
        for (const pc of (police.cars || [])) { if (pc.home) { pc.x = pc.home[0]; pc.z = pc.home[1]; }
          pc.active = false; pc.debarque = false; pc.speed = 0; pc.route = null; pc.vueT = 0; pc.vue = false;
          if (pc.g) pc.g.position.set(pc.x, pc.y || 0, pc.z); }
        for (let k = (police.agents || []).length - 1; k >= 0; k--) { const a = police.agents[k];
          try { scene.remove(a.av.group); const j = city.mannequins.indexOf(a.av); if (j >= 0) city.mannequins.splice(j, 1); } catch (e3) {}
          police.agents.splice(k, 1); }
      }
      if (typeof coup !== 'undefined') { coup.etat = 'aucun'; coup.bot = null; coup.car = null; }
      if (typeof gang !== 'undefined') gang.mission = null;
      if (typeof defi !== 'undefined') defi.on = null;
      if (typeof mission !== 'undefined' && mission.cur) endMission(false, true);
    } catch (e) {}
    // Les tests qui ont besoin d'un terrain degage poussent les figurants a 400 m ; sans ce
    // rappel ils n'en revenaient jamais et les tests suivants trouvaient une ville deserte.
    try {
      if (typeof bots !== 'undefined') for (const b of bots) {
        if (Math.abs(b.pos.x) < 260 && Math.abs(b.pos.z) < 340) continue;
        b.pos.set((Math.random() - 0.5) * 60, 0.3, 40 + (Math.random() - 0.5) * 60);
        b.av.group.position.copy(b.pos); b.av.group.visible = true; b.rdv = null; b.wait = 0;
      }
      if (typeof gangs !== 'undefined') for (const g of gangs) for (const m of g.membres) {
        if (Math.abs(m.x) < 260 && Math.abs(m.z) < 340) continue;
        m.x -= 400; m.z -= 400; if (m.av) m.av.group.position.set(m.x, m.y, m.z);
      }
    } catch (e11) {}
    if (!v.garderQualite && settings.quality !== 'high') { settings.quality = 'high'; try { applyQuality(); } catch (e12) {} }   // l'Ultra HD doublerait le temps du banc d'essai
    // Les ORDRES ne survivent pas d'un test a l'autre : un garde du corps, un protege, une
    // partie de tennis ou un rendez-vous laisses par le test precedent changeaient le
    // comportement de tout le monde dans le suivant (le garde revenait « a sa place »...).
    try {
      if (typeof bots !== 'undefined') for (const b of bots) { b.gardeCorps = 0; b.garde = 0; b.gardeVilla = 0; b.protege = null; b.gardeArme = 0; b.sport = null; b.rdv = null; b.rdvRoute = null; b.drive = null; b.bagarre = null; b.fight = null; b.ordre = null; b.slotGarde = 0; b.activite = null; }
      if (typeof tm !== 'undefined') { tm.on = false; tm.bot = null; }
      if (typeof fm !== 'undefined') { fm.on = false; fm.bot = null; }
      if (typeof gang !== 'undefined') { gang.mission = null; if (gang.missions) gang.missions.length = 0; }
    } catch (e13) {}
    settings.ctrl = 'cam';                       // la caméra ne suit plus l'orientation du joueur
    // L'heure se pilote par simTime (journee de 7 h a 19 h). Mais l'horloge ne doit JAMAIS
    // reculer : des minuteries posees par un test precedent (le prochain habitant qui va au
    // casino, la prochaine reunion de gang...) vivent sur des objets qui, eux, survivent, et
    // se retrouvaient alors dans un futur inatteignable. On avance donc d'un nombre entier de
    // journees : meme heure affichee, horloge toujours croissante.
    if (v.hour != null) {
      const cible = ((v.hour - 7 + 12) % 12) / 12 * day.len;
      const jours = Math.max(0, Math.ceil((simTime - cible) / day.len));
      simTime = cible + jours * day.len;
    }
    // La camera suit le joueur en douceur : apres une teleportation elle met plusieurs images
    // a le rattraper, et une mesure prise entre-temps porte sur une camera encore en route.
    // On la pose donc d'un coup sur le nouveau point de vue.
    if (v.x != null) { P.pos.set(v.x, v.y, v.z); P.vel.set(0, 0, 0); cam.target.set(v.x, v.y + 1.5, v.z); }
    if (v.facing != null) P.facing = v.facing;
    cam.yaw = v.yaw != null ? v.yaw : P.facing;
    if (v.pitch != null) cam.pitch = v.pitch;
    if (v.dist != null) { cam.base = v.dist; cam.dist = v.dist; }
    cam.freeUntil = 1e9;                         // fige l'orientation demandée
    if (v.tv && typeof modeTV === 'function') modeTV(true); else if (v.tv === false && typeof modeTV === 'function') modeTV(false);
    if (v.salonTV && typeof ouvreSalonTV === 'function') { try { ouvreSalonTV(); } catch (e9) {} }
    if (v.menu && typeof toggleMenu === 'function') { try { toggleMenu(true); } catch (e14) {} }   // capture du menu des reglages (poste F)
    if (v.mixOuvert) { try { document.getElementById('mixBloc').open = true; document.getElementById('mixBloc').scrollIntoView(); } catch (e15) {} }
    if (v.manette && typeof manetteOuvre === 'function') { try { manetteOuvre(''); document.getElementById('manette').classList.add('pret'); } catch (e10) {} }
    if (v.hideHud) document.querySelectorAll('#top,#chat,#radar,#act,#missionHud').forEach(function (e) { e.style.display = 'none'; });
    if (v.noClip) { P.pos.y = v.y; P.vel.set(0, 0, 0); }
    if (v.sansBots) bots.forEach(function (b) { b.av.group.visible = false; });
    if (v.dormir) { const b = city.beds[0]; if (b) { P.pos.set(b.x, b.y + 1, b.z); city.bedNear = b; sleepBed(); } }
    if (v.arme) { owned.add('arme:' + v.arme); equipWeapon(v.arme); drawWeapon(true); P.aimPitch = v.pitchVisee || 0; }
    if (v.raquette) { P.racket = true; setRacket(me, true); }
    if (v.atelier) {   // une voiture posée sur la travée de l'atelier, pour la capture
      try { for (const c of city.cars) { c.x += 300; c.z += 300; c.g.position.set(c.x, c.y, c.z); }
        amenerVoitureAtelier(); } catch (e) {}
    }
    if (v.coup) {   // un coup en cours, figé au bon instant, pour juger l'impact
      try {
        const b = bots[0];
        b.pos.set(P.pos.x + Math.sin(P.facing) * 1.5, P.pos.y, P.pos.z + Math.cos(P.facing) * 1.5);
        b.rdv = null; b.wait = 9; b.ko = 0; b.hp = 100; b.av.group.visible = true;
        b.av.group.position.copy(b.pos); b.facing = P.facing + Math.PI; b.av.group.rotation.y = b.facing;
        setTimeout(function () { try { P.punchT = 0; P.combo = v.coup === 'combo' ? 2 : 0; attack(v.coup === 'kick' ? 'kick' : 'punch'); } catch (e) {} }, Math.max(300, (v.wait || 1200) - 90));
      } catch (e) {}
    }
    if (v.balleMur) {   // une balle qui vient de frapper le décor
      try { setTimeout(function () { try { impact(P.pos.x + Math.sin(P.facing) * 3, P.pos.y + 1.3, P.pos.z + Math.cos(P.facing) * 3, { x: Math.sin(P.facing), y: 0, z: Math.cos(P.facing) }, 'mur', 1.2); } catch (e) {} }, Math.max(300, (v.wait || 1200) - 90)); } catch (e) {}
    }
    if (v.partie) {   // une partie de sport contre un membre, pour la capture
      try {
        const b = bots[0];
        amis.add(b.name);
        b.pos.set(v.partie === 'foot' ? -19 : 13, 0.3, v.partie === 'foot' ? -13 : -17.4);
        b.rdv = null; b.wait = 0; b.ko = 0; b.av.group.visible = true;
        b.sport = { jeu: v.partie, cote: v.partie === 'foot' ? 0 : 1, pret: true };
        if (v.partie === 'tennis') { setRacket(b.av, true); P.racket = true; setRacket(me, true); }
        b.facing = Math.atan2(P.pos.x - b.pos.x, P.pos.z - b.pos.z);
        b.av.group.position.copy(b.pos); b.av.group.rotation.y = b.facing;
      } catch (e) {}
    }
    // poste J : plante une scene de metier (chantier, incendie, facteur, balayeur, laveur)
    if (v.metier && typeof metierScene === 'function') { try { metierScene(v.metier); } catch (e14) {} }
    // poste Animation : fige un mouvement sur une image PRECISE, pour photographier une
    // serie d'instants successifs du meme geste (v.anim = { combat, u, garde, geste, t, opt }).
    if (typeof ANIM !== 'undefined' && ANIM) {
      ANIM.fige = v.anim || null;
      if (v.anim && v.anim.adversaire) {   // un adversaire plante devant le joueur, pour le combat
        try {
          const b = bots[0];
          b.pos.set(P.pos.x + Math.sin(P.facing) * 1.35, P.pos.y, P.pos.z + Math.cos(P.facing) * 1.35);
          b.rdv = null; b.wait = 99; b.ko = 0; b.hp = 100; b.fight = null; b.av.group.visible = true;
          b.av.group.position.copy(b.pos); b.facing = P.facing + Math.PI; b.av.group.rotation.y = b.facing;
        } catch (e15) {}
      }
    }
  },
  stats() { return { calls: renderer.info.render.calls, tris: renderer.info.render.triangles,
    world: worldIdx, solides: solids.length, heure: +day.h.toFixed(1), nuit: +day.night.toFixed(2) }; }
};
window.__G = {
  P, city, drive, police, jail, bank, mission, net, race, gym, cam, settings, me, bots, RALLY, tm, shared, ballMats, owned,
  updateBot, tennisMatchTick, policeTick, worldGroup, THREE,
  fm: typeof fm !== 'undefined' ? fm : null,
  joy: typeof joy !== 'undefined' ? joy : null,
  ROT_MORTE: typeof ROT_MORTE !== 'undefined' ? ROT_MORTE : 0,
  PAD_MAP: typeof PAD_MAP !== 'undefined' ? PAD_MAP : null,
  PT_ROLES: typeof PT_ROLES !== 'undefined' ? PT_ROLES : null,
  padLu: typeof padLu === 'function' ? padLu : null,
  padProfil: typeof padProfil === 'function' ? padProfil : null,
  padChapeau: typeof padChapeau === 'function' ? padChapeau : null,
  padCourse: typeof padCourse === 'function' ? padCourse : null,
  padActif: typeof padActif === 'function' ? padActif : null,
  padAction: typeof padAction === 'function' ? padAction : null,
  padEssaiTick: typeof padEssaiTick === 'function' ? padEssaiTick : null,
  ouvreTestManette: typeof ouvreTestManette === 'function' ? ouvreTestManette : null,
  armeSuivante: typeof armeSuivante === 'function' ? armeSuivante : null,
  PAD_CROIX_LONG: typeof PAD_CROIX_LONG !== 'undefined' ? PAD_CROIX_LONG : null,
  PAD_LONG: typeof PAD_LONG !== 'undefined' ? PAD_LONG : 0,
  PAD_BOUTONS: typeof PAD_BOUTONS !== 'undefined' ? PAD_BOUTONS : 0,
  readInput: typeof readInput === 'function' ? readInput : null,
  driveStep: typeof driveStep === 'function' ? driveStep : null,
  diffusion: typeof diffusion !== 'undefined' ? diffusion : null,
  diffusionMode: typeof diffusionMode === 'function' ? diffusionMode : null,
  diffusionMesure: typeof diffusionMesure === 'function' ? diffusionMesure : null,
  PALIERS_TV: typeof PALIERS_TV !== 'undefined' ? PALIERS_TV : null,
  paliersActifs: typeof paliersActifs === 'function' ? paliersActifs : null,
  DIFFUSION_CIBLE: typeof DIFFUSION_CIBLE !== 'undefined' ? DIFFUSION_CIBLE : 0,
  tvSalonMaj: typeof tvSalonMaj === 'function' ? tvSalonMaj : null,
  TENNIS_ZONE: typeof TENNIS_ZONE !== 'undefined' ? TENNIS_ZONE : null,
  FOOT_ZONE: typeof FOOT_ZONE !== 'undefined' ? FOOT_ZONE : null,
  DUEL_GAGNANTS: typeof DUEL_GAGNANTS !== 'undefined' ? DUEL_GAGNANTS : 0,
  botSport: typeof botSport === 'function' ? botSport : null,
  botSportif: typeof botSportif === 'function' ? botSportif : null,
  sportBotTick: typeof sportBotTick === 'function' ? sportBotTick : null,
  footMatchTick: typeof footMatchTick === 'function' ? footMatchTick : null,
  courtPlayers: typeof courtPlayers === 'function' ? courtPlayers : null,
  toggleRacket: typeof toggleRacket === 'function' ? toggleRacket : null,
  setRacket: typeof setRacket === 'function' ? setRacket : null,
  finDuel: typeof finDuel === 'function' ? finDuel : null,
  fx: typeof fx !== 'undefined' ? fx : null,
  impact: typeof impact === 'function' ? impact : null,
  gangeurKO: typeof gangeurKO === 'function' ? gangeurKO : null,
  corpsAuSol: typeof corpsAuSol === 'function' ? corpsAuSol : null,
  groundUnder: typeof groundUnder === 'function' ? groundUnder : null,
  gang: typeof gang !== 'undefined' ? gang : null,
  fxTick: typeof fxTick === 'function' ? fxTick : null,
  fxTrainee: typeof fxTrainee === 'function' ? fxTrainee : null,
  camSecousse: typeof camSecousse === 'function' ? camSecousse : null,
  noteOrdre: typeof noteOrdre === 'function' ? noteOrdre : null,
  finirOrdre: typeof finirOrdre === 'function' ? finirOrdre : null,
  journalHtml: typeof journalHtml === 'function' ? journalHtml : null,
  missionGang: typeof missionGang === 'function' ? missionGang : null,
  tuerMembre: typeof tuerMembre === 'function' ? tuerMembre : null,
  conduire: typeof conduire === 'function' ? conduire : null,
  commandesManette: typeof commandesManette === 'function' ? commandesManette : null,
  conduireVersPoint: typeof conduireVersPoint === 'function' ? conduireVersPoint : null,
  calerRoues: typeof calerRoues === 'function' ? calerRoues : null,
  prepareVehicule: typeof prepareVehicule === 'function' ? prepareVehicule : null,
  rouesTick: typeof rouesTick === 'function' ? rouesTick : null,
  fumeeRoues: typeof fumeeRoues === 'function' ? fumeeRoues : null,
  poseVehicule: typeof poseVehicule === 'function' ? poseVehicule : null,
  moteurRegime: typeof moteurRegime === 'function' ? moteurRegime : null,
  petarade: typeof petarade === 'function' ? petarade : null,
  boom: typeof boom === 'function' ? boom : null,
  choc: typeof choc === 'function' ? choc : null,
  ecraseAuSol: typeof ecraseAuSol === 'function' ? ecraseAuSol : null,
  ouvreAccident: typeof ouvreAccident === 'function' ? ouvreAccident : null,
  accidentsTick: typeof accidentsTick === 'function' ? accidentsTick : null,
  regleAccident: typeof regleAccident === 'function' ? regleAccident : null,
  rouleVers: typeof rouleVers === 'function' ? rouleVers : null,
  PLACES: typeof PLACES !== 'undefined' ? PLACES : null,
  PLACES_ORDRE: typeof PLACES_ORDRE !== 'undefined' ? PLACES_ORDRE : null,
  placesDe: typeof placesDe === 'function' ? placesDe : null,
  placeMonde: typeof placeMonde === 'function' ? placeMonde : null,
  assiedAvatar: typeof assiedAvatar === 'function' ? assiedAvatar : null,
  assiedChien: typeof assiedChien === 'function' ? assiedChien : null,
  placeOccupants: typeof placeOccupants === 'function' ? placeOccupants : null,
  makeDepanneuse: typeof makeDepanneuse === 'function' ? makeDepanneuse : null,
  poseAccident: typeof poseAccident === 'function' ? poseAccident : null,
  camConduite: typeof camConduite === 'function' ? camConduite : null,
  vitesseRel: typeof vitesseRel === 'function' ? vitesseRel : null,
  reculConduite: typeof reculConduite === 'function' ? reculConduite : null,
  poseJoueurAuVolant: typeof poseJoueurAuVolant === 'function' ? poseJoueurAuVolant : null,
  makeVehiculeTravail: typeof makeVehiculeTravail === 'function' ? makeVehiculeTravail : null,
  solSousRoues: typeof solSousRoues === 'function' ? solSousRoues : null,
  depanneuseAppel: typeof depanneuseAppel === 'function' ? depanneuseAppel : null,
  depanneusesTick: typeof depanneusesTick === 'function' ? depanneusesTick : null,
  makeAmbulance: typeof makeAmbulance === 'function' ? makeAmbulance : null,
  ambulanceAppel: typeof ambulanceAppel === 'function' ? ambulanceAppel : null,
  ambulancesTick: typeof ambulancesTick === 'function' ? ambulancesTick : null,
  urgencesTick: typeof urgencesTick === 'function' ? urgencesTick : null,
  servicesTick: typeof servicesTick === 'function' ? servicesTick : null,
  nitroGo: typeof nitroGo === 'function' ? nitroGo : null,
  nitroTick: typeof nitroTick === 'function' ? nitroTick : null,
  jambesEnCabine: typeof jambesEnCabine === 'function' ? jambesEnCabine : null,
  caisseFermee: typeof caisseFermee !== 'undefined' ? caisseFermee : null,
  groundCar: typeof groundCar === 'function' ? groundCar : null,
  camera: typeof camera !== 'undefined' ? camera : null,
  cam: typeof cam !== 'undefined' ? cam : null,
  horn: typeof horn === 'function' ? horn : null,
  entrainerMembre: typeof entrainerMembre === 'function' ? entrainerMembre : null,
  inZone: typeof inZone === 'function' ? inZone : null,
  loadWorld, cityReset, enterCar, exitCar, openUI, closeUI, takeAway, eatCarried, openFridge,
  respawn, die, msg, chat, infraction, clearWanted, jailEnter, jailFree, startMission, endMission,
  toggleMenu, applyMyLook, buildNav, navPath, throwGrenade, equipWeapon, fire, punch, kick, sitBench,
  get solids() { return solids; }, get breakables() { return breakables; }, get shots() { return shots; },
  get grenades() { return grenades; }, get debris() { return debrisParts; }, get uiOpen() { return uiOpen; },
  get paused() { return paused; }, get running() { return running; }, get wallet() { return wallet; },
  get mort() { return dead; }, get gagne() { return won; }, get loopErr() { return typeof loopErr !== 'undefined' ? loopErr : -1; },
  get worldIdx() { return worldIdx; }, get simTime() { return simTime; },
  set wallet(v) { wallet = v; }, set running(v) { running = v; },
  set simTime(v) { simTime = v; },   // les tests avancent l'horloge de simulation sans attendre le rendu
  aimTick, fire, drawWeapon, WEAPONS, vehicleDamage, fumeeTick, makeTarget, explodeVehicle, sitBench, sleepBed, placeDecor, repairVisual, rideEnter, infraction,
  // ces outils n'existent que dans la version corrigée : le crochet doit rester chargeable
  // sur la version d'origine pour pouvoir comparer les deux
  cityStep, cityCommon, startCountdown, sitSwing, swingTick, schQuestion, nextQuestion, answer, openSchool, school, voice, deliverDecor, grabParcel, dropDecor, DECOR, shotsTick, safesTick, keys, decorMesh,
  schTirage: typeof schTirage === 'function' ? schTirage : null,
  schDire: typeof schDire === 'function' ? schDire : null,
  schLire: typeof schLire === 'function' ? schLire : null,
  amis: typeof amis !== 'undefined' ? amis : null,
  chien: typeof chien !== 'undefined' ? chien : null,
  coup: typeof coup !== 'undefined' ? coup : null,
  commandeSociale: typeof commandeSociale === 'function' ? commandeSociale : null,
  chienTick: typeof chienTick === 'function' ? chienTick : null,
  coupTick: typeof coupTick === 'function' ? coupTick : null,
  coupAlerte: typeof coupAlerte === 'function' ? coupAlerte : null,
  coupMonter: typeof coupMonter === 'function' ? coupMonter : null,
  botPrendVoiture: typeof botPrendVoiture === 'function' ? botPrendVoiture : null,
  botConduireVers: typeof botConduireVers === 'function' ? botConduireVers : null,
  botDriveTick: typeof botDriveTick === 'function' ? botDriveTick : null,
  monterAvecBot: typeof monterAvecBot === 'function' ? monterAvecBot : null,
  botDescendre: typeof botDescendre === 'function' ? botDescendre : null,
  micro: typeof micro !== 'undefined' ? micro : null,
  chienAttaque: typeof chienAttaque === 'function' ? chienAttaque : null,
  aboie: typeof aboie === 'function' ? aboie : null,
  adopterChien: typeof adopterChien === 'function' ? adopterChien : null,
  petsTick, sitBench, sleepBed, store, updateBot,
  parcelTick, dropDecor, grabParcel, placeLibre, retirerDeco, reprendreDeco, pointPose, murProche, loadDecor, decorSave, sousToit,
  QR: typeof QR !== 'undefined' ? QR : null,
  tv: typeof tv !== 'undefined' ? tv : null,
  tel: typeof tel !== 'undefined' ? tel : null,
  tableauMaj: typeof tableauMaj === 'function' ? tableauMaj : null,
  tableauPose: typeof tableauPose === 'function' ? tableauPose : null,
  tableauRendu: typeof tableauRendu === 'function' ? tableauRendu : null,
  tableauQuestion: typeof tableauQuestion === 'function' ? tableauQuestion : null,
  tableauVerdict: typeof tableauVerdict === 'function' ? tableauVerdict : null,
  craieTick: typeof craieTick === 'function' ? craieTick : null,
  camTableau: typeof camTableau === 'function' ? camTableau : null,
  schoolTick: typeof schoolTick === 'function' ? schoolTick : null,
  sonCraie: typeof sonCraie === 'function' ? sonCraie : null,
  bulleMaitresse: typeof bulleMaitresse === 'function' ? bulleMaitresse : null,
  CRAIE_CPS: typeof CRAIE_CPS !== 'undefined' ? CRAIE_CPS : 0,
  man: typeof man !== 'undefined' ? man : null,
  pad: typeof pad !== 'undefined' ? pad : null,
  telCommande: typeof telCommande === 'function' ? telCommande : null,
  modeTV: typeof modeTV === 'function' ? modeTV : null,
  ouvreSalonTV: typeof ouvreSalonTV === 'function' ? ouvreSalonTV : null,
  manetteOuvre: typeof manetteOuvre === 'function' ? manetteOuvre : null,
  manetteFerme: typeof manetteFerme === 'function' ? manetteFerme : null,
  navBouge: typeof navBouge === 'function' ? navBouge : null,
  netTeardown: typeof netTeardown === 'function' ? netTeardown : null,
  navValide: typeof navValide === 'function' ? navValide : null,
  pollGamepad: typeof pollGamepad === 'function' ? pollGamepad : null,
  setWeapon: typeof setWeapon === 'function' ? setWeapon : null,
  creerAgent: typeof creerAgent === 'function' ? creerAgent : null,
  SHOP: typeof SHOP !== 'undefined' ? SHOP : null,
  CHAUSSURES: typeof CHAUSSURES !== 'undefined' ? CHAUSSURES : null,
  myCfg: typeof myCfg !== 'undefined' ? myCfg : null,
  myLook: typeof myLook === 'function' ? myLook : null,
  applyShopItem: typeof applyShopItem === 'function' ? applyShopItem : null,
  currentShopId: typeof currentShopId === 'function' ? currentShopId : null,
  catalog: typeof catalog === 'function' ? catalog : null,
  openStore: typeof openStore === 'function' ? openStore : null,
  TATOO_MOTIFS: typeof TATOO_MOTIFS !== 'undefined' ? TATOO_MOTIFS : null,
  TATOO_ZONES: typeof TATOO_ZONES !== 'undefined' ? TATOO_ZONES : null,
  TATOO_ENCRES: typeof TATOO_ENCRES !== 'undefined' ? TATOO_ENCRES : null,
  TATOO_TAILLES: typeof TATOO_TAILLES !== 'undefined' ? TATOO_TAILLES : null,
  tatoo: typeof tatoo !== 'undefined' ? tatoo : null,
  openTatoo: typeof openTatoo === 'function' ? openTatoo : null,
  tatouer: typeof tatouer === 'function' ? tatouer : null,
  poseTatouages: typeof poseTatouages === 'function' ? poseTatouages : null,
  tatooTexture: typeof tatooTexture === 'function' ? tatooTexture : null,
  applyLook: typeof applyLook === 'function' ? applyLook : null,
  gang: typeof gang !== 'undefined' ? gang : null,
  guerre: typeof guerre !== 'undefined' ? guerre : null,
  guerreTick: typeof guerreTick === 'function' ? guerreTick : null,
  recruteVaincu: typeof recruteVaincu === 'function' ? recruteVaincu : null,
  recruesTick: typeof recruesTick === 'function' ? recruesTick : null,
  majHudGuerre: typeof majHudGuerre === 'function' ? majHudGuerre : null,
  bank: typeof bank !== 'undefined' ? bank : null,
  buildGangs: typeof buildGangs === 'function' ? buildGangs : null,
  driveStep: typeof driveStep === 'function' ? driveStep : null,
  step: typeof step === 'function' ? step : null,
  SGRID: typeof SGRID !== 'undefined' ? SGRID : null,
  buildSGrid: typeof buildSGrid === 'function' ? buildSGrid : null,
  solidsPres: typeof solidsPres === 'function' ? solidsPres : null,
  solidsAutour: typeof solidsAutour === 'function' ? solidsAutour : null,
  sgridSale: typeof sgridSale === 'function' ? sgridSale : null,
  SGRID: typeof SGRID === 'object' ? SGRID : null,
  gangeurKO: typeof gangeurKO === 'function' ? gangeurKO : null,
  verifieElimination: typeof verifieElimination === 'function' ? verifieElimination : null,
  renaitGang: typeof renaitGang === 'function' ? renaitGang : null,
  GANTS: typeof GANTS !== 'undefined' ? GANTS : null,
  SAC_BANANE: typeof SAC_BANANE !== 'undefined' ? SAC_BANANE : null,
  poseChaussures: typeof poseChaussures === 'function' ? poseChaussures : null,
  poseGants: typeof poseGants === 'function' ? poseGants : null,
  mainDroite: typeof mainDroite === 'function' ? mainDroite : null,
  JERSEYS: typeof JERSEYS !== 'undefined' ? JERSEYS : null,
  jerseyOf: typeof jerseyOf === 'function' ? jerseyOf : null,
  itemKey: typeof itemKey === 'function' ? itemKey : null,
  rangementAuto: typeof rangementAuto === 'function' ? rangementAuto : null,
  setEtuis: typeof setEtuis === 'function' ? setEtuis : null,
  mesEtuis: typeof mesEtuis === 'function' ? mesEtuis : null,
  majEtuis: typeof majEtuis === 'function' ? majEtuis : null,
  appuiDosMonde: typeof appuiDosMonde === 'function' ? appuiDosMonde : null,
  knifeMesh: typeof knifeMesh === 'function' ? knifeMesh : null,
  coupCouteau: typeof coupCouteau === 'function' ? coupCouteau : null,
  garde: typeof garde === 'function' ? garde : null,
  esquive: typeof esquive === 'function' ? esquive : null,
  setGarde: typeof setGarde === 'function' ? setGarde : null,
  setAccroupi: typeof setAccroupi === 'function' ? setAccroupi : null,
  defenseJoueur: typeof defenseJoueur === 'function' ? defenseJoueur : null,
  hurt: typeof hurt === 'function' ? hurt : null,
  attack: typeof attack === 'function' ? attack : null,
  combatTick: typeof combatTick === 'function' ? combatTick : null,
  brancardMesh: typeof brancardMesh === 'function' ? brancardMesh : null,
  creerBrancard: typeof creerBrancard === 'function' ? creerBrancard : null,
  porterBrancard: typeof porterBrancard === 'function' ? porterBrancard : null,
  poserBrancard: typeof poserBrancard === 'function' ? poserBrancard : null,
  allongerSurBrancard: typeof allongerSurBrancard === 'function' ? allongerSurBrancard : null,
  descendreDuBrancard: typeof descendreDuBrancard === 'function' ? descendreDuBrancard : null,
  chargerBrancard: typeof chargerBrancard === 'function' ? chargerBrancard : null,
  sortirBrancard: typeof sortirBrancard === 'function' ? sortirBrancard : null,
  brancardTick: typeof brancardTick === 'function' ? brancardTick : null,
  brancardEtat: typeof brancardEtat === 'function' ? brancardEtat : null,
  creerAmbulancier: typeof creerAmbulancier === 'function' ? creerAmbulancier : null,
  embarqueBlesse: typeof embarqueBlesse === 'function' ? embarqueBlesse : null,
  peutKidnapper: typeof peutKidnapper === 'function' ? peutKidnapper : null,
  kidnapper: typeof kidnapper === 'function' ? kidnapper : null,
  otageTick: typeof otageTick === 'function' ? otageTick : null,
  otageProche: typeof otageProche === 'function' ? otageProche : null,
  interroger: typeof interroger === 'function' ? interroger : null,
  libereOtage: typeof libereOtage === 'function' ? libereOtage : null,
  entrainerMembre: typeof entrainerMembre === 'function' ? entrainerMembre : null,
  entrainementTick: typeof entrainementTick === 'function' ? entrainementTick : null,
  armerMembre: typeof armerMembre === 'function' ? armerMembre : null,
  proposeReunion: typeof proposeReunion === 'function' ? proposeReunion : null,
  reunionTick: typeof reunionTick === 'function' ? reunionTick : null,
  openReunion: typeof openReunion === 'function' ? openReunion : null,
  choixReunion: typeof choixReunion === 'function' ? choixReunion : null,
  captureTick: typeof captureTick === 'function' ? captureTick : null,
  revenusTick: typeof revenusTick === 'function' ? revenusTick : null,
  repriseTick: typeof repriseTick === 'function' ? repriseTick : null,
  territoireDe: typeof territoireDe === 'function' ? territoireDe : null,
  rangJoueur: typeof rangJoueur === 'function' ? rangJoueur : null,
  gagneRep: typeof gagneRep === 'function' ? gagneRep : null,
  openGuerre: typeof openGuerre === 'function' ? openGuerre : null,
  majGuerre: typeof majGuerre === 'function' ? majGuerre : null,
  saveGuerre: typeof saveGuerre === 'function' ? saveGuerre : null,
  loadGuerre: typeof loadGuerre === 'function' ? loadGuerre : null,
  attack: typeof attack === 'function' ? attack : null,
  nearestFighter: typeof nearestFighter === 'function' ? nearestFighter : null,
  marqueImpact: typeof marqueImpact === 'function' ? marqueImpact : null,
  nommeLesBatiments: typeof nommeLesBatiments === 'function' ? nommeLesBatiments : null,
  degageDecorSurRoutes: typeof degageDecorSurRoutes === 'function' ? degageDecorSurRoutes : null,
  chocDecor: typeof chocDecor === 'function' ? chocDecor : null,
  solideTouche: typeof solideTouche === 'function' ? solideTouche : null,
  batimentTouche: typeof batimentTouche === 'function' ? batimentTouche : null,
  faceTouchee: typeof faceTouchee === 'function' ? faceTouchee : null,
  sorteSelonForce: typeof sorteSelonForce === 'function' ? sorteSelonForce : null,
  effaceMarques: typeof effaceMarques === 'function' ? effaceMarques : null,
  MARQUES_MAX: typeof MARQUES_MAX !== 'undefined' ? MARQUES_MAX : null,
  MARQUES_MUR_MAX: typeof MARQUES_MUR_MAX !== 'undefined' ? MARQUES_MUR_MAX : null,
  MARQUE_SORTES: typeof MARQUE_SORTES !== 'undefined' ? MARQUE_SORTES : null,
  get marquesMesh() { return typeof marquesMesh !== 'undefined' ? marquesMesh : null; },
  fragile: typeof fragile === 'function' ? fragile : null,
  bonhommeNeige: typeof bonhommeNeige === 'function' ? bonhommeNeige : null,
  coneRue: typeof coneRue === 'function' ? coneRue : null,
  CASSE_DEF: typeof CASSE_DEF !== 'undefined' ? CASSE_DEF : null,
  breakThing: typeof breakThing === 'function' ? breakThing : null,
  repareChose: typeof repareChose === 'function' ? repareChose : null,
  chercheCasse: typeof chercheCasse === 'function' ? chercheCasse : null,
  repareCible: typeof repareCible === 'function' ? repareCible : null,
  buildNeigeDecor: typeof buildNeigeDecor === 'function' ? buildNeigeDecor : null,
  neigeDecor: typeof neigeDecor === 'function' ? neigeDecor : null,
  driveStep: typeof driveStep === 'function' ? driveStep : null,
  poubelle: typeof poubelle === 'function' ? poubelle : null,
  lightsTick: typeof lightsTick === 'function' ? lightsTick : null,
  feuPhase: typeof feuPhase === 'function' ? feuPhase : null,
  ligneFeu: typeof ligneFeu === 'function' ? ligneFeu : null,
  trafficLight: typeof trafficLight === 'function' ? trafficLight : null,
  signalisation: typeof signalisation === 'function' ? signalisation : null,
  carrefours: typeof carrefours === 'function' ? carrefours : null,
  panneau: typeof panneau === 'function' ? panneau : null,
  crosswalk: typeof crosswalk === 'function' ? crosswalk : null,
  roleVoie: typeof roleVoie === 'function' ? roleVoie : null,
  VOIES: typeof VOIES !== 'undefined' ? VOIES : null,
  FEU_VERT: typeof FEU_VERT !== 'undefined' ? FEU_VERT : null,
  FEU_ORANGE: typeof FEU_ORANGE !== 'undefined' ? FEU_ORANGE : null,
  FEU_CYCLE: typeof FEU_CYCLE !== 'undefined' ? FEU_CYCLE : null,
  PLAN_ROUTIER: typeof PLAN_ROUTIER !== 'undefined' ? PLAN_ROUTIER : null,
  trottoirs: typeof trottoirs === 'function' ? trottoirs : null,
  decorPublic: typeof decorPublic === 'function' ? decorPublic : null,
  degageLesRoutes: typeof degageLesRoutes === 'function' ? degageLesRoutes : null,
  finirPlan: typeof finirPlan === 'function' ? finirPlan : null,
  openEtal: typeof openEtal === 'function' ? openEtal : null,
  majEtal: typeof majEtal === 'function' ? majEtal : null,
  acheterArticle: typeof acheterArticle === 'function' ? acheterArticle : null,
  MARCHE: typeof MARCHE !== 'undefined' ? MARCHE : null,
  VILLA_HALF: typeof VILLA_HALF !== 'undefined' ? VILLA_HALF : null,
  TECHNO: typeof TECHNO !== 'undefined' ? TECHNO : null,
  TERRITOIRES: typeof TERRITOIRES !== 'undefined' ? TERRITOIRES : null,
  buildPlanque: typeof buildPlanque === 'function' ? buildPlanque : null,
  creerGangeur: typeof creerGangeur === 'function' ? creerGangeur : null,
  CHEFS_NOMS: typeof CHEFS_NOMS !== 'undefined' ? CHEFS_NOMS : null,
  RANGS: typeof RANGS !== 'undefined' ? RANGS : null,
  gangs: typeof gangs !== 'undefined' ? gangs : null,
  GANG_DEFS: typeof GANG_DEFS !== 'undefined' ? GANG_DEFS : null,
  GANG_MISSIONS: typeof GANG_MISSIONS !== 'undefined' ? GANG_MISSIONS : null,
  GANG_ORDRES: typeof GANG_ORDRES !== 'undefined' ? GANG_ORDRES : null,
  rejoindreGang: typeof rejoindreGang === 'function' ? rejoindreGang : null,
  quitterGang: typeof quitterGang === 'function' ? quitterGang : null,
  estDuGang: typeof estDuGang === 'function' ? estDuGang : null,
  missionGang: typeof missionGang === 'function' ? missionGang : null,
  gangMissionTick: typeof gangMissionTick === 'function' ? gangMissionTick : null,
  gangTick: typeof gangTick === 'function' ? gangTick : null,
  buildGangs: typeof buildGangs === 'function' ? buildGangs : null,
  ordreGang: typeof ordreGang === 'function' ? ordreGang : null,
  trouveBots: typeof trouveBots === 'function' ? trouveBots : null,
  cambrio: typeof cambrio !== 'undefined' ? cambrio : null,
  declencheCambriolage: typeof declencheCambriolage === 'function' ? declencheCambriolage : null,
  cambrioTick: typeof cambrioTick === 'function' ? cambrioTick : null,
  cambrioFin: typeof cambrioFin === 'function' ? cambrioFin : null,
  alarmeInstallee: typeof alarmeInstallee === 'function' ? alarmeInstallee : null,
  DECOR: typeof DECOR !== 'undefined' ? DECOR : null,
  decorMesh: typeof decorMesh === 'function' ? decorMesh : null,
  tenueMetier: typeof tenueMetier !== 'undefined' ? tenueMetier : null,
  METIERS_DEF: typeof METIERS_DEF !== 'undefined' ? METIERS_DEF : null,
  METIERS: typeof METIERS !== 'undefined' ? METIERS : null,
  MET_C: typeof MET_C !== 'undefined' ? MET_C : null,
  outilMesh: typeof outilMesh !== 'undefined' ? outilMesh : null,
  donneOutil: typeof donneOutil !== 'undefined' ? donneOutil : null,
  makeVehiculeTravail: typeof makeVehiculeTravail !== 'undefined' ? makeVehiculeTravail : null,
  actionneOutil: typeof actionneOutil !== 'undefined' ? actionneOutil : null,
  outilsVehiculesTick: typeof outilsVehiculesTick !== 'undefined' ? outilsVehiculesTick : null,
  arroseAutour: typeof arroseAutour !== 'undefined' ? arroseAutour : null,
  poseChantier: typeof poseChantier !== 'undefined' ? poseChantier : null,
  retireChantier: typeof retireChantier !== 'undefined' ? retireChantier : null,
  poseNidDePoule: typeof poseNidDePoule !== 'undefined' ? poseNidDePoule : null,
  boucheNidDePoule: typeof boucheNidDePoule !== 'undefined' ? boucheNidDePoule : null,
  poseDetritus: typeof poseDetritus !== 'undefined' ? poseDetritus : null,
  ramasseDetritus: typeof ramasseDetritus !== 'undefined' ? ramasseDetritus : null,
  boiteAuxLettres: typeof boiteAuxLettres !== 'undefined' ? boiteAuxLettres : null,
  declencheIncendie: typeof declencheIncendie !== 'undefined' ? declencheIncendie : null,
  incendiesTick: typeof incendiesTick !== 'undefined' ? incendiesTick : null,
  buildMetiers: typeof buildMetiers !== 'undefined' ? buildMetiers : null,
  metiersReset: typeof metiersReset !== 'undefined' ? metiersReset : null,
  metiersTick: typeof metiersTick !== 'undefined' ? metiersTick : null,
  metiersRepos: typeof metiersRepos !== 'undefined' ? metiersRepos : null,
  employesTick: typeof employesTick !== 'undefined' ? employesTick : null,
  pompiersTick: typeof pompiersTick !== 'undefined' ? pompiersTick : null,
  balayeurTick: typeof balayeurTick !== 'undefined' ? balayeurTick : null,
  laveurTick: typeof laveurTick !== 'undefined' ? laveurTick : null,
  facteurTick: typeof facteurTick !== 'undefined' ? facteurTick : null,
  chercheCasse: typeof chercheCasse !== 'undefined' ? chercheCasse : null,
  repareCible: typeof repareCible !== 'undefined' ? repareCible : null,
  metierParle: typeof metierParle !== 'undefined' ? metierParle : null,
  phraseMetier: typeof phraseMetier !== 'undefined' ? phraseMetier : null,
  prendreBoulot: typeof prendreBoulot !== 'undefined' ? prendreBoulot : null,
  boulotAvance: typeof boulotAvance !== 'undefined' ? boulotAvance : null,
  BOULOTS: typeof BOULOTS !== 'undefined' ? BOULOTS : null,
  metierMarche: typeof metierMarche !== 'undefined' ? metierMarche : null,
  metierRoule: typeof metierRoule !== 'undefined' ? metierRoule : null,
  metierOuvert: typeof metierOuvert !== 'undefined' ? metierOuvert : null,
  creerTravailleur: typeof creerTravailleur !== 'undefined' ? creerTravailleur : null,
  poseBoites: typeof poseBoites !== 'undefined' ? poseBoites : null,
  filetTexture: typeof filetTexture !== 'undefined' ? filetTexture : null,
  boulotTick: typeof boulotTick !== 'undefined' ? boulotTick : null,
  metierProche: typeof metierProche !== 'undefined' ? metierProche : null,
  poseEchelle: typeof poseEchelle !== 'undefined' ? poseEchelle : null,
  metierScene: typeof metierScene !== 'undefined' ? metierScene : null,
  metierSync: typeof metierSync !== 'undefined' ? metierSync : null,
  metierDit: typeof metierDit !== 'undefined' ? metierDit : null,
  metiersEvenements: typeof metiersEvenements !== 'undefined' ? metiersEvenements : null,
  chantiersUsure: typeof chantiersUsure !== 'undefined' ? chantiersUsure : null,
  poubelleRoulante: typeof poubelleRoulante !== 'undefined' ? poubelleRoulante : null,
  terrainLibre: typeof terrainLibre !== 'undefined' ? terrainLibre : null,
  tenuePiece: typeof tenuePiece !== 'undefined' ? tenuePiece : null,
  buildZone: typeof buildZone === 'function' ? buildZone : null,
  immeubleZone: typeof immeubleZone === 'function' ? immeubleZone : null,
  devenirAmi: typeof devenirAmi === 'function' ? devenirAmi : null,
  startGym: typeof startGym === 'function' ? startGym : null,
  remiseTick: typeof remiseTick === 'function' ? remiseTick : null,
  groundCar: typeof groundCar === 'function' ? groundCar : null,
  terrainH: typeof terrainH === 'function' ? terrainH : null,
  agentsTick: typeof agentsTick === 'function' ? agentsTick : null,
  openPlainte: typeof openPlainte === 'function' ? openPlainte : null,
  deposerPlainte: typeof deposerPlainte === 'function' ? deposerPlainte : null,
  plainteTick: typeof plainteTick === 'function' ? plainteTick : null,
  emprisonneBot: typeof emprisonneBot === 'function' ? emprisonneBot : null,
  plainte: typeof plainte !== 'undefined' ? plainte : null,
  PLAINTE_MOTIFS: typeof PLAINTE_MOTIFS !== 'undefined' ? PLAINTE_MOTIFS : null,
  creerAgent: typeof creerAgent === 'function' ? creerAgent : null,
  resetBot: typeof resetBot === 'function' ? resetBot : null,
  repareChose: typeof repareChose === 'function' ? repareChose : null,
  spawnShot: typeof spawnShot === 'function' ? spawnShot : null,
  shotsTick: typeof shotsTick === 'function' ? shotsTick : null,
  settleVehicle: typeof settleVehicle === 'function' ? settleVehicle : null,
  vehicleSolid: typeof vehicleSolid === 'function' ? vehicleSolid : null,
  gymTick: typeof gymTick === 'function' ? gymTick : null,
  gym: typeof gym !== 'undefined' ? gym : null,
  NAV: typeof NAV !== 'undefined' ? NAV : null,
  policeTemoin: typeof policeTemoin === 'function' ? policeTemoin : null,
  solidifieDecor: typeof solidifieDecor === 'function' ? solidifieDecor : null,
  obstacleDecor: typeof obstacleDecor === 'function' ? obstacleDecor : null,
  boiteMaillage: typeof boiteMaillage === 'function' ? boiteMaillage : null,
  desincarcere: typeof desincarcere === 'function' ? desincarcere : null,
  penetration: typeof penetration === 'function' ? penetration : null,
  tourRoulette: typeof tourRoulette === 'function' ? tourRoulette : null,
  rouletteCine: typeof rouletteCine === 'function' ? rouletteCine : null,
  rouletteEtat: typeof rouletteEtat === 'function' ? rouletteEtat : null,
  ROULETTE_ORDRE: typeof ROULETTE_ORDRE !== 'undefined' ? ROULETTE_ORDRE : null,
  ROUGES: typeof ROUGES !== 'undefined' ? ROUGES : null,
  bankAlarmBot: typeof bankAlarmBot === 'function' ? bankAlarmBot : null,
  MISSIONS: typeof MISSIONS !== 'undefined' ? MISSIONS : null,
  openMissions: typeof openMissions === 'function' ? openMissions : null,
  commandeSociale: typeof commandeSociale === 'function' ? commandeSociale : null,
  interpreteOrdre: typeof interpreteOrdre === 'function' ? interpreteOrdre : null,
  motsDe: typeof motsDe === 'function' ? motsDe : null,
  defi: typeof defi !== 'undefined' ? defi : null,
  chien: typeof chien !== 'undefined' ? chien : null,
  amis: typeof amis !== 'undefined' ? amis : null,
  devenirAmi: typeof devenirAmi === 'function' ? devenirAmi : null,
  adopterChien: typeof adopterChien === 'function' ? adopterChien : null,
  lancerActivite: typeof lancerActivite === 'function' ? lancerActivite : null,
  gpsRoute: typeof gpsRoute !== 'undefined' ? gpsRoute : null,
  setBeacon: typeof setBeacon === 'function' ? setBeacon : null,
  missionTick: typeof missionTick === 'function' ? missionTick : null,
  mission: typeof mission !== 'undefined' ? mission : null,
  gpsRoute: typeof gpsRoute !== 'undefined' ? gpsRoute : null,
  beacon: typeof beacon !== 'undefined' ? beacon : null,
  activiteTick: typeof activiteTick === 'function' ? activiteTick : null,
  guardsTick: typeof guardsTick === 'function' ? guardsTick : null,
  enterCar: typeof enterCar === 'function' ? enterCar : null,
  exitCar: typeof exitCar === 'function' ? exitCar : null,
  cityTick: typeof cityTick === 'function' ? cityTick : null,
  cityCommon: typeof cityCommon === 'function' ? cityCommon : null,
  cityVie: typeof cityVie === 'function' ? cityVie : null,
  SON: typeof SON !== 'undefined' ? SON : null,
  SOLS: typeof SOLS !== 'undefined' ? SOLS : null,
  bubble: typeof bubble === 'function' ? bubble : null,
  sonFeu: typeof sonFeu === 'function' ? sonFeu : null,
  sonExplosion: typeof sonExplosion === 'function' ? sonExplosion : null,
  sonSirene: typeof sonSirene === 'function' ? sonSirene : null,
  sonRecul: typeof sonRecul === 'function' ? sonRecul : null,
  SIRENES: typeof SIRENES !== 'undefined' ? SIRENES : null,
  urgenceDe: typeof urgenceDe === 'function' ? urgenceDe : null,
  sonMarteau: typeof sonMarteau === 'function' ? sonMarteau : null,
  sonSoudure: typeof sonSoudure === 'function' ? sonSoudure : null,
  sonBalai: typeof sonBalai === 'function' ? sonBalai : null,
  sonJetEau: typeof sonJetEau === 'function' ? sonJetEau : null,
  sonRaclette: typeof sonRaclette === 'function' ? sonRaclette : null,
  sonVentre: typeof sonVentre === 'function' ? sonVentre : null,
  sonParade: typeof sonParade === 'function' ? sonParade : null,
  sonCouteau: typeof sonCouteau === 'function' ? sonCouteau : null,
  declencheIncendie: typeof declencheIncendie === 'function' ? declencheIncendie : null,
  incendiesTick: typeof incendiesTick === 'function' ? incendiesTick : null,
  QUARTIERS: typeof QUARTIERS !== 'undefined' ? QUARTIERS : null,
  ACCUEIL_DELAI: typeof ACCUEIL_DELAI !== 'undefined' ? ACCUEIL_DELAI : null,
  hornEn: typeof hornEn === 'function' ? hornEn : null,
  sonEffort: typeof sonEffort === 'function' ? sonEffort : null,
  sonAboiement: typeof sonAboiement === 'function' ? sonAboiement : null,
  sonEn: typeof sonEn === 'function' ? sonEn : null,
  sonPas: typeof sonPas === 'function' ? sonPas : null,
  sonCoup: typeof sonCoup === 'function' ? sonCoup : null,
  sonAie: typeof sonAie === 'function' ? sonAie : null,
  sonRate: typeof sonRate === 'function' ? sonRate : null,
  sonRotor: typeof sonRotor === 'function' ? sonRotor : null,
  sonBlabla: typeof sonBlabla === 'function' ? sonBlabla : null,
  sonBulle: typeof sonBulle === 'function' ? sonBulle : null,
  sonPortiere: typeof sonPortiere === 'function' ? sonPortiere : null,
  sonPneus: typeof sonPneus === 'function' ? sonPneus : null,
  sonTole: typeof sonTole === 'function' ? sonTole : null,
  sonCloche: typeof sonCloche === 'function' ? sonCloche : null,
  sonsVille: typeof sonsVille === 'function' ? sonsVille : null,
  solSous: typeof solSous === 'function' ? solSous : null,
  cadencePas: typeof cadencePas === 'function' ? cadencePas : null,
  hauteurVoix: typeof hauteurVoix === 'function' ? hauteurVoix : null,
  quartierSon: typeof quartierSon === 'function' ? quartierSon : null,
  ambiance: typeof ambiance !== 'undefined' ? ambiance : null,
  parle: typeof parle === 'function' ? parle : null,
  PARLE: typeof PARLE !== 'undefined' ? PARLE : null,
  accueil: typeof accueil === 'function' ? accueil : null,
  accueilTick: typeof accueilTick === 'function' ? accueilTick : null,
  ACCUEILS: typeof ACCUEILS !== 'undefined' ? ACCUEILS : null,
  SONV: typeof SONV !== 'undefined' ? SONV : null,
  MIX_DEF: typeof MIX_DEF !== 'undefined' ? MIX_DEF : null,
  construitMix: typeof construitMix === 'function' ? construitMix : null,
  VILLE: typeof VILLE === 'object' ? VILLE : null,
  VILLAS: typeof VILLAS !== 'undefined' ? VILLAS : null,
  botTirePourMoi: typeof botTirePourMoi === 'function' ? botTirePourMoi : null,
  botRangeArme: typeof botRangeArme === 'function' ? botRangeArme : null,
  gardeArmeTick: typeof gardeArmeTick === 'function' ? gardeArmeTick : null,
  cibleGarde: typeof cibleGarde === 'function' ? cibleGarde : null,
  vieTick: typeof vieTick === 'function' ? vieTick : null,
  vie: typeof vie !== 'undefined' ? vie : null,
  ACTIVITES: typeof ACTIVITES !== 'undefined' ? ACTIVITES : null,
  libereVoiture: typeof libereVoiture === 'function' ? libereVoiture : null,
  rejoindreGang: typeof rejoindreGang === 'function' ? rejoindreGang : null,
  estDuGang: typeof estDuGang === 'function' ? estDuGang : null,
  estAmi: typeof estAmi === 'function' ? estAmi : null,
  openOrdres: typeof openOrdres === 'function' ? openOrdres : null,
  openQui: typeof openQui === 'function' ? openQui : null,
  startGym: typeof startGym === 'function' ? startGym : null,
  gymTick: typeof gymTick === 'function' ? gymTick : null,
  finirSeance: typeof finirSeance === 'function' ? finirSeance : null,
  stats: typeof stats !== 'undefined' ? stats : null,
  sprintDuree: typeof sprintDuree === 'function' ? sprintDuree : null,
  perfDe: typeof perfDe === 'function' ? perfDe : null,
  gym: typeof gym !== 'undefined' ? gym : null,
  conduire: typeof conduire === 'function' ? conduire : null,
  navCell: typeof navCell === 'function' ? navCell : null,
  mannequin: typeof mannequin === 'function' ? mannequin : null,
  gardesDuCorps: typeof gardesDuCorps === 'function' ? gardesDuCorps : null,
  vieDe: typeof vieDe === 'function' ? vieDe : null,
  gangeurIsole: typeof gangeurIsole === 'function' ? gangeurIsole : null,
  prixVeto: typeof prixVeto === 'function' ? prixVeto : null,
  chienVeto: typeof chienVeto === 'function' ? chienVeto : null,
  day: typeof day !== 'undefined' ? day : null,
  casino: typeof casino !== 'undefined' ? casino : null,
  ouvreCasino: typeof ouvreCasino === 'function' ? ouvreCasino : null,
  jouerCasino: typeof jouerCasino === 'function' ? jouerCasino : null,
  majCasino: typeof majCasino === 'function' ? majCasino : null,
  casinoTick: typeof casinoTick === 'function' ? casinoTick : null,
  pokerRang: typeof pokerRang === 'function' ? pokerRang : null,
  gainMachine: typeof gainMachine === 'function' ? gainMachine : null,
  tireRouleaux: typeof tireRouleaux === 'function' ? tireRouleaux : null,
  POKER_GAINS: typeof POKER_GAINS !== 'undefined' ? POKER_GAINS : null,
  PARIS_ROULETTE: typeof PARIS_ROULETTE !== 'undefined' ? PARIS_ROULETTE : null,
  desserteDe: typeof desserteDe === 'function' ? desserteDe : null,
  lieuDe: typeof lieuDe === 'function' ? lieuDe : null,
  pointRouteProche: typeof pointRouteProche === 'function' ? pointRouteProche : null,
  RACE_PTS: typeof RACE_PTS !== 'undefined' ? RACE_PTS : null,
  RACE_LEN: typeof RACE_LEN !== 'undefined' ? RACE_LEN : 0,
  RACE_C: typeof RACE_C !== 'undefined' ? RACE_C : null,
  pathPos: typeof pathPos === 'function' ? pathPos : null,
  grilleDepart: typeof grilleDepart === 'function' ? grilleDepart : null,
  grilleRecul: typeof grilleRecul === 'function' ? grilleRecul : null,
  // ---- poste K (design et graphisme) ----
  DA: typeof DA !== 'undefined' ? DA : null,
  cielA: typeof cielA === 'function' ? cielA : null,
  cielDome: typeof cielDome !== 'undefined' ? cielDome : null,
  accorde: typeof accorde === 'function' ? accorde : null,
  AMBIANCES: typeof AMBIANCES !== 'undefined' ? AMBIANCES : null,
  lumieresVille: typeof lumieresVille === 'function' ? lumieresVille : null,
  SOLEIL_DIR: typeof SOLEIL_DIR !== 'undefined' ? SOLEIL_DIR : null,
  fill: typeof fill !== 'undefined' ? fill : null,
  post: typeof post !== 'undefined' ? post : null,
  QUALITES: typeof QUALITES !== 'undefined' ? QUALITES : null,
  applyQuality: typeof applyQuality === 'function' ? applyQuality : null,
  rendreImage: typeof rendreImage === 'function' ? rendreImage : null,
  renderer: typeof renderer !== 'undefined' ? renderer : null,
  degatsVehicule: typeof degatsVehicule === 'function' ? degatsVehicule : null,
  feuVehicule: typeof feuVehicule === 'function' ? feuVehicule : null,
  chocVehicule: typeof chocVehicule === 'function' ? chocVehicule : null,
  feuxVehiculesTick: typeof feuxVehiculesTick === 'function' ? feuxVehiculesTick : null,
  marqueMur: typeof marqueMur === 'function' ? marqueMur : null,
  casseBonhomme: typeof casseBonhomme === 'function' ? casseBonhomme : null,
  DEGATS: typeof DEGATS !== 'undefined' ? DEGATS : null,
  graviteChoc: typeof graviteChoc === 'function' ? graviteChoc : null,
  eclatsVerre: typeof eclatsVerre === 'function' ? eclatsVerre : null,
  eteintFeu: typeof eteintFeu === 'function' ? eteintFeu : null,
  crackedGlass: typeof crackedGlass !== 'undefined' ? crackedGlass : null,
  marques: typeof marques !== 'undefined' ? marques : null,
  MARQUES_MAX: typeof MARQUES_MAX !== 'undefined' ? MARQUES_MAX : 0,
  feuxVehicules: typeof feuxVehicules !== 'undefined' ? feuxVehicules : null,
  NEONS: typeof NEONS !== 'undefined' ? NEONS : null,
  ambianceSet: typeof ambianceSet === 'function' ? ambianceSet : null,
  varieTeinte: typeof varieTeinte === 'function' ? varieTeinte : null,
  postDefines: typeof postDefines === 'function' ? postDefines : null,
  debrisTick: typeof debrisTick === 'function' ? debrisTick : null,
  arracheRoue: typeof arracheRoue === 'function' ? arracheRoue : null,
  carcasseNoircie: typeof carcasseNoircie === 'function' ? carcasseNoircie : null,
  stars: typeof stars !== 'undefined' ? stars : null,
  sunSprite: typeof sunSprite !== 'undefined' ? sunSprite : null,
  grilleEcart: typeof grilleEcart === 'function' ? grilleEcart : null,
  surLaLigne: typeof surLaLigne === 'function' ? surLaLigne : null,
  GRILLE_N: typeof GRILLE_N !== 'undefined' ? GRILLE_N : 0,
  GRILLE_JOUEUR: typeof GRILLE_JOUEUR !== 'undefined' ? GRILLE_JOUEUR : 0,
  startCountdown: typeof startCountdown === 'function' ? startCountdown : null,
  raceTick: typeof raceTick === 'function' ? raceTick : null,
  padAction: typeof padAction === 'function' ? padAction : null,
  montreAide: typeof montreAide === 'function' ? montreAide : null,
  cacheAide: typeof cacheAide === 'function' ? cacheAide : null,
  aideTick: typeof aideTick === 'function' ? aideTick : null,
  gpsTick: typeof gpsTick === 'function' ? gpsTick : null,
  trottoirs: typeof trottoirs !== 'undefined' ? trottoirs : null,
  decorPublic: typeof decorPublic !== 'undefined' ? decorPublic : null,
  pointRouteLibre: typeof pointRouteLibre !== 'undefined' ? pointRouteLibre : null,
  pointRouteProche: typeof pointRouteProche !== 'undefined' ? pointRouteProche : null,
  PAVE: typeof PAVE !== 'undefined' ? PAVE : null,
  TROTTOIR: typeof TROTTOIR !== 'undefined' ? TROTTOIR : null,
  ROAD: typeof ROAD !== 'undefined' ? ROAD : null,
  finirPlan: typeof finirPlan !== 'undefined' ? finirPlan : null,
  GANG_DEFS: typeof GANG_DEFS !== 'undefined' ? GANG_DEFS : null,
  VILLAS: typeof VILLAS !== 'undefined' ? VILLAS : null,
  RACE_C: typeof RACE_C !== 'undefined' ? RACE_C : null,
  RALLY: typeof RALLY !== 'undefined' ? RALLY : null,
  buildNav: typeof buildNav !== 'undefined' ? buildNav : null,
  navFree: typeof navFree !== 'undefined' ? navFree : null,
  navCell: typeof navCell !== 'undefined' ? navCell : null,
  navGeo: typeof navGeo !== 'undefined' ? navGeo : null,
  tableauMaj: typeof tableauMaj === 'function' ? tableauMaj : null,
  school: typeof school !== 'undefined' ? school : null,
  answer: typeof answer === 'function' ? answer : null,
  sitBench: typeof sitBench === 'function' ? sitBench : null,
  glassVert: typeof glassVert !== 'undefined' ? glassVert : null,
  animateRig: typeof animateRig === 'function' ? animateRig : null,
  degatsTick: typeof degatsTick === 'function' ? degatsTick : null,
  avDegats: typeof avDegats === 'function' ? avDegats : null,
  degatsTexture: typeof degatsTexture === 'function' ? degatsTexture : null,
  niveauDegats: typeof niveauDegats === 'function' ? niveauDegats : null,
  applyStats: typeof applyStats === 'function' ? applyStats : null,
  setWeapon: typeof setWeapon === 'function' ? setWeapon : null,
  interieur: typeof interieur !== 'undefined' ? interieur : null,
  interieurTick: typeof interieurTick === 'function' ? interieurTick : null,
  interieurDe: typeof interieurDe === 'function' ? interieurDe : null,
  pokerCartes3D: typeof pokerCartes3D === 'function' ? pokerCartes3D : null,
  carteTexture: typeof carteTexture === 'function' ? carteTexture : null,
  carteNom: typeof carteNom === 'function' ? carteNom : null,
  tourRoulette: typeof tourRoulette === 'function' ? tourRoulette : null,
  mesureSon: typeof mesureSon === 'function' ? mesureSon : null,
  padStick: typeof padStick === 'function' ? padStick : null,
  post: typeof post !== 'undefined' ? post : null,
  rendreImage: typeof rendreImage === 'function' ? rendreImage : null,
  QUALITES: typeof QUALITES !== 'undefined' ? QUALITES : null,
  qualite: typeof qualite === 'function' ? qualite : null,
  plafondPixels: typeof plafondPixels === 'function' ? plafondPixels : null,
  navVers: typeof navVers === 'function' ? navVers : null,
  navCibles: typeof navCibles === 'function' ? navCibles : null,
  navOnglet: typeof navOnglet === 'function' ? navOnglet : null,
  navGlisse: typeof navGlisse === 'function' ? navGlisse : null,
  padMenu: typeof padMenu === 'function' ? padMenu : null,
  PAD_HZ: typeof PAD_HZ !== 'undefined' ? PAD_HZ : null,
  PAD_REPET: typeof PAD_REPET !== 'undefined' ? PAD_REPET : null,
  armeSuivante: typeof armeSuivante === 'function' ? armeSuivante : null,
  PAD_CROIX: typeof PAD_CROIX !== 'undefined' ? PAD_CROIX : null,
  PAD_LONG: typeof PAD_LONG !== 'undefined' ? PAD_LONG : null,
  manetteBT: typeof manetteBT !== 'undefined' ? manetteBT : null,
  manetteConnecter: typeof manetteConnecter === 'function' ? manetteConnecter : null,
  manetteBTSonde: typeof manetteBTSonde === 'function' ? manetteBTSonde : null,
  manetteBTEtat: typeof manetteBTEtat === 'function' ? manetteBTEtat : null,
  padSon: typeof padSon === 'function' ? padSon : null,
  sfx: typeof sfx !== 'undefined' ? sfx : null,
  music: typeof music !== 'undefined' ? music : null,
  siren: typeof siren !== 'undefined' ? siren : null,
  MIX: typeof MIX !== 'undefined' ? MIX : null,
  PALIERS: typeof PALIERS !== 'undefined' ? PALIERS : null,
  ombresQualite: typeof ombresQualite === 'function' ? ombresQualite : null,
  ombresTaille: typeof ombresTaille === 'function' ? ombresTaille : null,
  ombreBase: typeof ombreBase === 'function' ? ombreBase : null,
  ratioQualite: typeof ratioQualite === 'function' ? ratioQualite : null,
  sun: typeof sun !== 'undefined' ? sun : null,
  SM: typeof SM !== 'undefined' ? SM : null,
  OMBRE_CADRE: typeof OMBRE_CADRE !== 'undefined' ? OMBRE_CADRE : null,
  rendu: typeof rendu !== 'undefined' ? rendu : null,
  fluiditeTick: typeof fluiditeTick === 'function' ? fluiditeTick : null,
  appliqueRendu: typeof appliqueRendu === 'function' ? appliqueRendu : null,
  ratioRendu: typeof ratioRendu === 'function' ? ratioRendu : null,
  demarreTV: typeof demarreTV === 'function' ? demarreTV : null,
  QR: typeof QR !== 'undefined' ? QR : null,
  tvPasseLaMain: typeof tvPasseLaMain === 'function' ? tvPasseLaMain : null,
  manetteConnecte: typeof manetteConnecte === 'function' ? manetteConnecte : null,
  tvVeille: typeof tvVeille === 'function' ? tvVeille : null,
  RESEAU: typeof RESEAU !== 'undefined' ? RESEAU : null,
  CHAUD: typeof CHAUD !== 'undefined' ? CHAUD : null,
  pollGamepad: typeof pollGamepad === 'function' ? pollGamepad : null,
  padActive: typeof padActive === 'function' ? padActive : null,
  padStick: typeof padStick === 'function' ? padStick : null,
  padVibre: typeof padVibre === 'function' ? padVibre : null,
  PAD_MAP: typeof PAD_MAP !== 'undefined' ? PAD_MAP : null,
  PS_NOMS: typeof PS_NOMS !== 'undefined' ? PS_NOMS : null,
  manetteSalon: typeof manetteSalon !== 'undefined' ? manetteSalon : null,
  camSecousse: typeof camSecousse === 'function' ? camSecousse : null,
  pad: typeof pad !== 'undefined' ? pad : null,
  tiedis: typeof tiedis === 'function' ? tiedis : null,
  applyTheme: typeof applyTheme === 'function' ? applyTheme : null,
  hemi: typeof hemi !== 'undefined' ? hemi : null,
  scene: typeof scene !== 'undefined' ? scene : null,
  netteteTextures: typeof netteteTextures === 'function' ? netteteTextures : null,
  MAN_ESSAIS: typeof MAN_ESSAIS !== 'undefined' ? MAN_ESSAIS : 0,
  tel: typeof tel !== 'undefined' ? tel : null,
  tvHeberge: typeof tvHeberge === 'function' ? tvHeberge : null,
  manetteOuvre: typeof manetteOuvre === 'function' ? manetteOuvre : null,
  manetteFerme: typeof manetteFerme === 'function' ? manetteFerme : null,
  man: typeof man !== 'undefined' ? man : null,
  castLance: typeof castLance === 'function' ? castLance : null,
  MANETTE_HZ: typeof MANETTE_HZ !== 'undefined' ? MANETTE_HZ : 0,
  PLAFOND_TV: typeof PLAFOND_TV !== 'undefined' ? PLAFOND_TV : 0,
  netteteTextures: typeof netteteTextures === 'function' ? netteteTextures : null,
  startGame: typeof startGame === 'function' ? startGame : null,
  chooseWorld: typeof chooseWorld === 'function' ? chooseWorld : null,
  WORLDS: typeof WORLDS !== 'undefined' ? WORLDS : null,
  tv: typeof tv !== 'undefined' ? tv : null,
  closeUI: typeof closeUI === 'function' ? closeUI : null,
  ombresCadence: typeof ombresCadence === 'function' ? ombresCadence : null,
  ombresRendu: typeof ombresRendu === 'function' ? ombresRendu : null,
  plafondPixels: typeof plafondPixels === 'function' ? plafondPixels : null,
  ratioQualite: typeof ratioQualite === 'function' ? ratioQualite : null,
  applyQuality: typeof applyQuality === 'function' ? applyQuality : null,
  renderer: typeof renderer !== 'undefined' ? renderer : null,
  sun: typeof sun !== 'undefined' ? sun : null,
  modeTV: typeof modeTV === 'function' ? modeTV : null,
  ouvreSalonTV: typeof ouvreSalonTV === 'function' ? ouvreSalonTV : null,
  tvSalonMaj: typeof tvSalonMaj === 'function' ? tvSalonMaj : null,
  tvManettesMaj: typeof tvManettesMaj === 'function' ? tvManettesMaj : null,
  lienTV: typeof lienTV === 'function' ? lienTV : null,
  castPret: typeof castPret === 'function' ? castPret : null,
  castMaj: typeof castMaj === 'function' ? castMaj : null,
  copieLienTV: typeof copieLienTV === 'function' ? copieLienTV : null,
  cast: typeof cast !== 'undefined' ? cast : null,
  routeLien: typeof routeLien === 'function' ? routeLien : null,
  cam: typeof cam !== 'undefined' ? cam : null,
  surLeCourt: typeof surLeCourt === 'function' ? surLeCourt : null,
  makeBall: typeof makeBall === 'function' ? makeBall : null,
  removeBall: typeof removeBall === 'function' ? removeBall : null,
  capTennis: typeof capTennis === 'function' ? capTennis : null,
  TENNIS_FILET: typeof TENNIS_FILET !== 'undefined' ? TENNIS_FILET : -13,
  TENNIS_LARGE: typeof TENNIS_LARGE !== 'undefined' ? TENNIS_LARGE : null,
  sauveTout: typeof sauveTout === 'function' ? sauveTout : null,
  rechargeTout: typeof rechargeTout === 'function' ? rechargeTout : null,
  restaureGang: typeof restaureGang === 'function' ? restaureGang : null,
  restaureMaVoiture: typeof restaureMaVoiture === 'function' ? restaureMaVoiture : null,
  sauveMaVoiture: typeof sauveMaVoiture === 'function' ? sauveMaVoiture : null,
  maVoiture: typeof maVoiture === 'function' ? maVoiture : null,
  autoSauve: typeof autoSauve === 'function' ? autoSauve : null,
  saveGuerre: typeof saveGuerre === 'function' ? saveGuerre : null,
  loadGuerre: typeof loadGuerre === 'function' ? loadGuerre : null,
  guerre: typeof guerre !== 'undefined' ? guerre : null,
  gang: typeof gang !== 'undefined' ? gang : null,
  store: typeof store !== 'undefined' ? store : null,
  rejoindreGang: typeof rejoindreGang === 'function' ? rejoindreGang : null,
  TUNE_MOTEURS: typeof TUNE_MOTEURS !== 'undefined' ? TUNE_MOTEURS : null,
  KIT_VITESSE: typeof KIT_VITESSE !== 'undefined' ? KIT_VITESSE : null,
  MOTEUR_VOIX: typeof MOTEUR_VOIX !== 'undefined' ? MOTEUR_VOIX : null,
  bonusKits: typeof bonusKits === 'function' ? bonusKits : null,
  moteurDe: typeof moteurDe === 'function' ? moteurDe : null,
  engine: typeof engine !== 'undefined' ? engine : null,
  nitroGo: typeof nitroGo === 'function' ? nitroGo : null,
  nitroTick: typeof nitroTick === 'function' ? nitroTick : null,
  NITRO_DUREE: typeof NITRO_DUREE !== 'undefined' ? NITRO_DUREE : 0,
  NITRO_RECHARGE: typeof NITRO_RECHARGE !== 'undefined' ? NITRO_RECHARGE : 0,
  enterCar: typeof enterCar === 'function' ? enterCar : null,
  exitCar: typeof exitCar === 'function' ? exitCar : null,
  vehicleSolid: typeof vehicleSolid === 'function' ? vehicleSolid : null,
  MONDE: typeof MONDE !== 'undefined' ? MONDE : null,
  heliStep: typeof heliStep === 'function' ? heliStep : null,
  chuteImpact: typeof chuteImpact === 'function' ? chuteImpact : null,
  majPerfHud: typeof majPerfHud === 'function' ? majPerfHud : null,
  resumeMissions: typeof resumeMissions === 'function' ? resumeMissions : null,
  journalHtml: typeof journalHtml === 'function' ? journalHtml : null,
  puceEtat: typeof puceEtat === 'function' ? puceEtat : null,
  CHUTE_SEUIL: typeof CHUTE_SEUIL !== 'undefined' ? CHUTE_SEUIL : 0,
  enseigneTexture: typeof enseigneTexture === 'function' ? enseigneTexture : null,
  plaqueTexture: typeof plaqueTexture === 'function' ? plaqueTexture : null,
  RACE_GATES: typeof RACE_GATES !== 'undefined' ? RACE_GATES : null,
  get raceKarts() { return typeof raceKarts !== 'undefined' ? raceKarts : null; },   // réaffecté à chaque construction de ville
  race: typeof race !== 'undefined' ? race : null,
  DECOR: typeof DECOR !== 'undefined' ? DECOR : null,
  deliverDecor: typeof deliverDecor === 'function' ? deliverDecor : null,
  dansMonGarage: typeof dansMonGarage === 'function' ? dansMonGarage : null,
  sleepBed: typeof sleepBed === 'function' ? sleepBed : null,
  sauveTout: typeof sauveTout === 'function' ? sauveTout : null,
  openAtelier: typeof openAtelier === 'function' ? openAtelier : null,
  majAtelier: typeof majAtelier === 'function' ? majAtelier : null,
  tuneCible: typeof tuneCible === 'function' ? tuneCible : null,
  dayTick: typeof dayTick === 'function' ? dayTick : null,
  openEquipe: typeof openEquipe === 'function' ? openEquipe : null,
  equipeSel: typeof equipeSel !== 'undefined' ? equipeSel : null,
  chanceMission: typeof chanceMission === 'function' ? chanceMission : null,
  botMission: typeof botMission === 'function' ? botMission : null,
  CHIEN_PERF_MAX: typeof CHIEN_PERF_MAX !== 'undefined' ? CHIEN_PERF_MAX : null,
  updateBot: typeof updateBot === 'function' ? updateBot : null,
  recruteVaincu: typeof recruteVaincu === 'function' ? recruteVaincu : null,
  gangTick: typeof gangTick === 'function' ? gangTick : null,
  typeMission: typeof typeMission === 'function' ? typeMission : null,
  rangJoueur: typeof rangJoueur === 'function' ? rangJoueur : null,
  prixSoin: typeof prixSoin === 'function' ? prixSoin : null,
  botHopital: typeof botHopital === 'function' ? botHopital : null,
  soinTick: typeof soinTick === 'function' ? soinTick : null,
  ANIM: typeof ANIM !== 'undefined' ? ANIM : null,
  animPose: typeof animPose === 'function' ? animPose : null,
  animPres: typeof animPres === 'function' ? animPres : null,
  GESTES: typeof GESTES !== 'undefined' ? GESTES : null,
  gesteMetier: typeof gesteMetier === 'function' ? gesteMetier : null,
  animCombat: typeof animCombat === 'function' ? animCombat : null,
  coupDePoing: typeof coupDePoing === 'function' ? coupDePoing : null,
  gardePoings: typeof gardePoings === 'function' ? gardePoings : null,
  esquiveBaisse: typeof esquiveBaisse === 'function' ? esquiveBaisse : null,
  coupCouteau: typeof coupCouteau === 'function' ? coupCouteau : null,
  encaisseCoup: typeof encaisseCoup === 'function' ? encaisseCoup : null,
  feuAnime: typeof feuAnime === 'function' ? feuAnime : null,
  feuEteint: typeof feuEteint === 'function' ? feuEteint : null,
  feuDetruit: typeof feuDetruit === 'function' ? feuDetruit : null,
  feuVehicule: typeof feuVehicule === 'function' ? feuVehicule : null,
  feuxAnimTick: typeof feuxAnimTick === 'function' ? feuxAnimTick : null,
  depanneuseAnime: typeof depanneuseAnime === 'function' ? depanneuseAnime : null,
  ambulanceAnime: typeof ambulanceAnime === 'function' ? ambulanceAnime : null,
  animTransArme: typeof animTransArme === 'function' ? animTransArme : null,
  animTransApplique: typeof animTransApplique === 'function' ? animTransApplique : null,
  animFige: typeof animFige === 'function' ? animFige : null,
  brancardAnime: typeof brancardAnime === 'function' ? brancardAnime : null,
  animReception: typeof animReception === 'function' ? animReception : null,
  animMondeTick: typeof animMondeTick === 'function' ? animMondeTick : null,
  botGardeDuCorps: typeof botGardeDuCorps === 'function' ? botGardeDuCorps : null,
  botProtegeMembre: typeof botProtegeMembre === 'function' ? botProtegeMembre : null,
  botGardeVilla: typeof botGardeVilla === 'function' ? botGardeVilla : null,
  protectionTick: typeof protectionTick === 'function' ? protectionTick : null,
  ordreGang: typeof ordreGang === 'function' ? ordreGang : null,
  botStop: typeof botStop === 'function' ? botStop : null,
  nommerChien: typeof nommerChien === 'function' ? nommerChien : null,
  gardeTick: typeof gardeTick === 'function' ? gardeTick : null,
  gardeArmeTick: typeof gardeArmeTick === 'function' ? gardeArmeTick : null,
  coifApercu: typeof coifApercu === 'function' ? coifApercu : null,
  openStore: typeof openStore === 'function' ? openStore : null,
  buildAvatar: typeof buildAvatar === 'function' ? buildAvatar : null,
  applyLook: typeof applyLook === 'function' ? applyLook : null,
  openCoiffeur: typeof openCoiffeur === 'function' ? openCoiffeur : null,
  majCoiffeur: typeof majCoiffeur === 'function' ? majCoiffeur : null,
  validerCoiffure: typeof validerCoiffure === 'function' ? validerCoiffure : null,
  COIFFES: typeof COIFFES !== 'undefined' ? COIFFES : null,
  COIFFES_BLOCS: typeof COIFFES_BLOCS !== 'undefined' ? COIFFES_BLOCS : null,
  coif: typeof coif !== 'undefined' ? coif : null,
  PAL: typeof PAL !== 'undefined' ? PAL : null,
  SHOP: typeof SHOP !== 'undefined' ? SHOP : null,
  chienPoseAssis: typeof chienPoseAssis === 'function' ? chienPoseAssis : null,
  perfDe: typeof perfDe === 'function' ? perfDe : null,
  perfGagne: typeof perfGagne === 'function' ? perfGagne : null,
  perfPerd: typeof perfPerd === 'function' ? perfPerd : null,
  ACT_MISSIONS: typeof ACT_MISSIONS !== 'undefined' ? ACT_MISSIONS : null,
  carriere: typeof carriere !== 'undefined' ? carriere : null,
  GRADES: typeof GRADES !== 'undefined' ? GRADES : null,
  gradeCarriere: typeof gradeCarriere !== 'undefined' ? gradeCarriere : null,
  primeGrade: typeof primeGrade !== 'undefined' ? primeGrade : null,
  missionDebloquee: typeof missionDebloquee !== 'undefined' ? missionDebloquee : null,
  carriereReussie: typeof carriereReussie !== 'undefined' ? carriereReussie : null,
  sauveCarriere: typeof sauveCarriere !== 'undefined' ? sauveCarriere : null,
  primeSport: typeof primeSport !== 'undefined' ? primeSport : null,
  PALIERS_SPORT: typeof PALIERS_SPORT !== 'undefined' ? PALIERS_SPORT : null,
  varianteMission: typeof varianteMission !== 'undefined' ? varianteMission : null,
  arroseAutour: typeof arroseAutour !== 'undefined' ? arroseAutour : null,
  lieuRoutier: typeof lieuRoutier !== 'undefined' ? lieuRoutier : null,
  longueurRoute: typeof longueurRoute !== 'undefined' ? longueurRoute : null,
  vehiculeMission: typeof vehiculeMission !== 'undefined' ? vehiculeMission : null,
  fabriqueDepanneuse: typeof fabriqueDepanneuse !== 'undefined' ? fabriqueDepanneuse : null,
  suitRouteMission: typeof suitRouteMission !== 'undefined' ? suitRouteMission : null,
  traceRouteMission: typeof traceRouteMission !== 'undefined' ? traceRouteMission : null,
  sireneMission: typeof sireneMission !== 'undefined' ? sireneMission : null,
  arreteSuspect: typeof arreteSuspect !== 'undefined' ? arreteSuspect : null,
  SINISTRES: typeof SINISTRES !== 'undefined' ? SINISTRES : null,
  PANNES: typeof PANNES !== 'undefined' ? PANNES : null,
  FEU_PERDU: typeof FEU_PERDU !== 'undefined' ? FEU_PERDU : null,
  declencheIncendie: typeof declencheIncendie !== 'undefined' ? declencheIncendie : null,
  incendiesTick: typeof incendiesTick !== 'undefined' ? incendiesTick : null,
  actionneOutil: typeof actionneOutil !== 'undefined' ? actionneOutil : null,
  navEnPieton: typeof navEnPieton !== 'undefined' ? navEnPieton : null,
  emprisonneBot: typeof emprisonneBot !== 'undefined' ? emprisonneBot : null,
  vehicleDamage: typeof vehicleDamage !== 'undefined' ? vehicleDamage : null,
  updateMissionHud: typeof updateMissionHud !== 'undefined' ? updateMissionHud : null,
  openMissions: typeof openMissions !== 'undefined' ? openMissions : null,
  RETRAITS: typeof RETRAITS !== 'undefined' ? RETRAITS : null,
  ADRESSES: typeof ADRESSES !== 'undefined' ? ADRESSES : null,
  perfEtoiles: typeof perfEtoiles === 'function' ? perfEtoiles : null,
  policePerf: typeof policePerf === 'function' ? policePerf : null,
  majForceGang: typeof majForceGang === 'function' ? majForceGang : null,
  forceGangRival: typeof forceGangRival === 'function' ? forceGangRival : null,
  tuerMembre: typeof tuerMembre === 'function' ? tuerMembre : null,
  gangMissionTick: typeof gangMissionTick === 'function' ? gangMissionTick : null,
  missionGang: typeof missionGang === 'function' ? missionGang : null,
  GANG_MISSIONS: typeof GANG_MISSIONS !== 'undefined' ? GANG_MISSIONS : null,
  openGuerre: typeof openGuerre === 'function' ? openGuerre : null,
  majGuerre: typeof majGuerre === 'function' ? majGuerre : null,
  lieuDe: typeof lieuDe === 'function' ? lieuDe : null,
  agentsTick: typeof agentsTick === 'function' ? agentsTick : null,
  TATOO_TAILLES: typeof TATOO_TAILLES !== 'undefined' ? TATOO_TAILLES : null,
  construireGraphe: typeof construireGraphe === 'function' ? construireGraphe : null,
  botConduit: typeof botConduit === 'function' ? botConduit : null,
  traficPose: typeof traficPose === 'function' ? traficPose : null,
  carrefourLibre: typeof carrefourLibre === 'function' ? carrefourLibre : null,
  pietonDevant: typeof pietonDevant === 'function' ? pietonDevant : null,
  conduire: typeof conduire === 'function' ? conduire : null,
  itineraireVoies: typeof itineraireVoies === 'function' ? itineraireVoies : null,
  voieProche: typeof voieProche === 'function' ? voieProche : null,
  projVoie: typeof projVoie === 'function' ? projVoie : null,
  rattacheDessertes: typeof rattacheDessertes === 'function' ? rattacheDessertes : null,
  codeRoute: typeof codeRoute === 'function' ? codeRoute : null,
  croisementLibre: typeof croisementLibre === 'function' ? croisementLibre : null,
  pietonSurPassage: typeof pietonSurPassage === 'function' ? pietonSurPassage : null,
  traficRoule: typeof traficRoule === 'function' ? traficRoule : null,
  traficDestination: typeof traficDestination === 'function' ? traficDestination : null,
  traficPlace: typeof traficPlace === 'function' ? traficPlace : null,
  flotteMaj: typeof flotteMaj === 'function' ? flotteMaj : null,
  gapDevant: typeof gapDevant === 'function' ? gapDevant : null,
  carBlocked: typeof carBlocked === 'function' ? carBlocked : null,
  vehHalf: typeof vehHalf === 'function' ? vehHalf : null,
  roleVoie: typeof roleVoie === 'function' ? roleVoie : null,
  feuPhase: typeof feuPhase === 'function' ? feuPhase : null,
  FEU_CYCLE: typeof FEU_CYCLE !== 'undefined' ? FEU_CYCLE : null,
  FEU_VERT: typeof FEU_VERT !== 'undefined' ? FEU_VERT : null,
  PERTE_DELAI: typeof PERTE_DELAI === 'function' ? PERTE_DELAI : null,
  majWanted: typeof majWanted === 'function' ? majWanted : null,
  abriDuJoueur: typeof abriDuJoueur === 'function' ? abriDuJoueur : null,
  policeVoit: typeof policeVoit === 'function' ? policeVoit : null,
  cityStep: typeof cityStep === 'function' ? cityStep : null,
  TATOO_ZONES: typeof TATOO_ZONES !== 'undefined' ? TATOO_ZONES : null,
  openTatoo: typeof openTatoo === 'function' ? openTatoo : null,
  majTatoo: typeof majTatoo === 'function' ? majTatoo : null,
  applyMyLook: typeof applyMyLook === 'function' ? applyMyLook : null,
  myCfg: typeof myCfg !== 'undefined' ? myCfg : null,
  panierChien: typeof panierChien === 'function' ? panierChien : null,
  chienOrdre: typeof chienOrdre === 'function' ? chienOrdre : null,
  ORDRES_CHIEN: typeof ORDRES_CHIEN !== 'undefined' ? ORDRES_CHIEN : null,
  openOrdresChien: typeof openOrdresChien === 'function' ? openOrdresChien : null,
  chienTick: typeof chienTick === 'function' ? chienTick : null,
  repareAtelier: typeof repareAtelier === 'function' ? repareAtelier : null,
  prixRepare: typeof prixRepare === 'function' ? prixRepare : null,
  openAtelier: typeof openAtelier === 'function' ? openAtelier : null,
  vehicleDamage: typeof vehicleDamage === 'function' ? vehicleDamage : null,
  navEnPieton: typeof navEnPieton === 'function' ? navEnPieton : null,
  navGeo: typeof navGeo === 'function' ? navGeo : null,
  navSale: typeof navSale === 'function' ? navSale : null,
  navLisse: typeof navLisse === 'function' ? navLisse : null,
  navLibreLigne: typeof navLibreLigne === 'function' ? navLibreLigne : null,
  npcBlocked: typeof npcBlocked === 'function' ? npcBlocked : null,
  groundUnder: typeof groundUnder === 'function' ? groundUnder : null,
  lancerActivite: typeof lancerActivite === 'function' ? lancerActivite : null,
  activiteTick: typeof activiteTick === 'function' ? activiteTick : null,
  BOT_DEFS: typeof BOT_DEFS !== 'undefined' ? BOT_DEFS : null,
  combatTick: typeof combatTick === 'function' ? combatTick : null,
  botProtege: typeof botProtege === 'function' ? botProtege : null,
  botStop: typeof botStop === 'function' ? botStop : null,
  tuning: typeof tuning !== 'undefined' ? tuning : null,
  tuneApply: typeof tuneApply === 'function' ? tuneApply : null,
  tuneCible: typeof tuneCible === 'function' ? tuneCible : null,
  openAtelier: typeof openAtelier === 'function' ? openAtelier : null,
  validerAtelier: typeof validerAtelier === 'function' ? validerAtelier : null,
  majAtelier: typeof majAtelier === 'function' ? majAtelier : null,
  nitroGo: typeof nitroGo === 'function' ? nitroGo : null,
  nitroTick: typeof nitroTick === 'function' ? nitroTick : null,
  TUNE_KITS: typeof TUNE_KITS !== 'undefined' ? TUNE_KITS : null,
  TUNE_MOTEURS: typeof TUNE_MOTEURS !== 'undefined' ? TUNE_MOTEURS : null,
  TUNE_AMORTIS: typeof TUNE_AMORTIS !== 'undefined' ? TUNE_AMORTIS : null,
  TUNE_COULEURS: typeof TUNE_COULEURS !== 'undefined' ? TUNE_COULEURS : null,
  TUNE_FINITIONS: typeof TUNE_FINITIONS !== 'undefined' ? TUNE_FINITIONS : null,
  tenueUniforme: typeof tenueUniforme === 'function' ? tenueUniforme : null,
  stoveTick: typeof stoveTick === 'function' ? stoveTick : null,
  useStove: typeof useStove === 'function' ? useStove : null,
  sharkTick: typeof sharkTick === 'function' ? sharkTick : null,
  drawWeapon: typeof drawWeapon === 'function' ? drawWeapon : null,
  openJail, jail, jailFree, shotsTick, fire, aimTick, spawnShot,
  armee: typeof armee !== 'undefined' ? armee : null,
  armeeAlerte: typeof armeeAlerte === 'function' ? armeeAlerte : null,
  armeeTick: typeof armeeTick === 'function' ? armeeTick : null,
  armeeFin: typeof armeeFin === 'function' ? armeeFin : null,
  agentsTick: typeof agentsTick === 'function' ? agentsTick : null,
  creerAgent: typeof creerAgent === 'function' ? creerAgent : null,
  policeInvestit: typeof policeInvestit === 'function' ? policeInvestit : null,
  policeDebarque: typeof policeDebarque === 'function' ? policeDebarque : null,
  policeVoit: typeof policeVoit === 'function' ? policeVoit : null,
  abriDuJoueur: typeof abriDuJoueur === 'function' ? abriDuJoueur : null,
  agentTue: typeof agentTue === 'function' ? agentTue : null,
  arrestation: typeof arrestation === 'function' ? arrestation : null,
  separerVehicules: typeof separerVehicules === 'function' ? separerVehicules : null,
  vehHalf: typeof vehHalf === 'function' ? vehHalf : null,
  camLibres: typeof camLibres === 'function' ? camLibres : null,
  venirAMoi: typeof venirAMoi === 'function' ? venirAMoi : null,
  lieuDe: typeof lieuDe === 'function' ? lieuDe : null,
  bankAlarm, carBlocked, policeTick, driveStep, loopPos, makeCar, groundUnder, npcBlocked, npcMove, navPath, camera, safesTick, hurt, day, sun, hemi, scene,
  zomNuit: typeof zomNuit === 'function' ? zomNuit : null,
  surGlace: typeof surGlace === 'function' ? surGlace : null,
  neigeDecor: typeof neigeDecor === 'function' ? neigeDecor : null,
  MUNITIONS: typeof MUNITIONS !== 'undefined' ? MUNITIONS : null,
  muniActive: typeof muniActive === 'function' ? muniActive : null,
  feuAuSol: typeof feuAuSol === 'function' ? feuAuSol : null,
  feuxTick: typeof feuxTick === 'function' ? feuxTick : null,
  balleExplose: typeof balleExplose === 'function' ? balleExplose : null,
  libereVehiculesOublies: typeof libereVehiculesOublies === 'function' ? libereVehiculesOublies : null,
  botStop: typeof botStop === 'function' ? botStop : null,
  monterAvecBot: typeof monterAvecBot === 'function' ? monterAvecBot : null,
  applyDamageVisual, explodeVehicle, breakThing, equipWeapon, owned, saveOwned, me, breakables, worldGroup,
  AIDE_ORDRES: typeof AIDE_ORDRES !== 'undefined' ? AIDE_ORDRES : null,
  botSuis: typeof botSuis === 'function' ? botSuis : null,
  botTape: typeof botTape === 'function' ? botTape : null,
  bagarreTick: typeof bagarreTick === 'function' ? bagarreTick : null,
  combatTick, cinemaTick, FILMS, beacon, setBeacon, clearBeacon, VIDEOS: typeof VIDEOS !== 'undefined' ? VIDEOS : null,
  prendreVoile: typeof prendreVoile === 'function' ? prendreVoile : null,
  voilePose: typeof voilePose === 'function' ? voilePose : null,
  ouvreVoile: typeof ouvreVoile === 'function' ? ouvreVoile : null,
  rangeVoile: typeof rangeVoile === 'function' ? rangeVoile : null,
  voileTick: typeof voileTick === 'function' ? voileTick : null,
  liftTick: typeof liftTick === 'function' ? liftTick : null,
  toitAccessible: typeof toitAccessible === 'function' ? toitAccessible : null,
  meteo: typeof meteo !== 'undefined' ? meteo : null,
  meteoTick: typeof meteoTick === 'function' ? meteoTick : null,
  meteoSet: typeof meteoSet === 'function' ? meteoSet : null,
  stealCar: typeof stealCar === 'function' ? stealCar : null,
  cinemaTick: typeof cinemaTick === 'function' ? cinemaTick : null,
  FILMS: typeof FILMS !== 'undefined' ? FILMS : null,
  filmSuivant: typeof filmSuivant === 'function' ? filmSuivant : null,
  ctrlText: typeof ctrlText === 'function' ? ctrlText : null,
  castSolids: typeof castSolids === 'function' ? castSolids : null,
  rayBox: typeof rayBox === 'function' ? rayBox : null,
  rayPerso: typeof rayPerso === 'function' ? rayPerso : null,
  get aimPoint() { return aimPoint; },
  get aimDir() { return typeof aimDir !== 'undefined' ? aimDir : null; },
  muzzle() { const w = me.weapons && me.weapons[P.weapon]; const m = w && w.userData && w.userData.muzzle;
    return m ? m.getWorldPosition(new THREE.Vector3()) : null; },
  bodyClass() { return document.body.className; },
  tactile(on) { document.body.classList.toggle('touch', !!on); },
  hud() { return { jump: document.getElementById('jumpBtn').textContent, car: document.getElementById('carBtn').textContent,
    punch: document.getElementById('punchBtn').textContent, emote: document.getElementById('emoteBtn').textContent }; },
  // Ce qu'on tient est passe du groupe du bras au noeud main, au centre du poing rond
  // on compte donc les deux, sinon le test « rien ne reste colle a la main » ne voyait plus rien.
  arm() { return me.rig.armR.children.length + (me.rig.armR.main ? me.rig.armR.main.children.length : 0); },
};
`;

function serve(htmlFile) {
  const html = fs.readFileSync(htmlFile, 'utf8')
    .replace(/<script src="https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/three\.js\/r128\/three\.min\.js"><\/script>/, '<script src="/three.min.js"></script>')
    .replace(/<script src="https:\/\/cdnjs\.cloudflare\.com\/ajax\/libs\/peerjs[^<]*<\/script>/, '')
    .replace(/<link href="https:\/\/fonts\.googleapis\.com[^>]*>/, '')
    .replace(/\nloop\(\);/, '\nloop();\n' + HOOK);
  const three = fs.readFileSync(path.join(__dirname, 'vendor', 'three.min.js'));
  const srv = http.createServer((req, res) => {
    if (req.url.startsWith('/three.min.js')) { res.writeHead(200, { 'Content-Type': 'application/javascript' }); res.end(three); }
    else { res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' }); res.end(html); }
  });
  return new Promise(r => srv.listen(0, '127.0.0.1', () => r({ srv, port: srv.address().port })));
}

(async () => {
  const file = process.argv[2] || path.join(ROOT, 'index.html');
  const { srv, port } = await serve(file);
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
    args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox', '--disable-dev-shm-usage'] });
  const page = await browser.newPage({ viewport: { width: 1280, height: 720 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
  await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'load' });
  await page.waitForFunction(() => window.__SHOT && window.__SHOT.ready, null, { timeout: 60000 })
    .catch(() => { throw new Error('le crochet __SHOT n\'est jamais devenu prêt — le jeu n\'a pas démarré. Erreurs: ' + errors.join(' | ')); });

  for (const v of VIEWS) {
    await page.evaluate(vv => window.__SHOT.go(vv), v);
    await page.waitForTimeout(v.wait || 700);
    await page.screenshot({ path: path.join(OUT, v.name + '.png') });
  }
  const stats = await page.evaluate(() => window.__SHOT.stats());
  console.log('rendu :', JSON.stringify(stats));
  if (errors.length) { console.log('\nERREURS CONSOLE (' + errors.length + ') :'); errors.slice(0, 15).forEach(e => console.log('  ' + e.slice(0, 220))); }
  else console.log('aucune erreur console.');
  await browser.close(); srv.close();
  console.log('captures dans', OUT);
})().catch(e => { console.error(e.message || e); process.exit(1); });
