(function(M){'use strict';
const inside=(x,y)=>x>=0&&x<8&&y>=0&&y<8;
M.Board=class{
 constructor(kind){this.kind=kind;this.turn=1;this.board=Array(64).fill(0);this.selected=-1;this.forced=-1;this.result=null;this.moves=0;if(kind==='checkers'){for(let y=0;y<8;y++)for(let x=0;x<8;x++)if((x+y)%2&&y!==3&&y!==4)this.board[y*8+x]=y<3?-1:1;}else{const row=[4,2,3,5,6,3,2,4];for(let i=0;i<8;i++){this.board[i]=-row[i];this.board[8+i]=-1;this.board[48+i]=1;this.board[56+i]=row[i];}}}
 raw(from,captureOnly=false){const b=this.board,p=b[from],side=Math.sign(p),type=Math.abs(p),x=from%8,y=from>>3,out=[];if(!p)return out;const add=(xx,yy)=>{if(!inside(xx,yy))return false;const to=yy*8+xx,v=b[to];if(Math.sign(v)!==side)out.push({from,to});return !v;};
 if(this.kind==='checkers'){for(const dx of [-1,1])for(const dy of type===2?[-1,1]:[-side]){const xx=x+dx,yy=y+dy;if(!inside(xx,yy))continue;const to=yy*8+xx;if(!b[to]&&!captureOnly)out.push({from,to});else if(Math.sign(b[to])===-side&&inside(x+2*dx,y+2*dy)&&!b[(y+2*dy)*8+x+2*dx])out.push({from,to:(y+2*dy)*8+x+2*dx,take:to});}return out;}
 if(type===1){if(inside(x,y-side)&&!b[(y-side)*8+x]&&!captureOnly){out.push({from,to:(y-side)*8+x});if(y===(side===1?6:1)&&!b[(y-side*2)*8+x])out.push({from,to:(y-side*2)*8+x});}for(const dx of [-1,1])if(inside(x+dx,y-side)&&Math.sign(b[(y-side)*8+x+dx])===-side)out.push({from,to:(y-side)*8+x+dx});}
 if(type===2)for(const[dx,dy]of [[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]])add(x+dx,y+dy);
 if(type>=3){const dirs=type===3?[[1,1],[-1,1],[1,-1],[-1,-1]]:type===4?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[-1,1],[1,-1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const[dx,dy]of dirs)for(let n=1;n<=(type===6?1:7);n++)if(!add(x+dx*n,y+dy*n))break;}
 return out;
 }
 attacked(square,side){for(let i=0;i<64;i++)if(Math.sign(this.board[i])===side){if(Math.abs(this.board[i])===1){if((square>>3)===(i>>3)-side&&Math.abs(square%8-i%8)===1)return true;}else if(this.raw(i).some(m=>m.to===square))return true;}return false;}
 legal(){let moves=[];for(let i=0;i<64;i++)if(Math.sign(this.board[i])===this.turn&&(this.forced<0||this.forced===i))moves.push(...this.raw(i));if(this.kind==='checkers'){const captures=moves.filter(m=>m.take!==undefined);return captures.length?captures:moves;}return moves.filter(m=>{if(Math.abs(this.board[m.to])===6)return false;const old=this.board.slice();this.board[m.to]=this.board[m.from];this.board[m.from]=0;const king=this.board.indexOf(6*this.turn),valid=king>=0&&!this.attacked(king,-this.turn);this.board=old;return valid;});}
 play(from,to){if(this.result)return false;const move=this.legal().find(m=>m.from===from&&m.to===to);if(!move)return false;const piece=this.board[from];this.board[to]=piece;this.board[from]=0;if(move.take!==undefined)this.board[move.take]=0;const row=to>>3,promote=Math.abs(piece)===1&&(row===0&&piece>0||row===7&&piece<0);if(promote)this.board[to]=this.kind==='checkers'?2*this.turn:5*this.turn;
 this.moves++;if(this.kind==='checkers'&&move.take!==undefined&&!promote&&this.raw(to,true).length){this.forced=to;return true;}this.forced=-1;this.turn*=-1;const possible=this.legal();if(!possible.length){if(this.kind==='chess'&&!this.attacked(this.board.indexOf(6*this.turn),-this.turn))this.result='draw';else this.result=this.turn===-1?'win':'lose';}if(this.moves>=160)this.result='draw';return true;}
 bot(){while(this.turn===-1&&!this.result){const moves=this.legal();if(!moves.length)break;moves.sort((a,b)=>((Math.abs(this.board[b.to])||0)+(b.take!==undefined?3:0)+Math.random()*.6)-((Math.abs(this.board[a.to])||0)+(a.take!==undefined?3:0)+Math.random()*.6));this.play(moves[0].from,moves[0].to);}}
};
M.pokerRank=cards=>{const counts={};cards.forEach(c=>counts[c%13]=(counts[c%13]||0)+1);const values=Object.values(counts).sort((a,b)=>b-a),ranks=Object.keys(counts).map(Number).sort((a,b)=>a-b),flush=cards.every(c=>Math.floor(c/13)===Math.floor(cards[0]/13)),straight=ranks.length===5&&(ranks[4]-ranks[0]===4||ranks.join(',')==='0,9,10,11,12');return flush&&straight?{name:'Quinte flush',mult:50}:values[0]===4?{name:'Carré',mult:20}:values[0]===3&&values[1]===2?{name:'Full',mult:8}:flush?{name:'Couleur',mult:6}:straight?{name:'Suite',mult:4}:values[0]===3?{name:'Brelan',mult:3}:values[0]===2&&values[1]===2?{name:'Deux paires',mult:2}:values[0]===2?{name:'Une paire',mult:1}:{name:'Carte haute',mult:0};};
})(Marlon);
