(function(M){'use strict';const G=M.Game.prototype,P=M.UI.prototype,$=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Math.floor(n).toLocaleString('fr-FR')+' pièces';
G.openPlace=function(id,target){if(this.ui)this.ui.casinoToken=(this.ui.casinoToken||0)+1;this.place=id;this.placeTarget=target;this.setMode('city');};
const mode=P.renderMode;P.renderMode=function(m){mode.call(this,m);if(m==='city'){this.renderCity();$('panelBody').querySelector('button')?.focus();}};
P.renderCity=function(){const g=this.g,s=g.city,id=g.place,body=$('panelBody');$('panelEyebrow').textContent='MARLON / SUNSHINE CITY';const b=g.world.services.find(b=>b.id===id);$('panelTitle').textContent=b?.name||{directory:'Explore Sunshine City',recruit:'Rencontrer un habitant',pet:'Votre compagnon',gang:'Votre équipe',school:'La classe des Palmiers'}[id]||'Sunshine City';body.innerHTML='';const balance=document.createElement('div');balance.className='city-balance';balance.textContent='PORTEFEUILLE  '+money(g.cash)+'  ·  BANQUE  '+money(s.bank);body.appendChild(balance);
 const text=(str,cls='')=>{const p=document.createElement('p');p.className=cls;p.textContent=str;body.appendChild(p);return p;};const grid=document.createElement('div');grid.className='city-cards';body.appendChild(grid);
 const button=(label,fn,parent=grid)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{fn();if(g.mode==='city'&&!['school','casino','pet','gang'].includes(id))g.ui.renderCity();};parent.appendChild(b);return b;};const card=(title,detail,price,fn,art)=>{const c=document.createElement('div');c.className='city-card';if(art)c.innerHTML=art;const h=document.createElement('h3');h.textContent=title;c.appendChild(h);const p=document.createElement('p');p.textContent=detail;c.appendChild(p);button(price,fn,c);grid.appendChild(c);return c;};
 if(id==='directory'){text('Choisissez une destination. Le trajet jaune vous guide dans la ville ; approchez du comptoir et appuyez sur E / Triangle.');for(const b of g.world.services)card(b.name,Math.round(Math.hypot(g.player.x-b.entry.x,g.player.z-b.entry.z))+' m','GUIDER',()=>{g.cityTarget=b.entry;g.setMode('play');g.toast('Destination : '+b.name);});button('MON GANG',()=>g.openPlace('gang'));return;}
 if(id==='dealer'){text('14 modèles à acheter. Les voitures sont livrées devant le showroom, avec une couleur au choix.');let selected=M.PALETTE[0];const swatches=document.createElement('div');swatches.className='swatches';body.insertBefore(swatches,grid);for(const color of M.PALETTE){const sw=button('●',()=>{selected=color;swatches.querySelectorAll('button').forEach(b=>b.classList.remove('active'));sw.classList.add('active');},swatches);sw.style.color=color;sw.setAttribute('aria-label','Peinture '+color);sw.onclick=()=>{selected=color;swatches.querySelectorAll('button').forEach(b=>b.classList.remove('active'));sw.classList.add('active');};}
 for(const v of M.CARS.filter(v=>v.price>0)){const art=`<svg viewBox="0 0 240 100" class="car-art" aria-hidden="true"><ellipse cx="120" cy="85" rx="100" ry="8" fill="#16383c22"/><path d="M20 67 Q15 53 34 49 L61 46 L84 22 Q93 15 115 15 L156 19 L184 46 L211 51 Q223 56 217 75 L22 75Z" fill="${M.PALETTE[M.CARS.indexOf(v)%8]}"/><path d="M71 45 L90 25 L114 24 L114 45Z M121 24 L151 27 L173 45 L121 45Z" fill="#d9f9fa"/><circle cx="64" cy="75" r="17" fill="#294253"/><circle cx="180" cy="75" r="17" fill="#294253"/><circle cx="64" cy="75" r="9" fill="#e7e9da"/><circle cx="180" cy="75" r="9" fill="#e7e9da"/></svg>`;card(v.name,v.hp+' ch · '+Math.round(v.maxSpeed*3.6)+' km/h · accélération '+v.accel,money(v.price),()=>g.buyCar(v.id,selected),art);}return;}
 if(id==='garage'){const c=g.nearCar();text(c?'Véhicule : '+c.name+' · état '+Math.round(c.health)+' %':'Achetez d’abord votre voiture au concessionnaire.');button('RÉPARER · 90 pièces',()=>{if(!c||Math.hypot(c.x-g.player.x,c.z-g.player.z)>38)return g.toast('Amenez la voiture près du garage.');g.spend(90,()=>g.startTask('repair',5,{car:c}));});for(const u of M.UPGRADES)card(u.name,u.id==='engine'?'+18 % accélération et vitesse':u.id==='turbo'?'+22 % accélération et vitesse':'Modification visible sur le véhicule',c?.upgrades?.includes(u.id)?'INSTALLÉ':money(u.price),()=>g.upgradeCar(u.id));for(const color of M.PALETTE)card('Peinture',color,'120 pièces',()=>{if(!c||Math.hypot(c.x-g.player.x,c.z-g.player.z)>38)return;g.spend(120,()=>{c.cityState.color=color;g.rebuildCar(c,c.cityState);g.animateCar(c,0);});},`<div class="paint-sample" style="background:${color}"></div>`);return;}
 if(id==='fashion'){for(const item of M.OUTFITS)card(item.name,{top:'Haut',bottom:'Bas',hat:'Accessoire de tête',shoes:'Chaussures',watch:'Poignet',jewelry:'Bijou'}[item.slot],s.closet.includes(item.id)?'PORTER':money(item.price),()=>g.buyOutfit(item.id));return;}
 if(id==='hair'){for(const h of M.HAIR)card(h.name,'Coupe visible sur le personnage',money(h.price),()=>g.spend(h.price,()=>{s.hair=h.id;M.dress(g.actor,s);}));return;}
 if(id==='tattoo'){for(const[id,name]of [['wave','Vague'],['palm','Palmier'],['star','Étoile']])card(name,'Motif sur l’épaule','60 pièces',()=>g.spend(60,()=>{s.tattoo=id;M.dress(g.actor,s);}));return;}
 if(id==='arms'){for(const w of M.WEAPONS)card(w.name,w.damage+' dégâts · '+(1/w.cooldown).toFixed(1)+' tirs/s',s.weapons.includes(w.id)?'ÉQUIPER':money(w.price),()=>{const equip=()=>{s.weapon=w.id;if(!s.weapons.includes(w.id))s.weapons.push(w.id);g.actor.gun.scale.set(w.id==='pistol'?1:1.25,1,w.id==='rifle'?2:w.id==='shotgun'?1.7:1);};if(s.weapons.includes(w.id)){equip();g.save();}else g.spend(w.price,equip);});button('120 MUNITIONS · 80 pièces',()=>g.spend(80,()=>g.player.ammo=Math.min(999,g.player.ammo+120)));return;}
 if(id==='pizza'){card('Pizza tropicale','Récupère 25 points de santé','18 pièces',()=>g.spend(18,()=>{g.player.health=Math.min(100,g.player.health+25);g.toast('Bon appétit !');}));return;}
 if(id==='bank'){text('Compte bancaire : argent protégé des amendes. Les braquages sont des événements fictifs du jeu. Chaque coffre demande 6 secondes ; 3 coffres maximum et alerte 3 étoiles.');for(const n of [100,500,1000]){button('DÉPOSER '+money(n),()=>g.spend(n,()=>s.bank+=n));button('RETIRER '+money(n),()=>{if(s.bank<n)return g.toast('Solde bancaire insuffisant.');s.bank-=n;g.cash+=n;g.save();});}button('BRAQUER LES COFFRES · 18 secondes',()=>{g.crime(3,'Alarme de la banque');g.startTask('rob',18,{opened:0});});return;}
 if(id==='police'){text('Le guichet enregistre les plaintes contre les gangs simulés. Cette version est solo : aucun autre joueur réel n’est présent.');for(const gang of ['Onyx','Les Cendres'])button('PORTER PLAINTE : '+gang,()=>{if(s.complaints.includes(gang))return g.toast('Votre plainte est déjà enregistrée.');s.complaints.push(gang);g.rep+=5;g.save();g.toast('Plainte enregistrée. Réputation +5.');});button('RÉGLER MES AMENDES · '+money(80*s.wanted),()=>g.spend(80*s.wanted,()=>{s.wanted=0;s.heat=0;}));text(s.complaints.length+' plainte(s) enregistrée(s).');return;}
 if(id==='hospital'){card('Chambre et soins','Santé entièrement restaurée après les soins','75 pièces',()=>g.spend(75,()=>g.startTask('heal',5)));return;}
 if(id==='gym'||id==='range'){const stat=id==='gym'?'strength':'accuracy';text((id==='gym'?'Force':'Précision')+' : '+Math.floor(s[stat])+' / 100');card(id==='gym'?'Séance de musculation':'Séance de tir','Entraînement animé · +5 points · 12 secondes','35 pièces',()=>{if(s[stat]>=100)return g.toast('Performance maximale.');g.spend(35,()=>g.startTask('train',12,{stat}));});return;}
 if(id==='school'){text(M.QUESTIONS.length+' questions disponibles. Une bonne réponse inédite rapporte 5 pièces.');for(const[domain,label]of [['maths','Mathématiques'],['logique','Logique'],['geographie','Géographie'],['biologie','Biologie']]){const btn=button(label,()=>{});btn.onclick=()=>this.schoolQuestion(domain);}return;}
 if(id==='adopt'){for(const[kind,name]of [['dog','Chien'],['cat','Chat']])card(name,'Adoption, nom et ordres : suivre, assis, couché, patte','80 pièces',()=>{if(s.pets.length>=3)return g.toast('Trois compagnons maximum.');const name=prompt('Quel nom lui donner ?',kind==='dog'?'Rio':'Moka');if(name===null)return;g.spend(80,()=>{s.pets.push({kind,name:name.replace(/[<>]/g,'').slice(0,20)||'Rio',command:'follow'});g.syncPets();});});for(const pet of g.pets)button(pet.state.name,()=>g.openPlace('pet',pet));return;}
 if(id==='pet'){const pet=g.placeTarget;text(pet.state.name+' · '+pet.state.kind);for(const[cmd,label]of [['follow','Suis-moi'],['sit','Assis'],['down','Couché'],['paw','Donne la patte']]){const b=button(label,()=>{});b.onclick=()=>{pet.state.command=cmd;g.save();g.setMode('play');g.toast(pet.state.name+' : '+label);};}button('CHANGER LE NOM',()=>{const name=prompt('Nouveau nom',pet.state.name);if(name){pet.state.name=name.replace(/[<>]/g,'').slice(0,20);g.save();g.openPlace('pet',pet);}});return;}
 if(id==='recruit'){text('Cet habitant peut rejoindre '+s.gang+'. Votre équipe compte '+g.allies.length+' / 3 membres.');button('RECRUTER · 200 pièces',()=>{if(g.allies.length>=3)return g.toast('Équipe complète.');g.spend(200,()=>{g.placeTarget.recruited=true;g.addAlly();g.setMode('play');});});return;}
 if(id==='gang'){text(s.gang+' · '+g.allies.length+' membres');button('NOMMER MON GANG',()=>{const n=prompt('Nom du gang',s.gang);if(n){s.gang=n.replace(/[<>]/g,'').slice(0,30);g.save();g.openPlace('gang');}});for(let i=0;i<g.allies.length;i++){const c=card('Membre '+(i+1),Math.round(g.allies[i].health)+' PV','SUIS-MOI',()=>g.giveOrder(i,'follow'));for(const[k,label]of [['guard','Garde du corps'],['car','Cherche une voiture'],['rob','Braque une boutique'],['weapon','Cherche des munitions'],['hospital','Va à l’hôpital'],['gym','Va à la musculation'],['range','Va au stand de tir']])button(label,()=>{g.giveOrder(i,k);g.setMode('play');},c);}return;}
 if(id==='missions'){text('Une mission urbaine à la fois. Le trajet jaune relie chaque étape.');for(const[type,label,reward]of [['parcel','Livraison de colis',160],['race','Tour de Sunshine en voiture',350],['heli','Vol panoramique',600],['dog','Promenade au parc',90]])card(label,'Récompense : '+money(reward),'ACCEPTER',()=>{if(s.job)return g.toast('Terminez ou abandonnez la mission actuelle.');s.job={type,index:0,remaining:type==='heli'?600:420};g.save();g.setMode('play');});if(s.job)button('ABANDONNER LA MISSION',()=>{s.job=null;g.cityTarget=null;g.save();});return;}
 if(id==='fair'){card('Grande roue','Tour de 45 secondes, cabine accessible','15 pièces',()=>g.spend(15,()=>g.startTask('wheel',45)));return;}
 if(id==='heli'){text('L’hélicoptère vous attend sur le toit. Prenez l’ascenseur ou les escaliers, puis approchez-vous et appuyez sur E / Triangle.');return;}
 if(id==='villa'){text('Villa ouverte : salon, étage, toit, piscine, trampoline et portail automatique.');button('MON GANG',()=>g.openPlace('gang'));return;}
 if(id==='park'){text('Jardin tropical, bancs, fleurs et promenade des compagnons.');button('COMMANDES DES COMPAGNONS',()=>g.openPlace('adopt'));return;}
 if(id==='casino'){text('Jeux en monnaie fictive, sans achat d’argent réel. Mise : 20 pièces. Quitter une partie engagée perd la mise.');for(const[k,name]of [['roulette','Roulette'],['slots','Machine à sous'],['poker','Poker fermé'],['checkers','Dames'],['chess','Échecs']]){const b=button(name,()=>{});b.onclick=()=>this.casinoStart(k);}return;}
};
P.speak=function(str){if(!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(str);u.lang='fr-FR';u.rate=.92;speechSynthesis.speak(u);}catch{}};
P.schoolQuestion=function(domain){const g=this.g,q=M.nextQuestion(g.city,domain);if(!q){$('panelBody').innerHTML='<p>Toutes les questions de ce domaine sont réussies !</p>';return;}this.currentQuestion=q;g.world.writeBoard(q.q,q.choices.join('  /  '));const body=$('panelBody');body.innerHTML='<div class="chalkboard"><span>ÉCOLE DES PALMIERS</span><h2>'+escape(q.q)+'</h2><p id="schoolFeedback">Choisissez une réponse.</p></div><div class="city-cards" id="answers"></div><div class="school-footer"></div>';for(const answer of q.choices){const b=document.createElement('button');b.textContent=answer;b.onclick=()=>{document.querySelectorAll('#answers button').forEach(b=>b.disabled=true);const correct=answer===q.answer;if(correct&&!g.city.answered.includes(q.id)){g.city.answered.push(q.id);g.cash+=5;}const message=correct?'Bonne réponse ! +5 pièces.':'La bonne réponse est : '+q.answer;g.world.writeBoard(q.q,'Réponse : '+q.answer);$('schoolFeedback').textContent=message;this.speak(message);g.save();};$('answers').appendChild(b);}const footer=body.querySelector('.school-footer');for(const[label,fn]of [['ÉCOUTER',()=>this.speak(q.q+' '+q.choices.join('. '))],['QUESTION SUIVANTE',()=>this.schoolQuestion(domain)],['CHANGER DE MATIÈRE',()=>g.openPlace('school')]]){const b=document.createElement('button');b.textContent=label;b.onclick=fn;footer.appendChild(b);}this.speak(q.q+' '+q.choices.join('. '));g.save();};
P.casinoStart=function(kind){const token=this.casinoToken=(this.casinoToken||0)+1,g=this.g;if(!g.spend(20,()=>{}))return;const body=$('panelBody');body.innerHTML='<div class="casino-stage"><canvas id="casinoCanvas" width="640" height="500"></canvas><p id="casinoResult">Mise engagée : 20 pièces</p></div><div class="casino-actions"></div>';const canvas=$('casinoCanvas'),ctx=canvas.getContext('2d'),actions=body.querySelector('.casino-actions');let paid=false;const settle=(amount,msg)=>{if(paid||token!==this.casinoToken||g.mode!=='city'||g.place!=='casino')return;paid=true;g.cash+=amount;g.save();$('casinoResult').textContent=msg+' · '+(amount?'Retour : '+money(amount):'Mise perdue.');};const btn=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;actions.appendChild(b);return b;};const bg=()=>{ctx.fillStyle='#145e61';ctx.fillRect(0,0,640,500);};
 if(kind==='roulette'){let angle=0,spinning=false,start=0,result=0,bet='red';const draw=()=>{bg();for(let i=0;i<37;i++){const a=angle+i*Math.PI*2/37;ctx.beginPath();ctx.moveTo(320,250);ctx.arc(320,250,210,a,a+Math.PI*2/37);ctx.closePath();ctx.fillStyle=i===0?'#54b994':i%2?'#e86685':'#27354d';ctx.fill();ctx.save();ctx.translate(320,250);ctx.rotate(a+Math.PI/37);ctx.fillStyle='#fff6dc';ctx.font='16px sans-serif';ctx.fillText(i,180,5);ctx.restore();}ctx.fillStyle='#ffe083';ctx.beginPath();ctx.moveTo(320,25);ctx.lineTo(309,53);ctx.lineTo(331,53);ctx.fill();};draw();const spin=choice=>{if(spinning||paid)return;spinning=true;bet=choice;result=Math.floor(Math.random()*37);start=performance.now();const finalAngle=-(result+.5)*Math.PI*2/37-Math.PI/2+Math.PI*12;const frame=t=>{if(g.mode!=='city'||token!==this.casinoToken||!$('casinoCanvas'))return;const q=Math.min(1,(t-start)/2300);angle=finalAngle*(1-Math.pow(1-q,3));draw();if(q<1)requestAnimationFrame(frame);else settle(result!==0&&(result%2?'red':'black')===bet?40:0,'Numéro '+result);};requestAnimationFrame(frame);};btn('MISER SUR ROUGE',()=>spin('red'));btn('MISER SUR NOIR',()=>spin('black'));
 }else if(kind==='slots'){let t=0;const values=[0,0,0],symbols=['★','7','◆','☀'];const draw=()=>{bg();for(let i=0;i<3;i++){ctx.fillStyle='#fff0c7';ctx.fillRect(75+i*170,140,150,180);ctx.fillStyle=['#ff7796','#54acb7','#f7bd46'][i];ctx.font='90px sans-serif';ctx.textAlign='center';ctx.fillText(symbols[values[i]],150+i*170,260);}};draw();let running=false;btn('LANCER LES ROULEAUX',()=>{if(running)return;running=true;const outcome=values.map(()=>Math.floor(Math.random()*4));const started=performance.now();const frame=now=>{if(g.mode!=='city'||token!==this.casinoToken||!$('casinoCanvas'))return;if(now-started<1500){for(let i=0;i<3;i++)values[i]=Math.floor(Math.random()*4);draw();requestAnimationFrame(frame);}else{values.splice(0,3,...outcome);draw();const count=new Set(values).size;settle(count===1?160:count===2?25:0,count===1?'Trois symboles !':count===2?'Une paire':'Pas de combinaison');}};requestAnimationFrame(frame);});
 }else if(kind==='poker'){const deck=Array.from({length:52},(_,i)=>i);for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}let cards=deck.splice(0,5),held=[false,false,false,false,false];const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','V','D','R'];const draw=()=>{bg();cards.forEach((card,i)=>{ctx.fillStyle=held[i]?'#ffe58e':'#fffaf0';ctx.fillRect(20+i*122,155,110,175);ctx.fillStyle=[1,2].includes(Math.floor(card/13))?'#dc5579':'#27394c';ctx.textAlign='center';ctx.font='30px sans-serif';ctx.fillText(ranks[card%13],75+i*122,207);ctx.font='48px sans-serif';ctx.fillText(suits[Math.floor(card/13)],75+i*122,280);});};draw();canvas.onclick=e=>{if(paid)return;const r=canvas.getBoundingClientRect(),i=Math.floor(((e.clientX-r.left)*640/r.width-20)/122);if(i>=0&&i<5){held[i]=!held[i];draw();}};btn('GARDER / CHANGER LES CARTES',()=>{if(paid)return;cards=cards.map((c,i)=>held[i]?c:deck.pop());draw();const rank=M.pokerRank(cards);settle(20*rank.mult,rank.name);});$('casinoResult').textContent='Cliquez les cartes à garder, puis changez les autres.';
 }else{const board=new M.Board(kind);this.boardGame=board;const symbols=['','♟','♞','♝','♜','♛','♚'];const draw=()=>{bg();for(let y=0;y<8;y++)for(let x=0;x<8;x++){const px=120+x*50,py=40+y*50,index=y*8+x;ctx.fillStyle=(x+y)%2?'#438f91':'#f7e8c6';if(index===board.selected)ctx.fillStyle='#ffd876';ctx.fillRect(px,py,50,50);const piece=board.board[index];if(piece){ctx.fillStyle=piece>0?'#fffdf5':'#26394e';ctx.strokeStyle='#102a35';ctx.lineWidth=2;if(kind==='checkers'){ctx.beginPath();ctx.arc(px+25,py+25,18,0,Math.PI*2);ctx.fill();ctx.stroke();if(Math.abs(piece)===2){ctx.beginPath();ctx.arc(px+25,py+25,10,0,Math.PI*2);ctx.stroke();}}else{ctx.textAlign='center';ctx.font='43px serif';ctx.strokeText(symbols[Math.abs(piece)],px+25,py+39);ctx.fillText(symbols[Math.abs(piece)],px+25,py+39);}}}};draw();canvas.onclick=e=>{if(board.turn!==1||board.result)return;const r=canvas.getBoundingClientRect(),x=Math.floor(((e.clientX-r.left)*640/r.width-120)/50),y=Math.floor(((e.clientY-r.top)*500/r.height-40)/50);if(x<0||x>7||y<0||y>7)return;const i=y*8+x;if(board.board[i]>0)board.selected=i;else if(board.selected>=0&&board.play(board.selected,i)){board.selected=board.forced;draw();setTimeout(()=>{board.bot();draw();if(board.result)settle(board.result==='win'?40:board.result==='draw'?20:0,board.result==='win'?'Victoire':board.result==='draw'?'Partie nulle':'Défaite');},300);}draw();};$('casinoResult').textContent=kind==='chess'?'Blancs : sélectionnez une pièce puis sa destination. Variante sans roque ni prise en passant.':'Blancs : prises obligatoires et prises multiples. Cliquez un pion puis sa destination.';
 }btn('RETOUR AU CASINO',()=>g.openPlace('casino'));
};
const update=P.update;P.update=function(){update.call(this);const g=this.g;if(!g.cityActive)return;const s=g.city,p=g.player;$('cash').textContent=money(g.cash);if(!g.city.job&&!g.operation&&!g.raid){$('objectiveType').textContent='SUNSHINE CITY';$('objectiveTitle').textContent='Votre ville, vos envies';$('objectiveText').textContent='M / pavé tactile → Lieux, commerces et activités. Approchez un comptoir, puis E / Triangle.';}let badge=$('cityStatus');if(!badge){badge=document.createElement('div');badge.id='cityStatus';$('hud').appendChild(badge);}badge.textContent='SUNSHINE CITY  ·  '+String(Math.floor(s.clock)).padStart(2,'0')+':'+String(Math.floor(s.clock%1*60)).padStart(2,'0')+'  ·  '+{sun:'SOLEIL',rain:'PLUIE',snow:'NEIGE'}[s.weather]+'  '+('★'.repeat(s.wanted)+'☆'.repeat(3-s.wanted));
 if(g.cityTask)$('context').textContent={lift:'Ascenseur',train:'Entraînement',heal:'Soins',repair:'Réparation',wheel:'Tour de grande roue',rob:'Ouverture des coffres'}[g.cityTask.kind]+' · '+Math.ceil(g.cityTask.duration-g.cityTask.time)+' s';else if(g.heliFlying)$('context').textContent='HÉLICOPTÈRE · R2 / Espace : monter · L2 / Maj : descendre · E : sortir une fois posé';else if(!g.vehicle){const b=g.world.services.find(b=>Math.hypot(p.x-b.service.x,p.z-b.service.z)<3.6);const lift=g.world.buildings.find(b=>Math.hypot(p.x-b.lift.x,p.z-b.lift.z)<2.2);if(lift)$('context').textContent='E / △ ASCENSEUR · étage suivant / retour au sol';else if(b)$('context').textContent='E / △ '+b.name;else if(g.npcs.some(n=>n.role==='civil'&&!n.recruited&&Math.hypot(n.x-p.x,n.z-p.z)<2.5))$('context').textContent='E / △ Parler et recruter';}
 if(g.city.job){$('objectiveType').textContent='MISSION URBAINE · '+Math.ceil(g.city.job.remaining)+' S';$('objectiveTitle').textContent={parcel:'Livraison de colis',race:'Course en voiture',heli:'Vol panoramique',dog:'Promenade du chien'}[g.city.job.type];$('objectiveText').textContent='Suivez le trajet jaune. Étape '+(g.city.job.index+1)+'.';}if(g.cityTarget){$('objectiveDistance').textContent='DESTINATION · '+Math.round(Math.hypot(g.cityTarget.x-p.x,g.cityTarget.z-p.z))+' m';const c=this.mapContext,scale=1.05,target=g.cityTarget;c.strokeStyle='#ffe86c';c.lineWidth=3;c.beginPath();c.moveTo(115,115);c.lineTo(115+(Math.round(p.x/50)*50-p.x)*scale,115);c.lineTo(115+(Math.round(p.x/50)*50-p.x)*scale,115+(Math.round(target.z/50)*50-p.z)*scale);c.lineTo(115+(target.x-p.x)*scale,115+(Math.round(target.z/50)*50-p.z)*scale);c.lineTo(115+(target.x-p.x)*scale,115+(target.z-p.z)*scale);c.stroke();}
};
const pause=P.renderPause;P.renderPause=function(){pause.call(this);if(!this.g.cityActive)return;const menu=$('panelBody').querySelector('.menu-buttons');for(const[id,label]of [['directory','EXPLORER LA VILLE'],['gang','MON GANG']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>this.g.openPlace(id);menu.appendChild(b);}const row=document.createElement('div');row.className='weather-controls';for(const[id,label]of [['sun','Soleil'],['rain','Pluie'],['snow','Neige']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{this.g.city.weather=id;this.g.save();this.g.setMode('play');};row.appendChild(b);}menu.appendChild(row);};
const map=P.renderMap;P.renderMap=function(){map.call(this);if(!this.g.cityActive)return;const b=document.createElement('button');b.className='primary';b.textContent='LIEUX, COMMERCES ET ACTIVITÉS';b.onclick=()=>this.g.openPlace('directory');$('panelBody').prepend(b);};
})(Marlon);
