(function(M){'use strict';const T=THREE,G=M.Game.prototype;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),pos=(x,z)=>({x,z});
G.initCity=function(){this.city=M.validCity(this.store.read()?.city);this.cityActive=true;this.cityTask=null;this.cityTarget=null;this.accident=null;this.npcs=[];this.pets=[];this.policeCooldown=0;this.physicsClock=0;this.cityMenus={};
 if(!this.city.cars.length)this.city=M.validCity({...this.city,cars:[]});this.cars.forEach((c,i)=>{const state=this.city.cars[i];if(i===13){state.id='works';state.color='#ffca62';}if(i>=30){state.id=['police','police','tow','sweeper'][i-30];state.color=i<32?'#386bb5':i===32?'#ffd36c':'#6ce3ac';}this.rebuildCar(c,state);c.traffic=i>=14&&i<32;c.cityTraffic=c.traffic;const bx=-250+(i%6)*50,bz=-150+Math.floor(i/6)*50;c.cityPath=[pos(bx+3,bz+103),pos(bx+3,bz-47),pos(bx+47,bz-47),pos(bx+47,bz+103)];c.path=c.cityPath;c.next=i%4;if(c.traffic){c.x=c.path[c.next].x;c.z=c.path[c.next].z;c.next=(c.next+1)%4;const t=c.path[c.next];c.yaw=Math.atan2(t.x-c.x,-(t.z-c.z));}this.animateCar(c,0);});
 this.traffic=this.cars.filter(c=>c.traffic);if(!this.hasSave){this.city.cars[0].owned=true;this.cars[0].owned=true;this.cars[0].x=-219;this.cars[0].z=250;this.cars[0].yaw=Math.PI/2;}
 M.dress(this.actor,this.city);for(let i=0;i<76;i++){const block=this.world.buildings[i%this.world.buildings.length],x=block.x+(i%2?16:-16),z=block.z+(i%3-1)*8;const role=i===0?'works':i===1?'sweeper':'civil';const actor=M.character(role==='works'?'#e3e951':role==='sweeper'?'#d5f83e':M.PALETTE[i%8]);if(role==='works')actor.materials.pants.color.set('#977357');if(role==='sweeper')actor.materials.pants.color.set('#53b36c');this.scene.add(actor.root);this.npcs.push({x,z,y:0,yaw:0,actor,role,home:pos(x,z),target:pos(x,z+8),health:100,phase:i,wait:0,recruited:false});}
 for(const b of this.world.services.filter(b=>!['fair','park','heli','villa'].includes(b.id))){const actor=M.character(b.id==='police'?'#3864ac':b.id==='hospital'?'#eaf5ff':M.PALETTE[this.npcs.length%8]);if(b.id==='police'){M.oval(actor.accessories,M.mat('#3260a0'),0,.1,0,.13,.06,.13);M.round(actor.styleExtras,.055,.06,.016,-.12,1.34,.15,M.mat('#ffdf6b'),.01);}this.scene.add(actor.root);this.npcs.push({x:b.x,z:b.z+3.7,y:0,yaw:Math.PI,actor,role:'staff',health:100,phase:0,wait:0,service:b.id});}
 this.npcs[0].x=-221;this.npcs[0].z=245;this.npcs[1].x=-229;this.npcs[1].z=245;this.syncPets();this.heli=M.heliModel();const h=this.world.services.find(b=>b.id==='heli');this.heli.root.position.set(h.x,h.height+.4,h.z);this.scene.add(this.heli.root);this.heliFlying=false;this.heliSpeed=0;
 const geometry=new T.BufferGeometry,points=new Float32Array(1800);for(let i=0;i<points.length;i+=3){points[i]=(Math.random()-.5)*80;points[i+1]=Math.random()*35;points[i+2]=(Math.random()-.5)*80;}geometry.setAttribute('position',new T.BufferAttribute(points,3));this.weatherFX=new T.Points(geometry,new T.PointsMaterial({color:'#ffffff',size:.12,transparent:true,opacity:.7}));this.weatherFX.frustumCulled=false;this.scene.add(this.weatherFX);
 this.winchLine=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]),new T.LineBasicMaterial({color:'#d9e6e3'}));this.winchLine.visible=false;this.scene.add(this.winchLine);this.routeLine=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:'#ffe763',depthTest:false}));this.routeLine.renderOrder=9;this.scene.add(this.routeLine);this.world.markers.forEach(m=>m.material.opacity=.3);this.city.clock=this.city.clock||10;
};
G.rebuildCar=function(c,s){if(c.model){this.scene.remove(c.model.root);}const spec=M.CARS.find(v=>v.id===s.id)||M.CARS[0];c.model=M.carModel(spec.id,s.color);c.name=spec.name;c.spec=spec;c.owned=s.owned;c.upgrades=s.upgrades;c.cityState=s;this.scene.add(c.model.root);M.customCar(c,s);};
const snapshot=G.snapshotState;G.snapshotState=function(){const s=snapshot.call(this);if(this.city)s.city=this.city;return s;};
const drive=M.drive;M.drive=function(c,u,dt){if(!c.spec)return drive(c,u,dt);const boost=(c.upgrades?.includes('engine')?1.18:1)*(c.upgrades?.includes('turbo')?1.22:1),old=c.speed;let acceleration=u.gas*c.spec.accel*boost;if(u.brake>0)acceleration-=u.brake*(c.speed>.6?22:7);if(c.speed<-.6&&u.gas>.1)acceleration=u.gas*18;c.speed=M.clamp(c.speed+acceleration*dt,-9,c.spec.maxSpeed*boost);c.speed*=Math.exp(-(u.handbrake?2.3:.18)*dt);if(!u.gas&&!u.brake){c.speed*=Math.exp(-.32*dt);if(Math.abs(c.speed)<.08)c.speed=0;}const steer=u.steer*.53/(1+Math.abs(c.speed)*.024);c.steer=M.damp(c.steer||0,steer,9,dt);c.yaw+=Math.tan(c.steer)*c.speed/2.8*dt*(u.handbrake?1.5:1);c.dx=Math.sin(c.yaw)*c.speed*dt;c.dz=-Math.cos(c.yaw)*c.speed*dt;return Math.abs(c.speed-old);};
const animateCar=G.animateCar;G.animateCar=function(c,dt,brake=0){animateCar.call(this,c,dt,brake);if(!this.cityActive)return;c.model.body.position.y+=(c.lower||0);const ratio=1-c.health/100;c.model.body.rotation.z+=Math.sin(c.x)*ratio*.015;for(const [i,part]of(c.model.breakables||[]).entries()){if(i===0){part.scale.z=1-ratio*.09;part.rotation.x=ratio*.025;}else if(i===1)part.visible=c.health>30;else{part.rotation.z=ratio*.25;part.position.y=.5-ratio*.3;}}for(let i=0;i<c.model.beacons.length;i++)c.model.beacons[i].visible=this.city.wanted>0&&Math.floor(this.t*8+i)%2===0;};
G.crime=function(level,label){if(!this.city)return;this.city.wanted=Math.max(this.city.wanted,level);this.city.heat=35+level*25;this.toast(label+' · '+this.city.wanted+' étoile(s)');};
G.spend=function(amount,action){if(!Number.isFinite(amount)||amount<0)return false;if(this.cash<amount){this.toast('Fonds insuffisants : '+amount+' pièces nécessaires.');return false;}this.cash-=amount;action();this.save();return true;};
G.buyCar=function(id,color){const spec=M.CARS.find(c=>c.id===id&&c.price>0);if(!spec)return false;const dealer=this.world.services.find(b=>b.id==='dealer'),spots=[pos(dealer.x-10,dealer.z+21),pos(dealer.x,dealer.z+21),pos(dealer.x+10,dealer.z+21)];const spot=spots.find(p=>!this.carAt(p.x,p.z,null,1));if(!spot){this.toast('Livraison impossible : libérez le parking du concessionnaire.');return false;}const index=this.city.cars.findIndex((c,i)=>i<14&&!c.owned&&this.cars[i]!==this.vehicle);if(index<0){this.toast('Collection complète : 14 emplacements.');return false;}return this.spend(spec.price,()=>{const s=this.city.cars[index]={id,color:M.PALETTE.includes(color)?color:M.PALETTE[0],owned:true,upgrades:[]},c=this.cars[index];c.x=spot.x;c.z=spot.z;c.yaw=Math.PI/2;c.speed=0;c.health=100;c.traffic=false;this.rebuildCar(c,s);this.animateCar(c,0);this.toast(spec.name+' livré sur le parking !');});};
G.nearCar=function(){return this.vehicle||this.cars.filter(c=>c.owned).sort((a,b)=>dist(a,this.player)-dist(b,this.player))[0];};
G.upgradeCar=function(id){const c=this.nearCar(),u=M.UPGRADES.find(v=>v.id===id);if(!c||!u||dist(c,this.player)>38)return this.toast('Amenez votre véhicule au garage.');if(c.cityState.upgrades.includes(id))return this.toast('Cette pièce est déjà installée.');this.spend(u.price,()=>{c.cityState.upgrades.push(id);this.rebuildCar(c,c.cityState);this.animateCar(c,0);});};
G.buyOutfit=function(id){const item=M.OUTFITS.find(v=>v.id===id);if(!item)return;if(this.city.closet.includes(id)){this.city.outfit[item.slot]=id;M.dress(this.actor,this.city);this.save();return;}this.spend(item.price,()=>{this.city.closet.push(id);this.city.outfit[item.slot]=id;M.dress(this.actor,this.city);});};
G.syncPets=function(){for(const p of this.pets||[])this.scene.remove(p.model.root);this.pets=this.city.pets.map((state,i)=>{const model=M.petModel(state.kind);this.scene.add(model.root);return{state,model,x:this.player.x+i+1,z:this.player.z+2,y:0};});};
G.startTask=function(kind,duration,extra={}){if(this.cityTask||this.action)return false;this.cityTask={kind,time:0,duration,...extra};this.setMode('play');this.input.clear();return true;};
G.cityInteract=function(){const p=this.player;if(this.cityTask){if(this.cityTask.kind==='rob'){this.cityTask=null;this.toast('Braquage interrompu. Échappez aux patrouilles !');this.save();}return true;}if(this.heliFlying){if(p.y<=this.world.groundHeight(p.x,p.z,p.y)+.5){this.heliFlying=false;this.actor.root.visible=true;p.x+=3;p.vy=0;this.heli.root.position.set(p.x-3,p.y,p.z);this.save();}else this.toast('Posez l’hélicoptère avant de sortir.');return true;}
 if(this.vehicle)return false;
 for(const b of this.world.buildings)if(dist(p,b.lift)<2.2){const floor=Math.round((p.y-.22)/4),target=floor>=b.floors?0:floor+1;this.startTask('lift',2,{from:p.y,to:target*4+.24,b});return true;}
 for(const b of this.world.services){if(dist(p,b.service)<3.6){this.openPlace(b.id);return true;}}
 const h=this.heli.root.position;if(Math.hypot(h.x-p.x,h.z-p.z)<4&&Math.abs(h.y-p.y)<2){this.heliFlying=true;this.player.armed=false;this.toast('Hélicoptère : déplacement + stick droit ; R2 / Espace monte, L2 / Maj descend.');return true;}
 const npc=this.npcs.find(n=>n.role==='civil'&&!n.recruited&&dist(n,p)<2.5);if(npc){this.openPlace('recruit',npc);return true;}
 const pet=this.pets.find(n=>dist(n,p)<2);if(pet){this.openPlace('pet',pet);return true;}
 return false;};
const interact=G.interact;G.interact=function(){if(this.cityActive&&this.cityInteract())return;const was=this.vehicle;interact.call(this);if(this.action?.kind==='enter'&&!this.action.car.owned&&this.cityActive)this.crime(1,'Véhicule emprunté sans autorisation');};
const update=G.updatePlayer;G.updatePlayer=function(u,dt){if(!this.cityActive)return update.call(this,u,dt);const p=this.player;
 if(this.cityTask){const a=this.cityTask;a.time+=dt;const q=Math.min(1,a.time/a.duration);p.vx=p.vz=0;if(a.kind==='lift'){p.y=a.from+(a.to-a.from)*(q*q*(3-2*q));a.b.lift.mesh.position.y=p.y+.1;p.x=a.b.lift.x;p.z=a.b.lift.z;}else if(a.kind==='wheel'){const ride=this.world.rides[0],v=ride.cabins[0].getWorldPosition(new T.Vector3());p.x=v.x;p.z=v.z;p.y=v.y-.55;}else{p.y=this.world.groundHeight(p.x,p.z);}
 M.animateCharacter(this.actor,0,dt,this.t,false,false,0,0,{seated:a.kind==='wheel',revive:['train','heal','repair','rob'].includes(a.kind)});if(a.kind==='train'){this.actor.ra.rotation.x=this.actor.la.rotation.x=-1.0-Math.sin(a.time*3)*.65;}this.actor.root.position.set(p.x,p.y,p.z);
 if(a.kind==='rob'){const n=Math.min(3,Math.floor(a.time/6));if(n>(a.opened||0)){this.cash+=750*n;a.opened=n;this.toast('Coffre '+n+' : +'+750*n+' pièces.');}}
 if(q>=1){this.cityTask=null;if(a.kind==='train'){this.city[a.stat]=Math.min(100,this.city[a.stat]+5);M.dress(this.actor,this.city);this.toast('Entraînement terminé : +5 '+(a.stat==='strength'?'force':'précision'));}if(a.kind==='heal')p.health=100;if(a.kind==='repair'&&a.car)a.car.health=100;if(a.kind==='wheel'){const b=this.world.services.find(b=>b.id==='fair');p.x=b.x;p.z=b.z+12;p.y=0;}if(a.kind==='rob')this.toast('Trois coffres ouverts : fuyez les patrouilles !');this.save();}return;}
 if(this.heliFlying){const look=u.lookX*dt*2.0+u.mouseX*.002;this.cam.yaw+=look;this.cam.pitch=M.clamp(this.cam.pitch+(u.lookY*dt+u.mouseY*.002),-.2,1);const v=M.moveVector(u.x,u.forward,this.cam.yaw),rise=(u.gas||this.input.keys.has('Space')?1:0)-(u.brake||u.sprint?1:0);p.x=M.clamp(p.x+v.x*25*dt,-300,300);p.z=M.clamp(p.z+v.z*25*dt,-300,300);let floor=0;for(const b of this.world.buildings)if(Math.abs(p.x-b.x)<15&&Math.abs(p.z-b.z)<15)floor=Math.max(floor,b.height+.4);p.y=M.clamp(p.y+rise*12*dt,floor,85);p.yaw=this.cam.yaw;this.heli.root.position.set(p.x,p.y,p.z);this.heli.root.rotation.y=Math.PI-p.yaw;this.heli.rotor.rotation.y+=dt*30;this.actor.root.visible=false;return;}
 this.actor.root.visible=true;const car=this.vehicle,health=car?.health,speed=Math.abs(car?.speed||0);update.call(this,u,dt);
 if(car&&car.health<health&&speed>5&&(!this.accident||this.t-this.accident.at>8)){this.crime(speed>22?2:1,'Collision signalée');const other=this.cars.find(c=>c!==car&&dist(c,car)<7);if(other)other.health=Math.max(0,other.health-speed*.7);this.accident={at:this.t,car,stage:'dispatch',timer:0};this.toast('Accident : patrouille et dépanneuse en intervention. Constat : 80 pièces.');this.impactMark(car.x,car.z);}
 if(car&&speed>6){if(this.t>(this.lastTrafficFine||0)+5){const axis=Math.abs(Math.cos(car.yaw))>.7?0:1;const crossed=this.world.signals.find(sig=>dist(sig,car)<6);if(crossed&&this.signalState(axis)==='red'){this.lastTrafficFine=this.t;this.crime(1,'Feu rouge franchi');}}for(const prop of this.world.props)if(prop.health>0&&dist(prop,car)<2.5)this.breakProp(prop);for(const n of this.npcs)if(n.role==='civil'&&dist(n,car)<2){n.wait=8;this.crime(2,'Mise en danger d’un piéton');car.speed*=.5;}}
 const villa=this.world.services.find(b=>b.id==='villa');if(!car&&dist(p,villa.trampoline)<1.8&&p.y<1.1&&p.vy<=0){p.vy=10;p.y=1.0;this.toast('Trampoline !');}
};
G.impactMark=function(x,z){const m=M.mesh(this.scene,new T.CircleGeometry(1.1,16),new T.MeshBasicMaterial({color:'#343a42',transparent:true,opacity:.65,depthWrite:false}),x,.035,z);m.rotation.x=-Math.PI/2;if(!this.marks)this.marks=[];this.marks.push(m);if(this.marks.length>30)this.scene.remove(this.marks.shift());};
G.serviceDrive=function(c,target,dt){const key=Math.round(target.x)+','+Math.round(target.z);if(c.serviceKey!==key){c.serviceKey=key;const x=Math.round(c.x/50)*50+3,z=Math.round(c.z/50)*50+3,tx=Math.round(target.x/50)*50+3,tz=Math.round(target.z/50)*50+3;c.serviceRoute=[{x,z:c.z},{x,z},{x:tx,z},{x:tx,z:tz},{x:target.x,z:tz},target];}const point=c.serviceRoute[0];if(!point)return;const dx=point.x-c.x,dz=point.z-c.z,d=Math.hypot(dx,dz);if(d<1){c.serviceRoute.shift();return;}c.yaw=M.angle(c.yaw,Math.atan2(dx,-dz),5,dt);c.speed=Math.min(12,d*2);this.world.grid.move(c,dx/d*c.speed*dt,dz/d*c.speed*dt,1.4);this.animateCar(c,dt);};
G.breakProp=function(prop){prop.health=0;prop.brokenAt=this.t;prop.root.rotation.z=1.4;this.impactMark(prop.x,prop.z);this.crime(1,'Mobilier endommagé');};
G.signalState=function(axis){const phase=this.t%28;return axis===0?(phase<11?'green':phase<13?'amber':'red'):(phase>=14&&phase<25?'green':phase>=25&&phase<27?'amber':'red');};
G.updateTraffic=function(dt){if(!this.cityActive)return;for(const c of this.traffic){if(!c.traffic||c===this.vehicle||c===this.action?.car)continue;const target=c.path[c.next],dx=target.x-c.x,dz=target.z-c.z,d=Math.hypot(dx,dz);if(d<1.5)c.next=(c.next+1)%4;const yaw=Math.atan2(dx,-dz);c.yaw=M.angle(c.yaw,yaw,5,dt);let blocked=false;const sx=Math.sin(c.yaw),sz=-Math.cos(c.yaw),axis=Math.abs(sz)>.7?0:1;
 for(const signal of this.world.signals){const ahead=(signal.x-c.x)*sx+(signal.z-c.z)*sz,side=Math.abs((signal.x-c.x)*sz-(signal.z-c.z)*sx);if(ahead>7&&ahead<20&&side<6&&this.signalState(axis)!=='green')blocked=true;}
 const probe=pos(c.x+sx*7,c.z+sz*7);if(this.cars.some(v=>v!==c&&dist(v,probe)<4)||!this.vehicle&&dist(this.player,probe)<4||this.npcs.some(n=>n.role==='civil'&&dist(n,probe)<2.5))blocked=true;
 c.speed=M.damp(c.speed,blocked?0:c.spec.id==='bike'?5:9,blocked?7:1.8,dt);const ox=c.x,oz=c.z;if(this.world.grid.move(c,sx*c.speed*dt,sz*c.speed*dt,1.5)){c.x=ox;c.z=oz;c.speed=0;}this.animateCar(c,dt,blocked?1:0);
 }
 this.updateCity(dt);
};
G.updateCity=function(dt){const p=this.player,s=this.city;this.physicsClock+=dt;s.clock=(s.clock+dt/45)%24;this.policeCooldown=Math.max(0,this.policeCooldown-dt);s.heat=Math.max(0,s.heat-dt);if(!s.heat&&s.wanted){s.wanted--;s.heat=s.wanted?20:0;this.save();}
 const night=s.clock<6||s.clock>19;this.sun.intensity=M.damp(this.sun.intensity,night?.22:s.weather==='sun'?1.35:.8,.5,dt);if(this.ambient)this.ambient.intensity=M.damp(this.ambient.intensity,night?.38:.62,.5,dt);this.world.lampMat.emissiveIntensity=night?3:.4;const sky=this.scene.children.find(o=>o.material?.uniforms?.horizon);if(sky){sky.material.uniforms.top.value.set(night?'#101c48':s.weather==='sun'?'#087cea':'#52769c');sky.material.uniforms.horizon.value.set(night?'#6262a5':s.weather==='sun'?'#a5e8ff':'#a7bfd2');}this.scene.fog.color.set(night?'#233954':'#62c5ed');
 this.weatherFX.visible=s.weather!=='sun';if(this.weatherFX.visible){this.weatherFX.position.set(p.x,0,p.z);this.weatherFX.material.size=s.weather==='snow'?.18:.08;const a=this.weatherFX.geometry.attributes.position;for(let i=0;i<a.count;i++){a.array[i*3+1]-=dt*(s.weather==='snow'?2:18);if(a.array[i*3+1]<0)a.array[i*3+1]=35;}a.needsUpdate=true;}
 for(const prop of this.world.props)prop.root.visible=dist(prop,p)<85;for(const sig of this.world.signals){sig.root.visible=dist(sig,p)<100;for(const {lamp,axis,i}of sig.lamps){const state=this.signalState(axis);lamp.material.color.set((state==='red'&&i===0)||(state==='amber'&&i===1)||(state==='green'&&i===2)?['#ff375b','#ffd057','#58ffbb'][i]:'#273a42');}}
 for(const gate of this.world.gates)gate.mesh.position.y=M.damp(gate.mesh.position.y,dist(p,gate)<9?-1.2:1,4,dt);
 for(const ride of this.world.rides){ride.wheel.rotation.z+=dt*.14;for(const cabin of ride.cabins)cabin.rotation.z=-ride.wheel.rotation.z;}
 for(const model of this.world.showroom)model.root.rotation.y+=dt*.07;
 for(const n of this.npcs){const near=dist(n,p)<65;n.actor.root.visible=near&&!n.recruited;if((!near&&n.role==='civil')||n.recruited)continue;let speed=0;n.wait=Math.max(0,n.wait-dt);if(n.role==='civil'&&!n.wait){if(dist(n,n.target)<.7){const h=n.home;n.target=pos(h.x,h.z+(Math.sin(this.t+n.phase)>0?1:-1)*9);n.wait=1.2+Math.random()*3;}const dx=n.target.x-n.x,dz=n.target.z-n.z,d=Math.hypot(dx,dz);if(d>.5){speed=1.0+(n.phase%4)*.13;this.world.grid.move(n,dx/d*speed*dt,dz/d*speed*dt,.25);n.yaw=M.angle(n.yaw,Math.atan2(dx,-dz),5,dt);}}if(n.role==='works'){const broken=this.world.props.find(prop=>!prop.health);if(broken){this.moveAgent(n,broken,3,dt);speed=Math.hypot(n.vx||0,n.vz||0);if(dist(n,broken)<2){n.repair=(n.repair||0)+dt;if(n.repair>4){broken.health=100;broken.root.rotation.z=0;n.repair=0;this.toast('Les services techniques ont réparé le mobilier.');}}}}if(n.role==='sweeper'){n.x+=Math.sin(this.t*.2)*dt*.3;speed=.5;}M.animateCharacter(n.actor,speed,dt,this.t+n.phase,false,false,0,0,{revive:n.repair>0});n.actor.root.position.set(n.x,0,n.z);n.actor.root.rotation.y=Math.PI-n.yaw;}
 for(const pet of this.pets){const command=pet.state.command;let speed=0;if(command==='follow'&&dist(pet,p)>1.8){const d=dist(pet,p);speed=d>7?5:2.8;this.world.grid.move(pet,(p.x-pet.x)/d*speed*dt,(p.z-pet.z)/d*speed*dt,.2);pet.model.root.rotation.y=Math.atan2(p.x-pet.x,p.z-pet.z);}pet.model.root.position.set(pet.x,command==='down'?-.16:0,pet.z);pet.model.body.rotation.x=command==='sit'?-.55:0;pet.model.tail.rotation.y=Math.sin(this.t*8)*.45;pet.model.legs.forEach((l,i)=>l.rotation.x=command==='paw'&&i===0?-1.3:Math.sin(this.t*9+i*Math.PI)*speed*.07);}
 if(s.wanted&&this.policeCooldown===0){const cops=this.cars.filter(c=>c.spec.id==='police');for(const c of cops){const distance=dist(c,p);if(distance<65){c.traffic=false;const target=this.nav.direction(c,p,this.t);if(distance>8&&Math.hypot(target.x,target.z)>.1){c.yaw=M.angle(c.yaw,Math.atan2(target.x,-target.z),3,dt);c.speed=M.damp(c.speed,Math.min(15,distance*.5),2,dt);this.world.grid.move(c,Math.sin(c.yaw)*c.speed*dt,-Math.cos(c.yaw)*c.speed*dt,1.5);this.animateCar(c,dt);}if(distance<9){s.lastFine+=dt;if(s.lastFine>8){const fine=80*s.wanted;this.cash=Math.max(0,this.cash-fine);this.toast('Interpellation : '+fine+' pièces d’amende.');s.wanted=0;s.heat=0;s.lastFine=0;this.policeCooldown=30;this.cityTask=null;this.save();}}}}}
 if(this.accident){const a=this.accident;a.timer+=dt;if(a.stage==='dispatch'&&a.timer>8){this.cash=Math.max(0,this.cash-80);a.stage='approach';this.toast('Constat établi : 80 pièces. Dépannage en approche.');}const tow=this.cars[32];if(a.stage==='approach'){this.serviceDrive(tow,{x:a.car.x+4,z:a.car.z+3},dt);if(dist(tow,a.car)<7&&a.timer>14){if(this.vehicle===a.car)this.toast('Sortez du véhicule pour autoriser le remorquage.');else{a.stage='winch';a.timer=0;}}}if(a.stage==='winch'){this.winchLine.visible=true;const cable=this.winchLine.geometry.attributes.position;cable.setXYZ(0,tow.x,1,tow.z);cable.setXYZ(1,a.car.x,.7,a.car.z);cable.needsUpdate=true;this.winchLine.geometry.computeBoundingSphere();a.car.x=M.damp(a.car.x,tow.x,1.1,dt);a.car.z=M.damp(a.car.z,tow.z+1,1.1,dt);this.animateCar(a.car,dt);a.car.model.root.position.y=Math.min(.9,a.timer*.2);if(a.timer>5){a.stage='transport';a.timer=0;}}if(a.stage==='transport'){this.winchLine.visible=false;const garage=this.world.services.find(b=>b.id==='garage');this.serviceDrive(tow,{x:garage.x+5,z:garage.z+20},dt);a.car.x=tow.x;a.car.z=tow.z+1;this.animateCar(tow,dt);this.animateCar(a.car,dt);a.car.model.root.position.y=.9;if(dist(tow,pos(garage.x+5,garage.z+20))<2){a.car.x=garage.x+10;a.car.z=garage.z+20;this.animateCar(a.car,0);this.accident=null;this.toast('Voiture déposée au garage. Réparation disponible au comptoir.');this.save();}}}
 const sweep=this.cars[33];sweep.x=-229+Math.sin(this.t*.04)*14;sweep.z=250;sweep.yaw=Math.cos(this.t*.04)>0?Math.PI/2:-Math.PI/2;sweep.speed=.6;this.animateCar(sweep,dt);sweep.model.extras.traverse(o=>{if(o.name==='brush')o.rotation.y+=dt*7;});this.tickOrders(dt);this.tickJob(dt);
};
const fire=G.fire;G.fire=function(){const before=this.player.mag;fire.call(this);if(this.cityActive&&this.player.mag<before){const w=M.WEAPONS.find(w=>w.id===this.city.weapon);this.player.fireCd=w.cooldown;this.crime(2,'Tir signalé');if(this.world.services.some(b=>b.id==='range'&&dist(b,this.player)<15)){this.city.accuracy=Math.min(100,this.city.accuracy+.15);this.city.wanted=0;}}};
const damage=G.damageEnemy;G.damageEnemy=function(e,n){const w=M.WEAPONS.find(v=>v.id===this.city?.weapon);return damage.call(this,e,n===27&&w?w.damage*(1+(this.city.accuracy||0)/500):n*(1+(this.city?.strength||0)/400));};
const cityHurt=G.hurt;G.hurt=function(n){cityHurt.call(this,n);if(this.action?.kind==='recover'){this.cityTask=null;this.heliFlying=false;this.actor.root.visible=true;}};
const enemies=G.updateEnemies;G.updateEnemies=function(dt){if(this.cityActive){const p=this.player;for(const e of this.enemies)if(dist(e,p)<80&&e.home>=8&&!e.raid){e.cooldown=Math.max(e.cooldown,1);}}enemies.call(this,dt);};
G.giveOrder=function(i,kind){const a=this.allies[i];if(!a)return;const targets={car:'dealer',rob:'pizza',weapon:'arms',hospital:'hospital',gym:'gym',range:'range'};if(['follow','guard'].includes(kind)){a.order=null;this.toast('Équipier : '+(kind==='guard'?'garde du corps':'suivez-moi'));return;}const b=this.world.services.find(b=>b.id===targets[kind]);a.order={kind,target:b.service,time:0};this.toast('Ordre transmis : '+kind);};
const allies=G.updateAllies;G.updateAllies=function(dt){const ordered=this.allies.filter(a=>a.order&&a.health>0),normal=this.allies.filter(a=>!a.order||a.health<=0),all=this.allies;this.allies=normal;allies.call(this,dt);this.allies=all.filter(a=>normal.includes(a)||ordered.includes(a));for(const a of ordered){const o=a.order;this.moveAgent(a,o.target,3.8,dt);a.yaw=M.angle(a.yaw,Math.atan2(a.vx,-a.vz),5,dt);a.actor.root.position.set(a.x,0,a.z);a.actor.root.rotation.y=Math.PI-a.yaw;M.animateCharacter(a.actor,Math.hypot(a.vx,a.vz),dt,this.t,false,false,0,0,{revive:o.time>0});if(dist(a,o.target)<3){o.time+=dt;if(o.time>6){if(o.kind==='hospital')a.health=100;if(o.kind==='gym')a.power=(a.power||0)+5;if(o.kind==='range')a.cooldown=.5;if(o.kind==='rob'){this.cash+=120;this.crime(2,'Braquage signalé par un commerçant');}if(o.kind==='weapon')this.player.ammo=Math.min(999,this.player.ammo+24);if(o.kind==='car'){const c=this.cars.find(c=>!c.traffic&&c!==this.vehicle);if(c){c.x=this.player.x+5;c.z=this.player.z+5;this.animateCar(c,0);this.crime(1,'Véhicule récupéré par votre équipe');}}a.order=null;this.toast('Ordre terminé. L’équipier revient.');this.save();}}}};
G.tickOrders=function(){};
G.jobRoute=function(type){const by=id=>this.world.services.find(b=>b.id===id).entry;return type==='parcel'?[by('missions'),by('pizza'),by('hospital')]:type==='race'?[pos(-200,200),pos(-200,0),pos(100,0),pos(100,200),pos(-200,200)]:type==='heli'?[pos(225,25),pos(-175,-175),pos(225,25)]:[by('adopt'),by('park'),by('adopt')];};
G.tickJob=function(dt){const job=this.city.job;if(!job)return;job.remaining-=dt;if(job.remaining<=0){this.city.job=null;this.toast('Mission expirée.');this.save();return;}const route=this.jobRoute(job.type),target=route[job.index];this.cityTarget=target;const eligible=job.type==='race'?!!this.vehicle:job.type==='heli'?this.heliFlying:job.type==='dog'?this.pets.some(p=>p.state.command==='follow'&&dist(p,this.player)<10):true;if(target&&dist(this.player,target)<8&&eligible){job.index++;if(job.index>=route.length){const reward={parcel:160,race:350,heli:600,dog:90}[job.type];this.cash+=reward;this.city.job=null;this.cityTarget=null;this.toast('Mission réussie : +'+reward+' pièces.');this.save();}else this.toast('Étape validée. Suivez le trajet jaune.');}
};
})(Marlon);
