/* Camera, analog comfort and vertical collision repairs. */
(function(M){
'use strict';const T=THREE,G=M.Game.prototype,clamp=M.clamp;
// Preserve the radial dead zone and independent sticks; give the right stick a finer center.
M.cameraCurve=value=>{const n=clamp(Number.isFinite(value)?value:0,-1,1);return Math.sign(n)*Math.pow(Math.abs(n),1.55);};
const poll=M.Input.prototype.poll;M.Input.prototype.poll=function(){const u=poll.apply(this,arguments);if(this.last==='pad'){u.lookX=M.cameraCurve(u.lookX);u.lookY=M.cameraCurve(u.lookY);}return u;};
const vibrate=M.Input.prototype.vibrate;M.Input.prototype.vibrate=function(power=.2,time=80){if(M.game?.haptics===false)return;const now=performance.now();if(now-(this.lastRumbleAt??-1000)<65&&power<.65)return;this.lastRumbleAt=now;return vibrate.call(this,clamp(power,0,1),clamp(time,0,220));};
// A support query belongs to the actor that is moving, never to another actor's height.
M.World.prototype.groundHeight=function(x,z,height){const actor=this._groundActor,y=height??actor?.y??0;let probe=Number.isFinite(y)?y:0;if(height===undefined&&actor?.vy<0&&Number.isFinite(this._previousFootY))probe=Math.max(probe,this._previousFootY);for(const b of this.buildings||[]){if(Math.abs(x-b.x)>=13.65||Math.abs(z-b.z)>=13.65)continue;const floors=Math.max(0,b.floors||0);if(!floors)return .22;
  if(x>b.x+8&&Math.abs(z-b.z)<10){if(x>=b.x+12)return .22;const ramp=(b.z+10-z)/5,f=clamp(Math.floor((probe-ramp+.4)/4),0,floors-1),support=f*4+ramp+.22;return support<=probe+.4?Math.max(.22,support):.22;}
  return .22+clamp(Math.floor(Math.max(0,probe-.22+.32)/4),0,floors)*4;
 }return this.surfaceHeight?.(x,z)||0;};
const info=G.animInfo;G.animInfo=function(p,extra={}){const a=info.call(this,p,extra),ground=this.world.groundHeight(p.x,p.z,p.y||0),co=Math.cos(p.yaw),si=Math.sin(p.yaw);a.air=(p.y||0)>ground+.035;a.footGround=[this.world.groundHeight(p.x+co*.12,p.z+si*.12,p.y||0)-ground,this.world.groundHeight(p.x-co*.12,p.z-si*.12,p.y||0)-ground];return a;};
G.alignCityFeet=function(){for(const n of this.npcs||[]){if(n.recruited)continue;n.y=this.world.groundHeight(n.x,n.z,n.y||0);n.actor.root.position.y=n.y;}for(const pet of this.pets||[]){pet.y=this.world.groundHeight(pet.x,pet.z,pet.y||0);pet.model.root.position.y=pet.y+(pet.state.command==='down'?-.16:0);}};
const cityUpdate=G.updateCity;G.updateCity=function(dt){cityUpdate.call(this,dt);this.alignCityFeet();};
const crewUpdate=G.updateAllies;G.updateAllies=function(dt){crewUpdate.call(this,dt);if(!this.vehicle)for(const a of this.allies)if(a.health>0){a.y=this.world.groundHeight(a.x,a.z,a.y||0);a.actor.root.position.y=a.y;}};
const init=G.initCity;G.initCity=function(){init.apply(this,arguments);let s={};try{s=JSON.parse(localStorage.getItem('marlon.rebuild.settings')||'{}');}catch{}this.haptics=s.haptics!==false;this.speedCamera=s.speedCamera!==false;this.fallInfo={height:0,landings:0,lastImpact:0};this.groundedAt=-Infinity;this.jumpBufferedUntil=-Infinity;this.alignCityFeet();};
const handle=G.handle;G.handle=function(u){const p=this.player,canJump=this.mode==='play'&&!this.vehicle&&!this.heliFlying&&!this.cityTask&&!this.action&&!this.lifeAction,requested=canJump&&u.edges.has('jump');let v=u;if(requested){v={...u,edges:new Set(u.edges)};v.edges.delete('jump');this.jumpBufferedUntil=this.t+.14;}handle.call(this,v);if(requested){const ground=this.world.groundHeight(p.x,p.z,p.y);if((p.y<=ground+.08&&p.vy<=.3)||this.t-(this.groundedAt??-Infinity)<.1){p.vy=5.8;this.jumpBufferedUntil=-Infinity;this.groundedAt=-Infinity;}}};
const update=G.updatePlayer;G.updatePlayer=function(u,dt){const p=this.player,world=this.world,oldY=p.y,oldVy=p.vy,onFoot=!this.vehicle&&!this.heliFlying&&!this.action&&!this.cityTask&&!this.lifeAction,groundBefore=world.groundHeight(p.x,p.z,p.y);world._groundActor=p;world._previousFootY=p.y;const carAt=this.carAt;if(onFoot)this.carAt=function(x,z,ignore,r){const car=carAt.call(this,x,z,ignore,r);return car&&!ignore&&Math.hypot(x-p.x,z-p.z)<.6&&p.y>(car.y||0)+(car.model.bounds?.height||2.85)+.08?null:car;};
 try{update.call(this,u,dt);}finally{world._groundActor=null;world._previousFootY=undefined;this.carAt=carAt;}
 if(!onFoot||this.vehicle||this.heliFlying||this.action||this.cityTask||this.lifeAction)return;
 // Vertical sweep prevents fast falls tunnelling through a floor between fixed steps.
 if(p.vy<=0){const floor=world.groundHeight(p.x,p.z,oldY);if(p.y<floor&&oldY>=floor-.35){p.y=floor;p.vy=0;this.actor.root.position.y=p.y;}}
 if(!Number.isFinite(p.y)||p.y< -4){p.y=world.groundHeight(p.x,p.z,0);p.vy=0;this.actor.root.position.y=p.y;}
 const ground=world.groundHeight(p.x,p.z,p.y),landed=p.y<=ground+.04&&p.vy<=.3;if(landed){this.groundedAt=this.t;if(this.jumpBufferedUntil>=this.t){p.vy=5.8;this.jumpBufferedUntil=-Infinity;this.groundedAt=-Infinity;}else if(oldVy< -3&&oldY>groundBefore+.04){this.fallInfo=this.fallInfo||{height:0,landings:0,lastImpact:0};this.fallInfo.landings++;this.fallInfo.lastImpact=Math.abs(oldVy);this.cam.landing=clamp(Math.abs(oldVy)*.007,0,.18);if(this.actor.animator)this.actor.animator.land=Math.max(this.actor.animator.land||0,clamp(Math.abs(oldVy)*.04,.2,.8));this.soundscape?.event('land',clamp(Math.abs(oldVy)/18,.2,1));this.input.vibrate(clamp(Math.abs(oldVy)/60,.08,.32),100);}}
 if(!landed&&this.fallInfo)this.fallInfo.height=Math.max(this.fallInfo.height,oldY-groundBefore);
};
G.updateCamera=function(dt){dt=clamp(dt,0,1);const p=this.player,c=this.cam,car=this.vehicle,aim=!!p.aim&&!car,speed=Math.abs(car?.speed||0),wide=this.speedCamera!==false,air=this.heliFlying,look=new T.Vector3(p.x,p.y+(car?1.35:1.43),p.z);if(aim){look.x+=Math.cos(c.yaw)*.52;look.z+=Math.sin(c.yaw)*.52;}
 // Modest lead gives room to read corners without dragging the player out of frame.
 if(car){const lead=Math.min(1.1,speed*.023);look.x+=Math.sin(car.yaw)*lead;look.z-=Math.cos(car.yaw)*lead;}c.target.lerp(look,1-Math.exp(-(aim?24:car?9:air?7:20)*dt));const anchor=new T.Vector3(p.x,p.y+1.4,p.z),delta=c.target.clone().sub(anchor),len=delta.length();if(len>.01&&this.world.grid.ray(anchor,delta.clone().normalize(),len,.14)<len)c.target.copy(anchor);
 const desired=aim?2.8:car?8.0+(wide?Math.min(1.8,speed*.035):0):air?11:5.6;c.distance=M.damp(c.distance,desired,8,dt);c.kick=M.damp(c.kick||0,0,15,dt);c.landing=M.damp(c.landing||0,0,11,dt);const pitch=clamp(c.pitch+(this.reduceShake?0:c.kick),-.36,.93),dir=new T.Vector3(-Math.sin(c.yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(c.yaw)*Math.cos(pitch));let free=this.world.grid.ray(c.target,dir,c.distance,.28);free=Math.max(.16,free-.13);c.actual=free<c.actual?free:Math.min(free,c.actual+6*dt);this.camera.position.copy(c.target).addScaledVector(dir,c.actual);this.camera.position.y=Math.max(.35,this.camera.position.y-(this.reduceShake?0:c.landing));this.camera.lookAt(c.target);
 // FOV responds to speed with a smooth bounded curve; no shake, blur or flashing streaks.
 const base=aim?51:car?66:air?69:62,target=base+(car&&wide?12*(1-Math.exp(-speed/34)):0);this.camera.fov=M.damp(this.camera.fov,target,5,dt);this.camera.updateProjectionMatrix();
};
if(M.UI){const P=M.UI.prototype,render=P.renderSettings,save=P.saveSettings;P.renderSettings=function(){render.apply(this,arguments);const grid=document.querySelector('#panelBody .settings-grid');if(!grid)return;for(const[id,label,checked]of[['speedCamera','Champ de vision sensible à la vitesse',this.g.speedCamera!==false],['haptics','Vibrations de la manette',this.g.haptics!==false]]){const n=document.createElement('div');n.className='setting';n.innerHTML='<label for="'+id+'">'+label+'</label><input type="checkbox" id="'+id+'">';grid.appendChild(n);const input=document.getElementById(id);input.checked=checked;input.onchange=e=>{this.g[id]=e.target.checked;this.saveSettings();};}}
 P.saveSettings=function(){save.apply(this,arguments);try{const s=JSON.parse(localStorage.getItem('marlon.rebuild.settings')||'{}');s.haptics=this.g.haptics!==false;s.speedCamera=this.g.speedCamera!==false;localStorage.setItem('marlon.rebuild.settings',JSON.stringify(s));}catch{}};
 const pad=P.padMenu;P.padMenu=function(u){const active=document.activeElement;if(active?.tagName==='SELECT'&&Math.abs(u.x)>.4&&this.g.wallTime-this.lastMenu>.2){active.selectedIndex=clamp(active.selectedIndex+Math.sign(u.x),0,active.options.length-1);active.dispatchEvent(new Event('change'));this.lastMenu=this.g.wallTime;return;}return pad.call(this,u);};
}
})(Marlon);
