(function(M){
'use strict';const T=THREE,G=M.Game.prototype,lerp=(a,b,t)=>a+(b-a)*M.clamp(t,0,1),ease=t=>{t=M.clamp(t,0,1);return t*t*(3-2*t);};
M.disposeRig=rig=>{const geometries=new Set,materials=new Set;rig.root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)materials.add(o.material);});rig.root.parent?.remove(rig.root);for(const g of geometries)g.dispose();for(const m of materials)m.dispose();};
G.load=function(){let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('Stockage indisponible');},removeItem:()=>{}};}this.store=new M.StateStore(storage);const state=this.store.read();this.hasSave=!!state;if(!state)return;const s=state.base;this.restoredState=state;Object.assign(this.player,{x:s.x,z:s.z,yaw:s.yaw,health:s.health,mag:s.mag,ammo:s.ammo});if(!this.world.grid.free(s.x,s.z,.5)){this.player.x=-225;this.player.z=250;}this.cash=s.cash;this.rep=s.rep;this.completed=s.completed;this.won=s.won;this.savedSquad=s.squad;this.cam.yaw=s.yaw;for(const t of this.sectors){t.owner=s.owned.includes(t.id)?'player':t.id%3===0?'cendre':'onyx';t.level=s.levels[t.id]||0;}this.cam.target.set(this.player.x,1.4,this.player.z);};
G.initV3=function(){this.nav=new M.Navigation(this.world.grid);this.action=null;this.aiFrame=-1;this.effectTick=0;const s=this.restoredState;if(!s||s.version!==3)return;
 this.t=s.time;this.incomeTimer=s.income;this.raidTimer=s.raidTimer;this.victoryTimer=s.victory;this.operation=s.operation;this.raid=s.raid;this.sectors.forEach((t,i)=>t.capture=s.capture[i]);
 this.cars.forEach((c,i)=>{Object.assign(c,s.cars[i]);if(!this.world.grid.free(c.x,c.z,1.2)){c.x=-219;c.z=250;c.traffic=false;}this.animateCar(c,0);});
 for(const e of this.enemies)M.disposeRig(e.actor);this.enemies=[];for(const data of s.enemies){const a=M.character(data.raid?'#624c38':this.sectors[data.home].owner==='cendre'?'#634643':'#303d50',true);this.scene.add(a.root);const e={...data,y:0,actor:a,hit:0};if(!this.world.grid.free(e.x,e.z,.34)){e.x=this.sectors[e.home].x;e.z=this.sectors[e.home].z+4;}this.enemies.push(e);a.root.position.set(e.x,0,e.z);a.root.visible=e.health>0||e.dead>0;if(e.health<=0){M.animateCharacter(a,0,.1,this.t,false,false,0,0,{dead:true});a.animator.death=1;}}
 for(const a of this.allies)M.disposeRig(a.actor);this.allies=[];for(const data of s.allies){this.addAlly();Object.assign(this.allies[this.allies.length-1],data);}
 if(s.vehicle!==null){this.vehicle=this.cars[s.vehicle];this.vehicle.traffic=false;this.player.x=this.vehicle.x;this.player.z=this.vehicle.z;this.player.yaw=this.vehicle.yaw;}
 this.restoredState=null;
};
G.snapshotState=function(){const p=this.player,base={version:2,cash:this.cash,rep:this.rep,ammo:p.ammo,mag:p.mag,health:p.health,x:p.x,z:p.z,yaw:p.yaw,owned:this.sectors.filter(t=>t.owner==='player').map(t=>t.id),levels:Object.fromEntries(this.sectors.map(t=>[t.id,t.level])),completed:this.completed,squad:this.allies.length,won:this.won};const point=a=>({x:a.x,z:a.z,yaw:a.yaw});return{version:3,base,time:this.t,income:this.incomeTimer,raidTimer:this.raidTimer,victory:this.victoryTimer,capture:this.sectors.map(t=>t.capture),vehicle:this.vehicle?this.cars.indexOf(this.vehicle):null,cars:this.cars.map(c=>({...point(c),health:c.health,traffic:c.traffic,next:c.next||0})),enemies:this.enemies.map(e=>({...point(e),health:e.health,dead:e.dead,home:e.home,raid:e.raid,cooldown:e.cooldown})),allies:this.allies.map(a=>({...point(a),health:a.health,downTime:a.downTime||0})),operation:this.operation,raid:this.raid};};
G.save=function(){if(this.action||this.skipExitSave)return false;const ok=this.store.write(this.snapshotState());if(ok)this.hasSave=true;else this.toast('Sauvegarde impossible. Exportez votre campagne depuis le menu Pause.');return ok;};
G.reset=function(){try{this.store.clear();this.skipExitSave=true;location.reload();}catch{this.toast('Impossible d’effacer la campagne : stockage indisponible.');}};
G.animInfo=function(p,extra={}){const speed=Math.hypot(p.vx||0,p.vz||0),co=Math.cos(p.yaw),si=Math.sin(p.yaw),ground=this.world.groundHeight(p.x,p.z);return{speed,air:(p.y||0)>ground+.02,vy:p.vy||0,landingSpeed:p.lastVertical||0,forward:speed>.05?((p.vx||0)*si-(p.vz||0)*co)/speed:1,strafe:speed>.05?((p.vx||0)*co+(p.vz||0)*si)/speed:0,footGround:[this.world.groundHeight(p.x+co*.12,p.z+si*.12)-ground,this.world.groundHeight(p.x-co*.12,p.z-si*.12)-ground],reload:p.reload||0,reloadProgress:1-(p.reload||0)/1.45,melee:p.melee||0,meleeProgress:1-(p.melee||0)/.62,combo:p.combo||1,recoil:M.clamp((p.fireCd||0)/.18,0,1),pitch:this.cam.pitch,...extra};};
G.seatPoint=function(c){c.model.root.updateMatrixWorld(true);return c.model.body.localToWorld(new T.Vector3(-(c.driverSide||-1)*.35,0,-.15));};
G.doorPoint=function(c,side,d=1.9){return{x:c.x+Math.cos(c.yaw)*side*d+Math.sin(c.yaw)*.05,z:c.z+Math.sin(c.yaw)*side*d-Math.cos(c.yaw)*.05};};
G.interact=function(){if(this.action)return;const p=this.player,c=this.vehicle||this.cars.filter(c=>Math.abs(c.speed)<2&&c.health>0).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];if(!c||!this.vehicle&&Math.hypot(c.x-p.x,c.z-p.z)>=4.7){if(this.nearBase())this.heal();else this.toast('Approchez-vous d’une portière.');return;}
 if(Math.abs(c.speed)>2)return this.toast('Ralentissez avant de sortir.');const exiting=!!this.vehicle,localX=(p.x-c.x)*Math.cos(c.yaw)+(p.z-c.z)*Math.sin(c.yaw),preferred=exiting?(c.driverSide||-1):(localX>=0?1:-1);let side=null,point;
 for(const candidate of [preferred,-preferred]){const pos=this.doorPoint(c,candidate,exiting?2.25:1.9);if(!this.world.grid.free(pos.x,pos.z,.42)||this.carAt(pos.x,pos.z,c,.4))continue;if(!exiting&&(!this.nav.clearLine(p,pos)||Math.hypot(pos.x-p.x,pos.z-p.z)>3.8))continue;side=candidate;point=pos;break;}
 if(side===null)return this.toast('Portière bloquée. Approchez l’autre côté.');c.speed=0;c.traffic=false;if(!exiting)c.driverSide=side;const seat=this.seatPoint(c);this.action={kind:exiting?'exit':'enter',car:c,side,from:{x:p.x,y:p.y,z:p.z},point,seat:{x:seat.x,y:seat.y,z:seat.z},time:0,duration:1.45};p.armed=false;p.aim=false;p.reload=0;p.melee=0;p.vx=p.vz=0;this.input.clear();this.actor.root.visible=true;this.audio.start();};
G.releaseCrew=function(c){let i=0;for(const a of this.allies){if(a.health<=0)continue;let done=false;for(const side of [-1,1])for(const offset of [0,1.5,-1.5,3,-3]){if(done)continue;const pos=this.doorPoint(c,side,2.6+i*.25);pos.x+=Math.sin(c.yaw)*offset;pos.z-=Math.cos(c.yaw)*offset;if(this.world.grid.free(pos.x,pos.z,.4)&&!this.carAt(pos.x,pos.z,null,.35)){a.x=pos.x;a.z=pos.z;a.path=null;a.pathAt=0;done=true;}}i++;}};
G.updateAction=function(dt){const a=this.action,p=this.player;if(!a)return;p.invincible=Math.max(0,p.invincible-dt);p.vy=0;a.time+=dt;const q=Math.min(1,a.time/a.duration);let info={};
 if(a.kind==='enter'||a.kind==='exit'){const c=a.car,door=c.model.doors.find(d=>d.side===-a.side);door.hinge.rotation.y=-door.side*Math.sin(Math.PI*q)*1.15;this.animateCar(c,dt);const enter=a.kind==='enter',blend=enter?ease((q-.32)/.55):1-ease((q-.18)/.65);let position;
 if(enter&&q<.32){const k=ease(q/.32);position={x:lerp(a.from.x,a.point.x,k),z:lerp(a.from.z,a.point.z,k)};}else{position={x:lerp(a.point.x,a.seat.x,blend),z:lerp(a.point.z,a.seat.z,blend)};}
 p.x=position.x;p.z=position.z;p.y=0;p.yaw=M.angle(p.yaw,c.yaw,9,dt);info={enter:true,enterProgress:blend};
 if(q>=1){door.hinge.rotation.y=0;if(enter){this.vehicle=c;p.x=c.x;p.z=c.z;this.cam.yaw=c.yaw;this.cam.pitch=.2;}else{this.vehicle=null;this.releaseCrew(c);p.x=a.point.x;p.z=a.point.z;p.y=this.world.groundHeight(p.x,p.z);}this.action=null;this.input.clear();this.save();}
 }else if(a.kind==='revive'){info={revive:true};p.yaw=Math.atan2(a.target.x-p.x,-(a.target.z-p.z));if(a.target.downTime<=0){this.action=null;return;}if(q>=1){a.target.health=45;a.target.downTime=0;a.target.path=null;this.action=null;this.toast('Équipier relevé. Ravitaillez-vous pour soigner votre équipe.');this.save();}}
 else if(a.kind==='recover'){info={dead:true};if(q>=1){this.action=null;p.invincible=0;originalHurt.call(this,1000);this.actor.animator.death=0;return;}}
 M.animateCharacter(this.actor,0,dt,this.t,false,false,0,0,info);this.actor.root.position.set(p.x,p.y,p.z);this.actor.root.rotation.y=Math.PI-p.yaw;this.audio.tick(0,false);
};
const originalUpdate=G.updatePlayer;
G.updatePlayer=function(u,dt){if(this.action){this.updateAction(dt);return;}const p=this.player;p.lastVertical=p.vy;originalUpdate.call(this,u,dt);
 if(p.melee>0&&!p.meleeApplied&&p.melee<=.40){p.meleeApplied=true;const e=this.enemies.filter(e=>e.health>0&&Math.hypot(e.x-p.x,e.z-p.z)<2.1&&!this.blocked(p,e)).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];if(e)this.damageEnemy(e,p.combo%3===0?48:32);this.audio.noise(.08,.17);}
 if(this.vehicle){const seat=this.seatPoint(this.vehicle);this.actor.root.visible=true;this.actor.root.position.copy(seat);this.actor.root.rotation.y=Math.PI-this.vehicle.yaw;M.animateCharacter(this.actor,0,dt,this.t,false,false,0,0,{seated:true,steer:this.vehicle.steer});}
 if(this.actor.animator?.events.some(e=>e==='stepL'||e==='stepR')&&!this.vehicle)this.audio.tone(75+Math.random()*20,.055,.045,'triangle');
};
const originalCar=G.animateCar;G.animateCar=function(c,dt,brake=0){originalCar.call(this,c,dt,brake);if(c.model.steeringWheel)c.model.steeringWheel.rotation.z=-c.steer*1.8;};
G.melee=function(){const p=this.player;if(this.action||this.vehicle||p.melee>0||p.reload>0)return;p.combo=(p.combo||0)+1;p.melee=.62;p.meleeApplied=false;p.armed=false;const e=this.enemies.find(e=>e.health>0&&Math.hypot(e.x-p.x,e.z-p.z)<2.3);if(e)p.yaw=Math.atan2(e.x-p.x,-(e.z-p.z));};
const originalFire=G.fire;G.fire=function(){if(this.action||this.player.melee>0)return;this.actor.root.position.set(this.player.x,this.player.y,this.player.z);this.actor.root.rotation.y=Math.PI-this.player.yaw;this.actor.root.updateMatrixWorld(true);originalFire.call(this);};
const originalReload=G.reload;G.reload=function(){if(this.action||this.player.melee>0)return;originalReload.call(this);if(this.player.reload>0)this.player.armed=true;};
const originalHurt=G.hurt;G.hurt=function(n){if(this.action?.kind==='recover'||this.player.invincible>0)return;if(this.action?.kind==='revive')this.action=null;if(this.player.health<=n){if(this.action?.car){for(const d of this.action.car.model.doors)d.hinge.rotation.y=0;}if(this.vehicle)this.vehicle.speed=0;this.player.health=0;this.damageTime=.6;this.action={kind:'recover',time:0,duration:2.3};this.actor.root.visible=true;return;}originalHurt.call(this,n);};
const originalRecruit=G.recruit;G.recruit=function(){if(this.action)return;const a=this.allies.find(a=>a.health<=0&&a.downTime>0&&Math.hypot(a.x-this.player.x,a.z-this.player.z)<2.6);if(a&&!this.vehicle){this.action={kind:'revive',target:a,time:0,duration:2.6};this.input.clear();this.toast('Réanimation… restez à couvert.');return;}originalRecruit.call(this);};
const originalHeal=G.heal;G.heal=function(){if(this.action)return;const need=this.allies.some(a=>a.health<100),before=this.cash;if(need&&this.nearBase()&&this.cash>=60){this.cash-=60;this.player.health=100;this.player.ammo=Math.max(120,this.player.ammo);if(this.vehicle)this.vehicle.health=100;for(const a of this.allies){a.health=100;a.downTime=0;}this.toast('Équipe soignée et ravitaillée : 60 €.');this.save();return;}originalHeal.call(this);};
G.moveAgent=function(a,target,speed,dt){if(this.aiFrame!==this.t){this.aiFrame=this.t;this.nav.budget=2;}const dir=this.nav.direction(a,target,this.t),len=Math.hypot(dir.x,dir.z);if(len<.05){a.vx=a.vz=0;return;}let dx=dir.x/len*speed*dt,dz=dir.z/len*speed*dt;const ox=a.x,oz=a.z;
 const others=[...this.allies,...this.enemies.filter(e=>e.health>0)];for(const other of others){if(other===a)continue;const x=a.x-other.x,z=a.z-other.z,d=Math.hypot(x,z);if(d>0&&d<.75){dx+=x/d*(.75-d)*dt*2;dz+=z/d*(.75-d)*dt*2;}}
 this.world.grid.move(a,dx,dz,.34);if(this.carAt(a.x,a.z,this.vehicle,.30)){a.x=ox;a.z=oz;a.pathAt=0;}a.vx=(a.x-ox)/dt;a.vz=(a.z-oz)/dt;a.y=this.world.groundHeight(a.x,a.z);
};
G.hurtAlly=function(a,n){if(a.health<=0)return;a.health=Math.max(0,a.health-n);a.hit=.3;if(a.health===0){a.downTime=60;a.path=null;this.toast('Équipier à terre. B / ↑ à proximité pour le relever (60 s).');}};
G.updateEnemies=function(dt){const p=this.player;for(const e of this.enemies){const rig=e.actor;if(e.health<=0){e.dead=Math.max(0,e.dead-dt);M.animateCharacter(rig,0,dt,this.t,false,false,0,0,{dead:true});rig.root.visible=e.dead>0;continue;}const dist=Math.hypot(e.x-p.x,e.z-p.z);if(dist>100&&!e.raid)continue;e.hit=Math.max(0,(e.hit||0)-dt);e.cooldown-=dt;
 const candidates=[p,...this.allies.filter(a=>a.health>0&&!this.vehicle)],target=candidates.filter(a=>Math.hypot(a.x-e.x,a.z-e.z)<34).sort((a,b)=>Math.hypot(a.x-e.x,a.z-e.z)-Math.hypot(b.x-e.x,b.z-e.z))[0];let active=!!target;
 e.vx=e.vz=0;if(target){const dx=target.x-e.x,dz=target.z-e.z,d=Math.hypot(dx,dz);e.yaw=Math.atan2(dx,-dz);if(d>16||this.blocked(e,target))this.moveAgent(e,target,2.4,dt);else if(d<5){this.moveAgent(e,{x:e.x-dx/(d||1)*3,z:e.z-dz/(d||1)*3},1.5,dt);}
 if(e.cooldown<=0&&!this.blocked(e,target)&&this.action?.kind!=='recover'){e.cooldown=1.6+this.rng();e.recoil=.18;this.tracer(new T.Vector3(e.x,1.3+(e.y||0),e.z),new T.Vector3(target.x,1.1+(target.y||0),target.z),'#d59b83');if(target===p)this.hurt(this.vehicle?3:7);else this.hurtAlly(target,11);this.audio.tone(90,.06,.04,'sawtooth');}}
 else if(e.raid)this.moveAgent(e,this.sectors[e.home],2.4,dt);
 e.recoil=Math.max(0,(e.recoil||0)-dt);rig.root.position.set(e.x,e.y||0,e.z);rig.root.rotation.set(0,Math.PI-e.yaw,0);M.animateCharacter(rig,Math.hypot(e.vx,e.vz),dt,this.t,true,active,0,e.hit,this.animInfo(e,{pitch:0,recoil:e.recoil/.18}));}
};
G.updateAllies=function(dt){const p=this.player;for(let i=this.allies.length-1;i>=0;i--){const a=this.allies[i],rig=a.actor;a.cooldown-=dt;a.hit=Math.max(0,(a.hit||0)-dt);if(a.health<=0){a.downTime=Math.max(0,(a.downTime||0)-dt);M.animateCharacter(rig,0,dt,this.t,false,false,0,0,{down:true});rig.root.visible=true;if(a.downTime<=0){M.disposeRig(rig);this.allies.splice(i,1);this.toast('Un équipier a été perdu. Recrutement disponible aux Forges.');}continue;}
 if(this.vehicle){a.x=p.x;a.z=p.z;rig.root.visible=false;continue;}rig.root.visible=true;const side=i%2===0?1:-1,back=1.8+Math.floor(i/2)*1.5,tx=p.x+Math.cos(p.yaw)*side*1.45-Math.sin(p.yaw)*back,tz=p.z+Math.sin(p.yaw)*side*1.45+Math.cos(p.yaw)*back,d=Math.hypot(tx-a.x,tz-a.z);a.vx=a.vz=0;
 if(d>1.0){this.moveAgent(a,{x:tx,z:tz},d>6?5.9:2.9,dt);if(Math.hypot(a.vx,a.vz)>.05)a.yaw=M.angle(a.yaw,Math.atan2(a.vx,-a.vz),10,dt);}
 const target=this.enemies.filter(e=>e.health>0&&Math.hypot(e.x-a.x,e.z-a.z)<23&&!this.blocked(a,e)).sort((x,y)=>Math.hypot(x.x-a.x,x.z-a.z)-Math.hypot(y.x-a.x,y.z-a.z))[0];if(target){a.yaw=Math.atan2(target.x-a.x,-(target.z-a.z));if(a.cooldown<=0){a.cooldown=1.15;a.recoil=.18;this.damageEnemy(target,14);this.tracer(new T.Vector3(a.x,1.3+(a.y||0),a.z),new T.Vector3(target.x,1.2+(target.y||0),target.z),'#a4bfb5');}}
 a.recoil=Math.max(0,(a.recoil||0)-dt);rig.root.position.set(a.x,a.y||0,a.z);rig.root.rotation.set(0,Math.PI-a.yaw,0);M.animateCharacter(rig,Math.hypot(a.vx,a.vz),dt,this.t,!!target,!!target,0,a.hit,this.animInfo(a,{pitch:0,recoil:a.recoil/.18}));}
};
const originalHandle=G.handle;G.handle=function(u){if(this.action)u={...u,edges:new Set([...u.edges].filter(a=>['pause','map','missions'].includes(a)))};originalHandle.call(this,u);};
const originalCamera=G.updateCamera;G.updateCamera=function(dt){if(this.reduceShake)this.cam.kick=0;originalCamera.call(this,dt);};
const originalStrategy=G.strategy;G.strategy=function(dt){if(this.action){const saved=this.player.y;this.player.y=10;originalStrategy.call(this,dt);this.player.y=saved;}else originalStrategy.call(this,dt);};
})(Marlon);
