(function(M){
'use strict';const T=THREE,vec=()=>new T.Vector3;
const SAVE='marlon.rebuild.save.v2';
class Audio{
 constructor(){this.enabled=true;this.ctx=null;}
 start(){if(!this.enabled)return;try{if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext);this.master=this.ctx.createGain();this.master.gain.value=.2;this.master.connect(this.ctx.destination);this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.engineGain=this.ctx.createGain();this.engineGain.gain.value=0;this.engine.connect(this.engineGain).connect(this.master);this.engine.start();}this.ctx.resume();}catch{}}
 tone(f=300,d=.1,v=.3,type='sine'){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*.4),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(this.master);o.start();o.stop(t+d);}
 noise(d=.12,v=.35){if(!this.ctx||!this.enabled)return;const n=Math.floor(this.ctx.sampleRate*d),buf=this.ctx.createBuffer(1,n,this.ctx.sampleRate),a=buf.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/n,3);const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=buf;g.gain.value=v;s.connect(g).connect(this.master);s.start();}
 tick(speed,driving){if(!this.ctx)return;this.engine.frequency.setTargetAtTime(35+Math.abs(speed)*3.5,this.ctx.currentTime,.1);this.engineGain.gain.setTargetAtTime(this.enabled&&driving?.08:0,this.ctx.currentTime,.1);}
}
class Game{
 constructor(renderer,scene,camera){this.renderer=renderer;this.scene=scene;this.camera=camera;this.input=new M.Input(renderer.domElement);this.audio=new Audio;this.world=new M.World(scene);this.mode='front';this.t=0;this.wallTime=0;this.step=1/60;this.acc=0;this.uiTimer=0;this.saveTimer=0;this.incomeTimer=0;this.raidTimer=160;this.victoryTimer=0;this.raid=null;this.operation=null;this.waypoint=null;this.selected=9;this.trace=[];this.hitTime=0;this.damageTime=0;this.enemies=[];this.allies=[];this.cars=[];this.traffic=[];this.sectors=M.territories();this.cam={yaw:0,pitch:.22,distance:6.5,target:new T.Vector3(-225,1.4,250),lookUntil:0,actual:6.5,kick:0};this.rng=M.rng(121);
 this.player={x:-225,y:0,z:250,vx:0,vz:0,vy:0,yaw:0,health:100,mag:24,ammo:120,armed:false,aim:false,melee:0,fireCd:0,reload:0,invincible:0};this.actor=M.character();scene.add(this.actor.root);this.vehicle=null;this.cash=900;this.rep=0;this.completed=[];this.won=false;
 this.load();this.populate();for(let i=0;i<(this.savedSquad||0);i++)this.addAlly();this.actor.root.position.set(this.player.x,0,this.player.z);this.actor.root.rotation.y=Math.PI-this.player.yaw;this.lastInput=this.input.poll();this.updateCamera(1);this.ui=null;
 }
 load(){let raw;try{raw=localStorage.getItem(SAVE);}catch{}const s=M.parseSave(raw);this.hasSave=!!s;if(!s)return;Object.assign(this.player,{x:s.x,z:s.z,yaw:s.yaw,health:s.health,mag:s.mag,ammo:s.ammo});if(!this.world.grid.free(s.x,s.z,.5)){this.player.x=-225;this.player.z=250;}this.cash=s.cash;this.rep=s.rep;this.completed=s.completed;this.won=s.won;this.savedSquad=s.squad;this.cam.yaw=this.player.yaw;for(const t of this.sectors){t.owner=s.owned.includes(t.id)?'player':t.id%3===0?'cendre':'onyx';t.level=s.levels[t.id]||0;}this.cam.target.set(this.player.x,1.4,this.player.z);}
 save(){const p=this.player,s={version:2,cash:this.cash,rep:this.rep,ammo:p.ammo,mag:p.mag,health:p.health,x:p.x,z:p.z,yaw:p.yaw,owned:this.sectors.filter(t=>t.owner==='player').map(t=>t.id),levels:Object.fromEntries(this.sectors.map(t=>[t.id,t.level])),completed:this.completed,squad:this.allies.length,won:this.won};try{localStorage.setItem(SAVE,JSON.stringify(s));this.hasSave=true;return true;}catch{this.toast('Sauvegarde indisponible : le navigateur bloque le stockage.');return false;}}
 setMode(mode){this.mode=mode;this.input.clear();if(mode!=='play'){this.audio.tick(0,false);if(document.pointerLockElement)document.exitPointerLock();}this.ui?.renderMode(mode);}
 start(){this.setMode('play');this.audio.start();this.cam.target.set(this.player.x,1.4,this.player.z);this.updateCamera(1);this.toast(this.hasSave?'Progression reprise. M : carte stratégique.':'Bienvenue aux Forges. B : recruter un équipier pour 200 €.');}
 toast(text){this.ui?.toast(text);}
 reset(){try{localStorage.removeItem(SAVE);}catch{}location.reload();}
 populate(){
 const palette=['#294c59','#716656','#6d3030','#b2b0a1','#20292e','#546552'];
 this.addCar(-219,250,Math.PI/2,'coupe','#244c5c','Vesper GT');this.addCar(-232,255,Math.PI/2,'suv','#4c5052','Sentinel X');
 for(let i=0;i<26;i++){const x=-250+(i%11)*50,z=-280+Math.floor(i/11)*200+(i%3)*15;this.addCar(x+5.8,z,0,i%4===0?'van':i%3===0?'suv':'sedan',palette[i%6],i%4===0?'Cargo 90':i%3===0?'Sentinel X':'Regent S');}
 for(let i=0;i<6;i++){const x=-200+i*50,z=-150;const c=this.addCar(x+3,z,0,'sedan',palette[(i+3)%6],'Regent S');c.traffic=true;c.path=[{x:x+3,z:-253},{x:x+47,z:-253},{x:x+47,z:247},{x:x+3,z:247}];c.next=0;this.traffic.push(c);}
 for(const t of this.sectors)if(t.owner!=='player')this.spawnGuards(t);
 }
 addCar(x,z,yaw,kind,color,name){const model=M.carModel(kind,color);model.root.position.set(x,0,z);model.root.rotation.y=Math.PI-yaw;this.scene.add(model.root);const c={x,z,y:0,yaw,speed:0,steer:0,health:100,model,name,traffic:false};this.cars.push(c);return c;}
 spawnGuards(t,raid=false){for(let i=0;i<3;i++){const a=M.character(raid?'#624c38':t.owner==='cendre'?'#634643':'#303d50',true);const e={x:t.x+(i-1)*3,y:0,z:t.z+(raid?28:4),yaw:Math.PI,health:80,home:t.id,actor:a,cooldown:1+i*.6,dead:0,raid,hit:0};a.root.position.set(e.x,0,e.z);this.scene.add(a.root);this.enemies.push(e);}}
 territory(x=this.player.x,z=this.player.z){return this.sectors[M.clamp(Math.floor((z+300)/200),0,2)*4+M.clamp(Math.floor((x+300)/150),0,3)];}
 nearBase(){return Math.hypot(this.player.x+225,this.player.z-265)<34;}
 addAlly(){const a=M.character('#385a53');this.scene.add(a.root);const i=this.allies.length;const x=this.player.x+(i%2?2:-2),z=this.player.z+2;this.allies.push({x,y:0,z,yaw:0,actor:a,cooldown:0,health:100});a.root.position.set(x,0,z);}
 recruit(){if(this.vehicle)return this.toast('Sortez du véhicule pour recruter.');if(!this.nearBase())return this.toast('Recrutement disponible à la planque des Forges.');if(this.allies.length>=3)return this.toast('Équipe complète : trois équipiers.');if(this.cash<200)return this.toast('Recrutement : 200 € nécessaires.');this.cash-=200;this.addAlly();this.toast('Équipier recruté. Il vous suit et couvre vos conquêtes.');this.save();}
 heal(){if(this.nearBase()){const cost=this.player.health<100||this.player.ammo<120||this.vehicle?.health<100?60:0;if(this.cash<cost)return this.toast('Ravitaillement : 60 € nécessaires.');this.cash-=cost;this.player.health=100;this.player.ammo=Math.max(this.player.ammo,120);if(this.vehicle)this.vehicle.health=100;this.toast('Soins, munitions et réparation effectués.');this.save();}else this.toast('Rejoignez le garage des Forges pour vous ravitailler.');}
 interact(){const p=this.player;if(this.vehicle){const c=this.vehicle;if(Math.abs(c.speed)>2)return this.toast('Ralentissez avant de sortir.');let exit=null;for(const [dx,dz]of [[2.3,0],[-2.3,0],[0,3.6],[0,-3.6]]){const x=c.x+Math.cos(c.yaw)*dx+Math.sin(c.yaw)*dz,z=c.z+Math.sin(c.yaw)*dx-Math.cos(c.yaw)*dz;if(this.world.grid.free(x,z,.45)&&!this.carAt(x,z,c,.45)){exit={x,z};break;}}if(!exit)return this.toast('Sortie bloquée. Déplacez le véhicule.');p.x=exit.x;p.z=exit.z;p.y=0;this.vehicle=null;c.speed=0;this.actor.root.visible=true;this.cam.lookUntil=this.t+1;this.toast('À pied. G : arme · L2 / clic droit : viser.');return;}
 const c=this.cars.filter(c=>Math.abs(c.speed)<2&&c.health>0).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];if(c&&Math.hypot(c.x-p.x,c.z-p.z)<4.7){this.vehicle=c;c.traffic=false;p.armed=false;p.aim=false;p.reload=0;p.vx=p.vz=0;p.x=c.x;p.z=c.z;this.actor.root.visible=false;this.cam.yaw=c.yaw;this.cam.pitch=.2;this.input.clear();this.audio.start();this.toast(c.name+' — R2 : accélérer · L2 : freiner / reculer · R1 : frein à main.');}else if(this.nearBase())this.heal();else this.toast('Approchez-vous d’un véhicule à l’arrêt.');}
 carAt(x,z,ignore=null,r=.4){for(const c of this.cars){if(c===ignore)continue;const dx=x-c.x,dz=z-c.z,localX=dx*Math.cos(c.yaw)+dz*Math.sin(c.yaw),localZ=dx*Math.sin(c.yaw)-dz*Math.cos(c.yaw);if(Math.abs(localX)<1.1+r&&Math.abs(localZ)<2.35+r)return c;}return null;}
 rayCars(o,d,max,ignore=null){let result={distance:max,car:null};for(const c of this.cars){if(c===ignore)continue;const co=Math.cos(c.yaw),si=Math.sin(c.yaw),x=o.x-c.x,z=o.z-c.z;const a={x:x*co+z*si,y:o.y,z:x*si-z*co},b={x:d.x*co+d.z*si,y:d.y,z:d.x*si-d.z*co};const hit=M.rayBox(a,b,{minx:-1.06,maxx:1.06,miny:.32,maxy:1.58,minz:-2.32,maxz:2.32},max);if(hit<result.distance)result={distance:hit,car:c};}return result;}
 blocked(from,to){const d=new T.Vector3(to.x-from.x,(to.y||1.2)-(from.y||1.2),to.z-from.z),len=d.length();if(len<.01)return false;d.divideScalar(len);const origin={x:from.x,y:from.y||1.2,z:from.z};return this.world.grid.ray(origin,d,len)<len-.1||this.rayCars(origin,d,len,this.vehicle).distance<len-.1;}
 handle(u){if(u.edges.has('pause')){if(this.mode==='front')this.start();else this.setMode(this.mode==='play'?'pause':this.mode==='settings'?this.ui.returnTo:'play');return;}
 if(this.mode!=='play'){if(this.input.last==='pad')this.ui?.padMenu(u);return;}
 if(u.edges.has('map')){this.setMode('map');return;}if(u.edges.has('missions')){this.setMode('missions');return;}
 if(u.edges.has('interact'))this.interact();if(u.edges.has('recruit'))this.recruit();if(u.edges.has('heal'))this.heal();if(u.edges.has('weapon')&&!this.vehicle)this.player.armed=!this.player.armed;
 if(u.edges.has('recenter')){this.cam.yaw=this.vehicle?.yaw??this.player.yaw;this.cam.pitch=.2;this.cam.lookUntil=this.t+1;}
 if(u.edges.has('reload'))this.reload();if(u.edges.has('melee')&&!this.vehicle)this.melee();if(u.edges.has('jump')&&!this.vehicle&&this.player.y<=this.world.groundHeight(this.player.x,this.player.z)+.001)this.player.vy=5.3;
 }
 reload(){const p=this.player;if(p.reload>0||p.mag===24||p.ammo<=0||this.vehicle)return;p.reload=1.45;this.audio.tone(260,.12,.1,'square');}
 melee(){const p=this.player;if(p.melee>0)return;p.melee=.45;this.audio.noise(.08,.13);let nearest=this.enemies.filter(e=>e.health>0&&Math.hypot(e.x-p.x,e.z-p.z)<2.2&&!this.blocked(p,e)).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];if(nearest){p.yaw=Math.atan2(nearest.x-p.x,-(nearest.z-p.z));this.damageEnemy(nearest,40);}}
 damageEnemy(e,d){if(e.health<=0)return;e.health-=d;e.hit=.3;this.hitTime=.15;this.input.vibrate(.25);this.audio.noise(.09,.11);if(e.health<=0){e.dead=8;this.cash+=25;this.rep+=5;}}
 tracer(a,b,color='#f4d8a0'){const geo=new T.BufferGeometry().setFromPoints([a.clone(),b.clone()]);const line=new T.Line(geo,new T.LineBasicMaterial({color,transparent:true,opacity:.8}));this.scene.add(line);this.trace.push({line,ttl:.055});}
 fire(){const p=this.player;if(this.vehicle||p.fireCd>0||p.reload>0)return;p.armed=true;if(p.mag<=0){this.reload();p.fireCd=.25;return;}p.mag--;p.fireCd=.18;this.actor.flash.visible=true;this.cam.kick+=.015;this.audio.noise(.14,.5);this.audio.tone(80,.13,.3,'triangle');this.input.vibrate(.15,45);
 const origin=this.camera.position.clone(),dir=new T.Vector3;this.camera.getWorldDirection(dir);let range=Math.min(this.world.grid.ray(origin,dir,85),this.rayCars(origin,dir,85).distance),target=null,hitDist=range;
 // Aim assist is a small visible cone and always respects world occlusion.
 if(this.input.last==='pad'&&p.aim){let best=.986;for(const e of this.enemies){if(e.health<=0)continue;const v=new T.Vector3(e.x,1.25,e.z).sub(origin),dist=v.length(),dot=v.normalize().dot(dir);if(dist<65&&dot>best&&this.world.grid.ray(origin,v,dist)>=dist-.1){dir.copy(v);best=dot;}}range=Math.min(this.world.grid.ray(origin,dir,85),this.rayCars(origin,dir,85).distance);hitDist=range;}
 const ray=new T.Ray(origin,dir),pt=vec();for(const e of this.enemies){if(e.health<=0)continue;for(const [y,r]of [[.75,.32],[1.23,.34],[1.65,.16]]){if(ray.intersectSphere(new T.Sphere(new T.Vector3(e.x,y,e.z),r),pt)){const d=origin.distanceTo(pt);if(d<hitDist){target=e;hitDist=d;}}}}
 // The camera can see around a corner; the muzzle cannot shoot through it.
 const end=origin.clone().addScaledVector(dir,hitDist),muzzle=this.actor.flash.getWorldPosition(new T.Vector3()),shot=end.clone().sub(muzzle),length=shot.length();shot.normalize();const wall=this.world.grid.ray(muzzle,shot,length),carHit=this.rayCars(muzzle,shot,length+.25),obstruction=Math.min(wall,carHit.distance);if(carHit.car&&carHit.distance<=wall+.2&&carHit.distance<=length+.2){carHit.car.health=Math.max(0,carHit.car.health-8);this.audio.noise(.06,.12);}if(obstruction<length-.2){end.copy(muzzle).addScaledVector(shot,obstruction);target=null;}if(target)this.damageEnemy(target,27);this.tracer(muzzle,end);
 }
 hurt(n){const p=this.player;if(p.invincible>0)return;p.health=Math.max(0,p.health-n);this.damageTime=.55;this.input.vibrate(.4,100);if(p.health<=0){const loss=Math.min(180,this.cash);this.cash-=loss;if(this.vehicle){this.vehicle.speed=0;this.vehicle=null;}Object.assign(p,{x:-225,z:250,y:0,vx:0,vz:0,vy:0,health:100,invincible:8,armed:false,aim:false,reload:0});this.actor.root.visible=true;this.cam.target.set(p.x,1.4,p.z);this.cam.yaw=0;this.operation=null;for(const a of this.allies){a.x=p.x+2;a.z=p.z+2;}this.toast('Repli à la planque. Frais de secours : '+loss+' €.');this.save();}}
 updatePlayer(u,dt){const p=this.player;p.invincible=Math.max(0,p.invincible-dt);p.fireCd=Math.max(0,p.fireCd-dt);p.melee=Math.max(0,p.melee-dt);this.actor.flash.visible=p.fireCd>.145;
 if(p.reload>0){p.reload-=dt;if(p.reload<=0){const n=Math.min(24-p.mag,p.ammo);p.mag+=n;p.ammo-=n;this.audio.tone(420,.08,.1);}}
 const sens=this.input.sensitivity*(p.aim?.55:1);const lx=u.lookX*2.5*dt+u.mouseX*.0022,ly=u.lookY*1.7*dt+u.mouseY*.0022;if(Math.abs(lx)+Math.abs(ly)>.0001){this.cam.yaw+=lx*sens;this.cam.pitch=M.clamp(this.cam.pitch+ly*sens*(this.input.invert?-1:1),-.36,.93);this.cam.lookUntil=this.t+2.5;}
 if(this.vehicle){const c=this.vehicle;M.drive(c,c.health<=0?{...u,gas:0,brake:0,handbrake:true}:u,dt);if(c.health<=0){c.speed=M.damp(c.speed,0,4,dt);c.dx=Math.sin(c.yaw)*c.speed*dt;c.dz=-Math.cos(c.yaw)*c.speed*dt;}
 const speed=Math.abs(c.speed),oldx=c.x,oldz=c.z;const hit=this.world.grid.move(c,c.dx,c.dz,2.25);const other=this.carAt(c.x,c.z,c,1.25);if(other){c.x=oldx;c.z=oldz;}
 if(hit||other){c.speed*=-.18;if(speed>5){c.health=Math.max(0,c.health-speed*.22);this.hurt(speed*.13);this.audio.noise(.12,.2);this.input.vibrate(.35,100);}}
 p.x=c.x;p.z=c.z;p.y=0;p.yaw=c.yaw;p.aim=false;this.animateCar(c,dt,u.brake);if(this.t>this.cam.lookUntil&&speed>1.5)this.cam.yaw=M.angle(this.cam.yaw,c.yaw,2.1,dt);
 for(const e of this.enemies)if(e.health>0&&Math.hypot(e.x-c.x,e.z-c.z)<2.4&&speed>4){this.damageEnemy(e,speed*3);c.speed*=.8;}
 }else{p.aim=!!u.aim;if(p.aim)p.armed=true;const v=M.moveVector(u.x,u.forward,this.cam.yaw),speed=p.aim?2.1:u.sprint?6.7:3.5;p.vx=M.damp(p.vx,v.x*speed,16,dt);p.vz=M.damp(p.vz,v.z*speed,16,dt);const ox=p.x,oz=p.z;this.world.grid.move(p,p.vx*dt,p.vz*dt,.34);if(this.carAt(p.x,p.z,null,.3)){p.x=ox;p.z=oz;p.vx=p.vz=0;}p.vy-=15*dt;p.y+=p.vy*dt;const ground=this.world.groundHeight(p.x,p.z);if(p.y<ground){p.y=ground;p.vy=0;}
 if(p.aim)p.yaw=this.cam.yaw;else if(Math.hypot(p.vx,p.vz)>.1)p.yaw=M.angle(p.yaw,Math.atan2(p.vx,-p.vz),16,dt);
 if(u.fire)this.fire();M.animateCharacter(this.actor,Math.hypot(p.vx,p.vz),dt,this.t,p.armed,p.aim,p.melee,this.damageTime,{...this.animInfo(p),speed:Math.hypot(p.x-ox,p.z-oz)/dt});this.actor.root.position.set(p.x,p.y,p.z);this.actor.root.rotation.y=Math.PI-p.yaw;
 }this.audio.tick(this.vehicle?.speed||0,!!this.vehicle);}
 animateCar(c,dt,brake=0){const a=c.model;a.root.position.set(c.x,0,c.z);a.root.rotation.y=Math.PI-c.yaw;a.body.rotation.z=M.damp(a.body.rotation.z,-c.steer*c.speed*.006,6,dt);a.body.rotation.x=M.damp(a.body.rotation.x,brake*.025,5,dt);a.body.position.y=Math.sin(this.t*18)*Math.min(.012,Math.abs(c.speed)*.0008);for(const w of a.wheels){w.spin.rotation.x+=c.speed*dt/.38;if(w.front)w.pivot.rotation.y=-c.steer;}a.tail.emissiveIntensity=brake>.1?3:.65;}
 updateTraffic(dt){for(const c of this.traffic){if(!c.traffic||c===this.vehicle)continue;const t=c.path[c.next],dx=t.x-c.x,dz=t.z-c.z,dist=Math.hypot(dx,dz);if(dist<5)c.next=(c.next+1)%c.path.length;const target=Math.atan2(dx,-dz);c.yaw=M.angle(c.yaw,target,2.4,dt);let blocked=false;const fx=c.x+Math.sin(c.yaw)*7,fz=c.z-Math.cos(c.yaw)*7;if(Math.hypot(fx-this.player.x,fz-this.player.z)<5||this.carAt(fx,fz,c,1))blocked=true;c.speed=M.damp(c.speed,blocked?0:8,blocked?5:1,dt);const before={x:c.x,z:c.z};if(this.world.grid.move(c,Math.sin(c.yaw)*c.speed*dt,-Math.cos(c.yaw)*c.speed*dt,2.2)){c.x=before.x;c.z=before.z;c.speed=0;}if(Math.hypot(c.x-this.player.x,c.z-this.player.z)<2.6&&!this.vehicle){c.x=before.x;c.z=before.z;c.speed=0;}this.animateCar(c,dt,blocked?1:0);}}
 updateEnemies(dt){const p=this.player;for(const e of this.enemies){const a=e.actor;if(e.health<=0){e.dead=Math.max(0,e.dead-dt);a.root.rotation.z=M.damp(a.root.rotation.z,1.5,9,dt);a.root.position.y=.15;if(e.dead===0)a.root.visible=false;continue;}const dist=Math.hypot(e.x-p.x,e.z-p.z);if(dist>100&&!e.raid){a.root.visible=false;continue;}a.root.visible=true;e.hit=Math.max(0,e.hit-dt);e.cooldown-=dt;const hostile=dist<30||e.raid;let speed=0;if(hostile){const target=e.raid&&dist>30?this.sectors[e.home]:p;const dx=target.x-e.x,dz=target.z-e.z,d=Math.hypot(dx,dz);e.yaw=Math.atan2(dx,-dz);if(d>14||this.blocked(e,p)){speed=2.2;this.world.grid.move(e,dx/(d||1)*speed*dt,dz/(d||1)*speed*dt,.34);}else if(d<6){speed=1.5;this.world.grid.move(e,-dx/(d||1)*speed*dt,-dz/(d||1)*speed*dt,.34);}
 if(dist<34&&e.cooldown<=0&&!this.blocked(e,p)){e.cooldown=1.5+this.rng();this.tracer(new T.Vector3(e.x,1.3,e.z),new T.Vector3(p.x,1.1+p.y,p.z),'#d59b83');this.hurt(this.vehicle?3:7);this.audio.tone(90,.06,.05,'sawtooth');}}
 M.animateCharacter(a,speed,dt,this.t,true,hostile,0,e.hit);a.root.position.set(e.x,0,e.z);a.root.rotation.y=Math.PI-e.yaw;}}
 updateAllies(dt){const p=this.player;for(let i=0;i<this.allies.length;i++){const a=this.allies[i],rig=a.actor;a.cooldown-=dt;const tx=p.x+Math.cos(this.cam.yaw)*(i%2===0?2:-2),tz=p.z+2+i,dx=tx-a.x,dz=tz-a.z,d=Math.hypot(dx,dz);let speed=0;a.actor.root.visible=!this.vehicle;if(d>80&&this.world.grid.free(tx,tz,.4)){a.x=tx;a.z=tz;}else if(d>1.3&&!this.vehicle){speed=d>7?6.4:3.7;this.world.grid.move(a,dx/d*speed*dt,dz/d*speed*dt,.34);a.yaw=M.angle(a.yaw,Math.atan2(dx,-dz),8,dt);}const target=this.enemies.find(e=>e.health>0&&Math.hypot(e.x-a.x,e.z-a.z)<22&&!this.blocked(a,e));if(target&&!this.vehicle){a.yaw=Math.atan2(target.x-a.x,-(target.z-a.z));if(a.cooldown<=0){a.cooldown=1.1;this.damageEnemy(target,14);this.tracer(new T.Vector3(a.x,1.3,a.z),new T.Vector3(target.x,1.2,target.z),'#a4bfb5');}}M.animateCharacter(rig,speed,dt,this.t,!!target,!!target);rig.root.position.set(a.x,0,a.z);rig.root.rotation.y=Math.PI-a.yaw;}}
 fortify(id){const t=this.sectors[id];if(t.owner!=='player'||t.level>=3)return;const cost=120*(t.level+1);if(this.cash<cost)return this.toast('Fonds insuffisants.');this.cash-=cost;t.level++;this.save();this.toast('Défense renforcée au niveau '+t.level+'.');this.ui.renderMap();}
 strategy(dt){const p=this.player;this.captureTarget=null;for(const t of this.sectors){const near=Math.hypot(p.x-t.x,p.z-t.z)<12,eligible=M.canAttack(this.sectors,t),enemy=this.enemies.some(e=>e.health>0&&e.home===t.id&&Math.hypot(e.x-t.x,e.z-t.z)<28),team=this.allies.some(a=>a.health>0&&Math.hypot(a.x-t.x,a.z-t.z)<20);
 if(near&&eligible&&!this.vehicle){this.captureTarget=t;this.captureReason=enemy?'ÉLIMINEZ LES DÉFENSEURS':!team?'UN ÉQUIPIER EST NÉCESSAIRE':p.y>.2?'REJOIGNEZ LE SOL':'PRISE DE CONTRÔLE';if(!enemy&&team&&p.y<.2)t.capture+=dt/18;}
 if(t.capture>=1){t.owner='player';t.capture=0;this.cash+=350;this.rep+=60;this.audio.tone(740,.6,.2);this.toast(t.name+' sous votre contrôle. +350 € · +60 réputation.');if(this.operation?.type==='capture')this.completeOperation();this.save();}
 const marker=this.world.markers[t.id];marker.material.color.set(t.owner==='player'?'#84c6ae':'#d39c63');marker.core.rotation.y=this.t*.6;marker.core.position.y=2.8+Math.sin(this.t*1.7+t.id)*.15;
 }
 this.incomeTimer+=dt;if(this.incomeTimer>=120){this.incomeTimer-=120;const amount=this.sectors.filter(t=>t.owner==='player').length*75;this.cash+=amount;this.toast('Revenus des quartiers : +'+amount+' €.');this.save();}
 this.raidTimer-=dt;if(!this.raid&&this.raidTimer<=0){const owned=this.sectors.filter(t=>t.owner==='player'&&t.id!==8);if(owned.length){const t=owned[Math.floor(this.rng()*owned.length)];this.raid={id:t.id,warning:45,remaining:70,spawned:false};this.toast('Attaque annoncée sur '+t.name+' dans 45 secondes.');}this.raidTimer=170;}
 if(this.raid){const r=this.raid,t=this.sectors[r.id];r.warning-=dt;if(r.warning<=0&&!r.spawned){r.spawned=true;this.spawnGuards(t,true);this.toast('Votre quartier '+t.name+' est attaqué.');}if(r.spawned){r.remaining-=dt;const attackers=this.enemies.filter(e=>e.raid&&e.home===t.id&&e.health>0);if(!attackers.length){this.cash+=200;this.rep+=30;this.toast('Défense réussie : +200 €.');if(this.operation?.type==='defend')this.completeOperation();this.raid=null;this.save();}else if(r.remaining<=0){if(t.level>0){t.level--;this.toast('La fortification a repoussé l’attaque. Un niveau consommé.');if(this.operation?.type==='defend')this.completeOperation();}else{t.owner='cendre';t.capture=0;this.toast(t.name+' est perdu. Reprenez le quartier.');if(this.operation?.type==='defend')this.operation=null;}for(const e of attackers){e.raid=false;if(t.owner==='player'){e.health=0;e.dead=2;}}this.raid=null;this.save();}}}
 if(this.sectors.every(t=>t.owner==='player')&&!this.won){this.victoryTimer+=dt;if(this.victoryTimer>=90){this.won=true;this.save();this.setMode('victory');}}else this.victoryTimer=0;
 }
 startOperation(type){if(this.operation)return this.toast('Terminez ou abandonnez l’opération en cours.');const owned=this.sectors.filter(t=>t.owner==='player'),targets=this.sectors.filter(t=>M.canAttack(this.sectors,t));if(type==='capture'&&!targets.length)return this.toast('Aucune conquête disponible.');if(type==='patrol'&&owned.length<2)return this.toast('Contrôlez au moins deux quartiers.');if(type==='defend'&&owned.length<2)return this.toast('Conquérez un deuxième quartier pour débloquer la défense.');let ids=type==='recon'?[9,5,6]:type==='courier'?[8,11]:type==='patrol'?owned.slice(0,3).map(t=>t.id):type==='capture'?[targets[0].id]:[];
 this.operation={type,ids,index:0,remaining:type==='courier'?240:420};if(type==='defend'){this.raidTimer=5;if(this.raid)this.operation.ids=[this.raid.id];}this.setMode('play');this.toast('Opération lancée : '+M.missions[type].name+'.');}
 completeOperation(){if(!this.operation)return;const type=this.operation.type,full=M.missions[type].reward,amount=Math.floor(full*(this.completed.includes(type)?.4:1));this.cash+=amount;this.rep+=35;if(!this.completed.includes(type))this.completed.push(type);this.operation=null;this.audio.tone(640,.35,.18);this.toast('Opération réussie : +'+amount+' €.');this.save();}
 updateOperation(dt){const op=this.operation;if(!op)return;op.remaining-=dt;if(op.remaining<=0){this.toast('Opération expirée. Aucune récompense.');this.operation=null;return;}if(op.type==='capture'||op.type==='defend')return;const t=this.sectors[op.ids[op.index]];if(Math.hypot(this.player.x-t.x,this.player.z-t.z)<13&&(op.type!=='courier'||this.vehicle)){op.index++;this.audio.tone(520,.12,.15);if(op.index>=op.ids.length)this.completeOperation();else this.toast('Étape validée. Rejoignez '+this.sectors[op.ids[op.index]].name+'.');}}
 updateCamera(dt){const p=this.player,c=this.cam,car=this.vehicle,aim=p.aim&&!car;const target=new T.Vector3(p.x,p.y+(car?1.35:1.43),p.z);if(aim){target.x+=Math.cos(c.yaw)*.58;target.z+=Math.sin(c.yaw)*.58;}c.target.lerp(target,1-Math.exp(-(aim?22:car?7:18)*dt));
 // Anchor may never lag through a wall; shorten the spring arm before rendering.
 const anchor=new T.Vector3(p.x,p.y+1.4,p.z),anchorDelta=c.target.clone().sub(anchor),anchorLen=anchorDelta.length();if(anchorLen>.01&&this.world.grid.ray(anchor,anchorDelta.clone().normalize(),anchorLen,.12)<anchorLen)c.target.copy(anchor);
 const wanted=aim?2.6:car?8.5+Math.min(3,Math.abs(car.speed)*.075):6.2;c.distance=M.damp(c.distance,wanted,7,dt);c.kick=M.damp(c.kick,0,15,dt);const pitch=c.pitch+c.kick,dir=new T.Vector3(-Math.sin(c.yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(c.yaw)*Math.cos(pitch));let free=this.world.grid.ray(c.target,dir,c.distance,.27);free=Math.max(.12,free-.1);c.actual=free<c.actual?free:Math.min(free,c.actual+4.5*dt);this.camera.position.copy(c.target).addScaledVector(dir,c.actual);this.camera.position.y=Math.max(.3,this.camera.position.y);this.camera.lookAt(c.target);this.camera.fov=M.damp(this.camera.fov,aim?51:car?66+Math.min(10,Math.abs(car.speed)*.24):62,8,dt);this.camera.updateProjectionMatrix();}
 frame(realDt){const dt=Math.min(.1,Math.max(0,realDt));this.wallTime+=dt;const u=this.input.poll();this.lastInput=u;this.handle(u);if(this.mode==='play'){
 this.acc+=dt;let steps=0;while(this.acc>=this.step&&steps<6){const inp=steps===0?u:{...u,mouseX:0,mouseY:0};this.t+=this.step;this.updatePlayer(inp,this.step);this.updateTraffic(this.step);this.updateEnemies(this.step);this.updateAllies(this.step);this.strategy(this.step);this.updateOperation(this.step);this.acc-=this.step;steps++;if(this.mode!=='play'){this.acc=0;break;}}
 // Mouse motion belongs to a render frame, not a simulation tick. Preserve it if no step ran.
 if(!steps){this.input.mouse.x+=u.mouseX;this.input.mouse.y+=u.mouseY;}
 this.updateCamera(dt);this.saveTimer+=dt;if(this.saveTimer>15){this.saveTimer=0;this.save();}
 }else{this.acc=0;if(this.mode==='front'){const a=this.wallTime*.009;this.camera.position.set(-239+Math.sin(a)*4,7.8,265);this.camera.lookAt(-210,5,215);}}
 for(let i=this.trace.length-1;i>=0;i--){const t=this.trace[i];t.ttl-=dt;if(t.ttl<=0){this.scene.remove(t.line);t.line.geometry.dispose();t.line.material.dispose();this.trace.splice(i,1);}}
 this.hitTime=Math.max(0,this.hitTime-dt);this.damageTime=Math.max(0,this.damageTime-dt);this.uiTimer+=dt;if(this.uiTimer>.09){this.uiTimer=0;this.ui?.update();}if(this.sun){const p=this.mode==='front'?{x:-225,z:240}:this.player;this.sun.position.set(p.x-70,90,p.z-55);this.sun.target.position.set(p.x,0,p.z);this.sun.target.updateMatrixWorld();}
 // Cull whole detailed rigs, including their shadow passes, outside the local streets.
 for(const c of this.cars)c.model.root.visible=Math.hypot(c.x-this.camera.position.x,c.z-this.camera.position.z)<90;
 for(const e of this.enemies)e.actor.root.visible=(e.health>0||e.dead>0)&&Math.hypot(e.x-this.camera.position.x,e.z-this.camera.position.z)<80;
 this.renderer.render(this.scene,this.camera);
 }
}
M.missions={recon:{name:'Lire la ville',desc:'Repérez République, Saint-Roch et le Centre financier. Tous les moyens de transport sont autorisés.',reward:250},courier:{name:'Dernière livraison',desc:'Prenez un véhicule. Chargez aux Forges puis livrez au Terminal Sud avant la fin du temps imparti.',reward:450},capture:{name:'Étendre les frontières',desc:'Éliminez les défenseurs d’un quartier voisin. Restez dans la zone avec un équipier pendant 18 secondes.',reward:500},patrol:{name:'Tenir la rue',desc:'Patrouillez dans vos quartiers. Deux territoires contrôlés au minimum.',reward:280},defend:{name:'Personne ne passe',desc:'Une attaque arrive. Rejoignez votre quartier et repoussez les assaillants, ou appuyez-vous sur sa fortification.',reward:450}};
M.Game=Game;
})(Marlon);
