/* Sunshine 05 · Street life, neighbourhood stories and contextual interactions.
   Loaded after city-ui.js. All objectives and one-off rewards are save validated. */
(function(M){
'use strict';
const T=THREE,G=M.Game.prototype,P=M.UI.prototype,$=id=>document.getElementById(id);
const distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),clamp=M.clamp;
const BRIGHT=['#ff263c','#843aff','#a1f000','#ff8a00','#008cff','#ff00bc'];
const FACTIONS=[{name:'Les Braises',color:BRIGHT[0]},{name:'Violet Club',color:BRIGHT[1]},{name:'Acid Crew',color:BRIGHT[2]}];
const JOBS={cleanup:{title:'Coup de propre aux Docks',reward:120,detail:'Ramassez les trois sacs orange signalés, puis rapportez-les à Nora.'},courier:{title:'Le colis du quartier',reward:150,detail:'Récupérez le colis à la cour ouest et livrez-le à la cour sud.'},rescue:{title:'Un toit pour Pixel',reward:90,detail:'Approchez Pixel, rassurez-le puis ramenez-le à Nora ou adoptez-le.'}};
const HOME={x:-219,z:-222},PICKUP={x:-276,z:-166},DELIVERY={x:-168,z:-273};
const CLEAN=[{x:-235,z:-217},{x:-218,z:-234},{x:-182,z:-267}];
const list=(a,max=80)=>Array.isArray(a)?[...new Set(a.filter(v=>typeof v==='string').map(v=>v.slice(0,60)))].slice(0,max):[];
const valid=M.validCity;
M.validCity=function(value){const city=valid(value),a=value?.life||{};city.life={version:1,searched:list(a.searched,512),fed:list(a.fed,5),adopted:list(a.adopted,5),recruited:list(a.recruited,42),crewColors:Array.isArray(a.crewColors)?a.crewColors.slice(0,3).map(c=>BRIGHT.includes(c)?c:''):[],completed:list(a.completed,3).filter(k=>JOBS[k]),job:null};if(a.job&&JOBS[a.job.type])city.life.job={type:a.job.type,stage:clamp(Math.floor(Number(a.job.stage)||0),0,4),remaining:clamp(Number(a.job.remaining)||420,0,900),collected:list(a.job.collected,3).filter(k=>['0','1','2'].includes(k))};return city;};
const bandGeometry=new T.CylinderGeometry(.224,.224,.066,20,1,true),knotGeometry=new T.SphereGeometry(.034,8,6);
const bands=new Map;
function bandana(rig,color){if(rig.lifeBand)return;let mat=bands.get(color);if(!mat){mat=M.mat(color,.74);bands.set(color,mat);}const group=new T.Group;rig.head.add(group);const band=new T.Mesh(bandGeometry,mat);band.scale.z=.9;band.position.y=.108;group.add(band);const knot=new T.Mesh(knotGeometry,mat);knot.position.set(.205,.091,-.11);group.add(knot);for(const side of [-1,1]){const tail=M.round(group,.045,.14,.02,.215,.058,-.105+side*.025,mat,.013);tail.rotation.z=side*.28;}rig.lifeBand=group;}
const spawnGuards=G.spawnGuards;G.spawnGuards=function(...args){const before=this.enemies.length;spawnGuards.apply(this,args);for(const e of this.enemies.slice(before))bandana(e.actor,FACTIONS[e.home%3]?.color||BRIGHT[0]);};
M.lifePose=function(a,kind,t){if(kind==='talk'){a.ra.rotation.x=-.55-Math.sin(t*2.4)*.18;a.re.rotation.x=-1.05;a.head.rotation.y=Math.sin(t*.9)*.22;}else if(kind==='dance'){a.body.position.y+=Math.sin(t*6)*.055;a.body.rotation.z=Math.sin(t*3)*.13;a.body.rotation.y=Math.sin(t*1.5)*.23;a.la.rotation.x=-.8+Math.sin(t*3)*.65;a.ra.rotation.x=-.8-Math.sin(t*3)*.65;a.la.rotation.z=.3+Math.sin(t*3)*.17;a.ra.rotation.z=-.3+Math.sin(t*3)*.17;a.le.rotation.x=a.re.rotation.x=-.7;a.head.rotation.z=-Math.sin(t*3)*.1;}else if(kind==='phone'){a.ra.rotation.x=-.38;a.re.rotation.x=-2.12;a.head.rotation.z=-.12;}else if(kind==='sit'){a.la.rotation.x=a.ra.rotation.x=-.15;a.le.rotation.x=a.re.rotation.x=-.95;}else if(kind==='drink'){a.ra.rotation.x=-.35-Math.sin(Math.min(1,t/1.5)*Math.PI/2)*.65;a.re.rotation.x=-1.85;a.head.rotation.x=-.11;}else if(['pet','clean','search','pickup'].includes(kind)){a.body.rotation.x=.26;a.ra.rotation.x=-.8-Math.sin(t*5)*.25;a.re.rotation.x=-.4;a.la.rotation.x=-.35;}else if(kind==='wave'){a.ra.rotation.x=-2.45;a.ra.rotation.z=-.45+Math.sin(t*7)*.25;a.re.rotation.x=-.4;}};
function freeNearby(g,x,z,radius=4){if(g.world.grid.free(x,z,.4,0))return{x,z};for(let i=0;i<16;i++){const a=i*Math.PI/4,r=radius*(1+Math.floor(i/8));const p={x:x+Math.sin(a)*r,z:z+Math.cos(a)*r};if(g.world.grid.free(p.x,p.z,.4,0))return p;}return{x,z};}
function labelPlane(text,color,width=2.4){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=100;const c=canvas.getContext('2d');c.fillStyle='#101a32';c.fillRect(0,0,512,100);c.fillStyle=color;c.font='bold 38px sans-serif';c.textAlign='center';c.fillText(text,256,64);const texture=new T.CanvasTexture(canvas);texture.encoding=T.sRGBEncoding;const mesh=new T.Mesh(new T.PlaneGeometry(width,width/5.12),new T.MeshBasicMaterial({map:texture,side:T.DoubleSide}));return mesh;}
function makeMissionProp(g,id,p,type){const root=new T.Group,orange=M.mat('#ff6800'),dark=M.mat('#252e43'),yellow=M.mat('#ffdb00');root.position.set(p.x,Math.min(.55,g.world.groundHeight(p.x,p.z,0)),p.z);g.scene.add(root);if(type==='bag'){M.oval(root,orange,0,.35,0,.32,.4,.3);M.round(root,.13,.12,.13,0,.76,0,dark,.025);}else{M.round(root,.72,.55,.58,0,.3,0,orange,.055);M.round(root,.11,.56,.59,0,.3,0,yellow,.015);}const ring=M.mesh(root,new T.TorusGeometry(.7,.035,6,24),new T.MeshBasicMaterial({color:'#ffe000'}),0,.045,0);ring.rotation.x=Math.PI/2;return{id,x:p.x,z:p.z,root,type,ring};}
const init=G.initCity;
G.initCity=function(){init.call(this);this.lifePeople=[];this.strays=[];this.lifeAction=null;this.lifeClock=0;this.lifeProps=[];const keys=new Set;this.lifeInteractables=[...this.world.props,...(this.world.lifeSpots||[])].filter(o=>{const key=o.kind+':'+o.x+':'+o.z;if(keys.has(key))return false;keys.add(key);return ['bench','vending','bin','phone','mailbox','dance','hydrant'].includes(o.kind);});const s=this.city.life;
 for(let i=0;i<42;i++){const gang=i<12,faction=FACTIONS[Math.floor(i/4)%3],role=i===0?'leader':gang?'gang':'social';let p;if(gang){const centers=[HOME,{x:-229,z:-221},{x:-224,z:-232}],c=centers[Math.floor(i/4)];p=freeNearby(this,c.x+(i%4-1)*1.55,c.z+(i%2)*2);}else{const b=this.world.services[(i-12)%this.world.services.length];p=freeNearby(this,b.x+(i%2?5:-5),b.z+17.5+(i%3)*.7);}
 const actor=M.character(gang?faction.color:BRIGHT[i%BRIGHT.length]);if(gang)bandana(actor,faction.color);actor.materials.pants.color.set(i%3===0?'#073986':i%3===1?'#123047':'#1791fa').convertSRGBToLinear();this.scene.add(actor.root);const n={id:'person-'+i,x:p.x,z:p.z,y:0,yaw:gang?Math.PI/2:i*.81,actor,role,faction:gang?faction:null,name:i===0?'Nora — La voix des Docks':gang?['Sami','Léna','Milo','Jade'][i%4]:'Habitant',home:{...p},target:{...p},state:gang?'talk':['walk','phone','talk','dance','walk','sit'][i%6],phase:i*.71,think:0,wait:3+i%4,recruited:s.recruited.includes('person-'+i),vx:0,vz:0};if(n.state==='sit'){const bench=this.world.props.filter(o=>o.kind==='bench').sort((a,b)=>distance(a,n)-distance(b,n))[0];if(bench&&distance(bench,n)<18){n.x=bench.x;n.z=bench.z+.15;n.yaw=Math.PI-(bench.root?.rotation.y||0);n.home={x:n.x,z:n.z};}else n.state='talk';}if(n.state==='phone'){const phone=M.round(actor.re,.075,.135,.018,0,-.29,.055,M.mat('#0d1025'),.008);phone.rotation.x=-.2;M.round(phone,.06,.104,.005,0,0,.011,M.mat('#00eaff'),.006);}this.lifePeople.push(n);actor.root.position.set(n.x,0,n.z);actor.root.rotation.y=Math.PI-n.yaw;}
 const leader=this.lifePeople[0];Object.assign(leader,HOME,{home:{...HOME},target:{...HOME}});leader.marker=labelPlane('NORA · MISSIONS','#ffe000',2.65);leader.marker.position.y=2.55;leader.actor.root.add(leader.marker);
 for(let i=0;i<5;i++){const model=M.petModel('dog'),p=freeNearby(this,-230+i*2,-216-i*3);model.root.scale.setScalar(i===0?.94:.8+i*.035);this.scene.add(model.root);this.strays.push({id:'stray-'+i,name:['Pixel','Rocky','Foxy','Nougat','Jazz'][i],x:p.x,z:p.z,y:0,yaw:i,home:{...p},target:{...p},model,phase:i,seed:i,wait:0,fed:s.fed.includes('stray-'+i),adopted:s.adopted.includes('stray-'+i),following:false});}
 for(let i=0;i<CLEAN.length;i++)this.lifeProps.push(makeMissionProp(this,'clean-'+i,CLEAN[i],'bag'));this.lifeProps.push(makeMissionProp(this,'parcel',PICKUP,'parcel'));
 this.lifeDrop=new T.Group;this.lifeDrop.position.set(DELIVERY.x,Math.min(.55,this.world.groundHeight(DELIVERY.x,DELIVERY.z,0)),DELIVERY.z);this.scene.add(this.lifeDrop);const ring=M.mesh(this.lifeDrop,new T.TorusGeometry(1,.07,8,28),new T.MeshBasicMaterial({color:'#fff000'}),0,.1,0);ring.rotation.x=Math.PI/2;const sign=labelPlane('DÉPÔT COLIS','#fff000',2);sign.position.y=1.6;this.lifeDrop.add(sign);
 this.lifeCarry=new T.Group;M.round(this.lifeCarry,.40,.31,.29,0,0,0,M.mat('#ff8100'),.035);M.round(this.lifeCarry,.07,.32,.30,0,0,0,M.mat('#ffe600'),.012);this.lifeCarry.visible=false;this.actor.le.add(this.lifeCarry);this.lifeCarry.position.set(0,-.3,.12);
 this.lifeCup=new T.Group;M.mesh(this.lifeCup,new T.CylinderGeometry(.061,.05,.16,12),M.mat('#ff1c73'),0,0,0);M.mesh(this.lifeCup,new T.CylinderGeometry(.063,.063,.015,12),M.mat('#fffaff'),0,.079,0);this.actor.re.add(this.lifeCup);this.lifeCup.position.set(0,-.31,.07);this.lifeCup.visible=false;this.lifeWater=new T.Group;const dropGeo=new T.SphereGeometry(.045,6,5),dropMat=new T.MeshBasicMaterial({color:'#00dfff',transparent:true,opacity:.8});for(let i=0;i<14;i++)this.lifeWater.add(new T.Mesh(dropGeo,dropMat));this.scene.add(this.lifeWater);this.lifeWater.visible=false;this.allies.forEach((a,i)=>{if(s.crewColors[i])bandana(a.actor,s.crewColors[i]);});for(const e of this.enemies)bandana(e.actor,FACTIONS[e.home%3]?.color||BRIGHT[0]);if(s.job?.type==='rescue'&&s.job.stage===1)this.strays[0].following=true;
};
G.lifeNearby=function(){if(!this.cityActive||this.vehicle||this.heliFlying||this.action||this.cityTask||this.player.y>1.5)return null;const p=this.player,choices=[];for(const n of this.lifePeople||[])if(!n.recruited&&distance(n,p)<2.6)choices.push({kind:'person',target:n,label:n.role==='leader'?'Parler à Nora · missions':n.faction?'Parler à '+n.name+' · '+n.faction.name:'Discuter / danser',distance:distance(n,p)});for(const d of this.strays||[])if(!d.adopted&&distance(d,p)<2.4)choices.push({kind:'dog',target:d,label:'Rassurer '+d.name,distance:distance(d,p)});
 const job=this.city.life.job;if(job?.type==='cleanup')for(const o of this.lifeProps)if(o.type==='bag'&&!job.collected.includes(o.id.split('-')[1])&&distance(o,p)<2.5)choices.push({kind:'clean',target:o,label:'Ramasser le sac',distance:distance(o,p)-.8});if(job?.type==='courier'&&job.stage===0){const o=this.lifeProps.find(o=>o.id==='parcel');if(distance(o,p)<2.5)choices.push({kind:'pickup',target:o,label:'Prendre le colis',distance:distance(o,p)-.8});}if(job?.type==='courier'&&job.stage===1&&distance(p,DELIVERY)<2.5)choices.push({kind:'deliver',target:DELIVERY,label:'Livrer le colis',distance:-1});
 for(const prop of this.lifeInteractables||[]){if(prop.health===0||!['bench','vending','bin','phone','mailbox','dance','hydrant'].includes(prop.kind)||distance(p,prop)>2.15)continue;choices.push({kind:'prop',target:prop,label:{bench:'S’asseoir',vending:'Boisson fraîche · 6 pièces',bin:'Fouiller / recycler',phone:'Écouter les nouvelles du quartier',mailbox:'Missions du quartier',dance:'Danser',hydrant:'Rafraîchissement'}[prop.kind],distance:distance(p,prop)+.35});}
 choices.sort((a,b)=>a.distance-b.distance);return choices[0]||null;};
const cityInteract=G.cityInteract;
G.cityInteract=function(){if(this.lifeAction){this.cancelLifeAction();return true;}if(this.vehicle||this.action||this.cityTask||this.heliFlying)return cityInteract.call(this);const p=this.player;/* Existing counters, pets and lifts retain their interaction space. */if(this.world.services.some(b=>distance(p,b.service)<3.6)||this.world.buildings.some(b=>distance(p,b.lift)<2.2)||this.pets.some(d=>distance(p,d)<2))return cityInteract.call(this);const nearby=this.lifeNearby();if(!nearby)return cityInteract.call(this);if(['clean','pickup','deliver'].includes(nearby.kind))this.performLifeInteraction(nearby.kind,nearby.target);else this.openPlace('life-'+nearby.kind,nearby.target);return true;};
G.cancelLifeAction=function(){if(!this.lifeAction)return;this.lifeAction=null;if(this.lifeCup)this.lifeCup.visible=false;if(this.lifeWater)this.lifeWater.visible=false;if(this.lifeCarry)this.lifeCarry.visible=this.city.life.job?.type==='courier'&&this.city.life.job.stage===1;this.player.vy=0;this.toast('Vous reprenez votre promenade.');};
G.performLifeInteraction=function(kind,target){if(this.lifeAction||this.action||this.cityTask||this.vehicle)return false;const s=this.city.life,p=this.player;if(target&&distance(p,target)>4)return false;let duration={sit:10,dance:8,drink:3,search:2.8,pet:2.5,clean:2.8,pickup:2.5,deliver:2.5,phone:4,hydrant:3}[kind]||3;
 if(kind==='drink'){if(this.cash<6){this.toast('Il vous faut 6 pièces.');return false;}this.cash-=6;this.save();}
 if(kind==='search'){const id=target.kind+':'+Math.round(target.x)+':'+Math.round(target.z);if(s.searched.includes(id)){this.toast('Cette corbeille a déjà été triée.');return false;}}
 if(target&&distance(p,target)>4)return false;this.lifeAction={kind,target,time:0,duration};p.armed=false;p.aim=false;p.vx=p.vz=p.vy=0;if(target){p.yaw=Math.atan2(target.x-p.x,-(target.z-p.z));if(kind==='sit'){const point=freeNearby(this,target.x,target.z+.2,1);p.x=point.x;p.z=point.z;p.y=(target.root?.position.y||0)+.26;p.yaw=Math.PI-(target.yaw||target.root?.rotation.y||0);}}
 this.setMode('play');this.input.clear();this.soundscape?.event(kind==='pet'?'bark':'interaction',.28);return true;};
G.finishLifeAction=function(a){const s=this.city.life;this.lifeAction=null;if(this.lifeCup)this.lifeCup.visible=false;if(this.lifeWater)this.lifeWater.visible=false;if(a.kind==='drink'){this.player.health=Math.min(100,this.player.health+12);this.toast('Boisson fraîche : +12 santé.');}if(a.kind==='search'){const id=a.target.kind+':'+Math.round(a.target.x)+':'+Math.round(a.target.z);if(!s.searched.includes(id)){s.searched.push(id);s.searched=s.searched.slice(-512);this.cash+=5;this.toast('Recyclage : +5 pièces.');}}if(a.kind==='pet'){a.target.fed=true;if(!s.fed.includes(a.target.id))s.fed.push(a.target.id);a.target.wait=6;if(s.job?.type==='rescue'&&a.target.id==='stray-0'){s.job.stage=1;a.target.following=true;this.toast('Pixel vous fait confiance. Raccompagnez-le auprès de Nora.');}else this.toast(a.target.name+' vous fait confiance. Vous pouvez l’adopter.');}if(a.kind==='clean'&&s.job?.type==='cleanup'){const id=a.target.id.split('-')[1];if(!s.job.collected.includes(id))s.job.collected.push(id);s.job.stage=s.job.collected.length;this.toast('Sac ramassé : '+s.job.collected.length+' / 3.');}if(a.kind==='pickup'&&s.job?.type==='courier'){s.job.stage=1;this.toast('Colis récupéré. Direction la cour sud !');}if(a.kind==='deliver'&&s.job?.type==='courier'&&s.job.stage===1)this.completeLifeJob();if(a.kind==='phone')this.toast('Radio Docks : Nora vous attend dans la cour, au nord-ouest.');if(a.kind==='hydrant'){this.player.health=Math.min(100,this.player.health+3);this.toast('Un peu de fraîcheur ! +3 santé.');}this.save();};
const playerUpdate=G.updatePlayer;
G.updatePlayer=function(u,dt){if(!this.lifeAction)return playerUpdate.call(this,u,dt);if(this.action||this.vehicle||this.cityTask||this.heliFlying||Math.hypot(u.x||0,u.forward||0)>.2||u.edges?.has('jump')){this.cancelLifeAction();return playerUpdate.call(this,u,dt);}const a=this.lifeAction,p=this.player;a.time+=dt;p.vx=p.vz=p.vy=0;p.invincible=Math.max(0,p.invincible-dt);p.fireCd=Math.max(0,p.fireCd-dt);this.cam.yaw+=(u.lookX||0)*dt*2+(u.mouseX||0)*.002;this.cam.pitch=clamp(this.cam.pitch+(u.lookY||0)*dt+(u.mouseY||0)*.002,-.3,.9);M.animateCharacter(this.actor,0,dt,this.t,false,false,0,0,{seated:a.kind==='sit',revive:['pet','clean','search','pickup','deliver'].includes(a.kind)});M.lifePose(this.actor,a.kind,a.time);this.lifeCup.visible=a.kind==='drink';if(a.kind==='hydrant'){this.lifeWater.visible=true;this.lifeWater.position.set(a.target.x,0,a.target.z);this.lifeWater.children.forEach((drop,i)=>{const q=(a.time*.7+i/14)%1;drop.position.set(Math.sin(i*2.4)*q*.7,.5+Math.sin(q*Math.PI)*1.2,Math.cos(i*2.4)*q*.7);});}this.actor.root.position.set(p.x,p.y,p.z);this.actor.root.rotation.y=Math.PI-p.yaw;if(a.time>=a.duration)this.finishLifeAction(a);};
G.acceptLifeJob=function(type){const s=this.city.life;if(!JOBS[type])return false;if(s.job||this.city.job){this.toast('Terminez ou abandonnez la mission en cours.');return false;}if(s.completed.includes(type)){this.toast('Cette histoire du quartier est déjà terminée.');return false;}s.job={type,stage:0,remaining:420,collected:[]};if(type==='rescue'){const dog=this.strays[0];if(dog.adopted){this.toast('Pixel a déjà trouvé une famille.');s.job=null;return false;}}
 this.setMode('play');this.save();this.toast(JOBS[type].title+' · Suivez le trajet jaune.');return true;};
G.completeLifeJob=function(){const s=this.city.life,job=s.job;if(!job||s.completed.includes(job.type))return false;const reward=JOBS[job.type].reward;s.completed.push(job.type);s.job=null;this.cityTarget=null;this.cash+=reward;this.rep+=8;if(this.strays[0])this.strays[0].following=false;this.lifeCarry.visible=false;this.toast('Quartier aidé ! +'+reward+' pièces · +8 réputation.');this.save();return true;};
G.recruitLifePerson=function(n){if(!n||n.role==='leader'||n.recruited||this.allies.length>=3)return this.toast('Équipe complète ou habitant indisponible.');if(this.cash<200)return this.toast('Recrutement : 200 pièces.');this.cash-=200;n.recruited=true;this.city.life.recruited.push(n.id);const color=n.faction?.color||BRIGHT[4];this.city.life.crewColors[this.allies.length]=color;this.addAlly();bandana(this.allies[this.allies.length-1].actor,color);this.save();this.setMode('play');this.toast(n.name+' rejoint '+this.city.gang+'. Donnez-lui des ordres dans Mon gang.');};
G.adoptStray=function(d){const s=this.city.life;if(!d||d.adopted||!d.fed)return this.toast('Rassurez d’abord ce chien.');if(this.city.pets.length>=3)return this.toast('Trois compagnons maximum.');d.adopted=true;d.following=false;s.adopted.push(d.id);this.city.pets.push({kind:'dog',name:d.name,command:'follow'});if(s.job?.type==='rescue'&&d.id==='stray-0')this.completeLifeJob();this.syncPets();this.save();this.setMode('play');this.toast(d.name+' a trouvé une famille ! Il vous suit.');};
const updateCity=G.updateCity;
G.updateCity=function(dt){updateCity.call(this,dt);if(!this.lifePeople)return;this.lifeClock+=dt;const p=this.player,clock=this.lifeClock,s=this.city.life;
 for(const n of this.lifePeople){const near=distance(n,p)<58;n.actor.root.visible=near&&!n.recruited;if(!near||n.recruited)continue;n.think-=dt;n.wait-=dt;let speed=0;if(n.think<=0){n.think=.5;const car=this.cars.find(c=>Math.abs(c.speed)>5&&distance(c,n)<6);if(car){const dx=n.x-car.x,dz=n.z-car.z,d=Math.hypot(dx,dz)||1;n.target=freeNearby(this,n.x+dx/d*6,n.z+dz/d*6);n.state='flee';n.wait=3.5;}else if(n.state==='flee'&&n.wait<0){n.state=n.role==='gang'||n.role==='leader'?'talk':'walk';n.target={...n.home};}else if(n.role==='social'&&n.state==='walk'&&distance(n,n.target)<.6){n.target=freeNearby(this,n.home.x+Math.sin(clock*.23+n.phase)*5,n.home.z+Math.cos(clock*.21+n.phase)*1.8);}}
 if(n.state==='walk'||n.state==='flee'){const dx=n.target.x-n.x,dz=n.target.z-n.z,d=Math.hypot(dx,dz);if(d>.4){speed=n.state==='flee'?4.2:1.2;this.world.grid.move(n,dx/d*speed*dt,dz/d*speed*dt,.34);n.yaw=M.angle(n.yaw,Math.atan2(dx,-dz),5,dt);}}else if(n.state!=='sit'&&distance(n,p)<4)n.yaw=M.angle(n.yaw,Math.atan2(p.x-n.x,-(p.z-n.z)),2,dt);
 M.animateCharacter(n.actor,speed,dt,clock+n.phase,false,false,0,0,{seated:n.state==='sit'});M.lifePose(n.actor,n.state,clock+n.phase);n.y=n.state==='sit'?.26:Math.min(.55,this.world.groundHeight(n.x,n.z,0));n.actor.root.position.set(n.x,n.y,n.z);n.actor.root.rotation.y=Math.PI-n.yaw;if(n.marker){n.marker.rotation.y=this.cam.yaw+n.yaw-Math.PI;n.marker.position.y=2.55+Math.sin(clock*2)*.04;}}
 for(const d of this.strays){d.model.root.visible=!d.adopted&&distance(d,p)<65;if(d.adopted||!d.model.root.visible&&!d.following)continue;d.wait-=dt;const target=d.following?{x:p.x+Math.cos(this.cam.yaw)*1.5,z:p.z+Math.sin(this.cam.yaw)*1.5}:d.target;let dist=distance(d,target),speed=0;if(!d.following&&d.wait<=0&&dist<.8){d.target=freeNearby(this,d.home.x+Math.sin(clock*.2+d.phase)*7,d.home.z+Math.cos(clock*.17+d.phase)*6);d.wait=2.5+d.seed*.2;}if(dist>(d.following?1.3:.6)&&d.wait<=0){speed=d.following?dist>7?5.7:3.1:1.0;const dx=target.x-d.x,dz=target.z-d.z;this.world.grid.move(d,dx/dist*speed*dt,dz/dist*speed*dt,.25);d.yaw=M.angle(d.yaw,Math.atan2(dx,-dz),6,dt);}d.phase+=speed*dt*4;d.model.legs?.forEach((leg,i)=>leg.rotation.x=Math.sin(d.phase+i%2*Math.PI)*Math.min(.65,speed*.35));if(d.model.tail)d.model.tail.rotation.z=Math.sin(clock*9+d.phase)*(d.fed?.55:.23);if(d.model.head){d.model.head.rotation.x=Math.sin(clock*1.5+d.phase)*.09;d.model.head.rotation.y=d.wait>0?Math.sin(clock)*.2:0;}d.model.root.position.set(d.x,Math.min(.55,this.world.groundHeight(d.x,d.z,0))+Math.abs(Math.sin(d.phase))*Math.min(.035,speed*.01),d.z);d.model.root.rotation.y=Math.PI-d.yaw;}
 for(const a of this.world.decorAnimations||[]){a.pivot.visible=distance(a,p)<80;if(a.pivot.visible&&a.kind==='swing')a.pivot.rotation.x=Math.sin(clock*1.4+a.phase)*.28;}const job=s.job;for(const o of this.lifeProps){o.root.visible=distance(p,o)<70&&(o.type==='bag'?job?.type==='cleanup'&&!job.collected.includes(o.id.split('-')[1]):job?.type==='courier'&&job.stage===0);o.ring.scale.setScalar(1+Math.sin(clock*3)*.07);}this.lifeDrop.visible=job?.type==='courier'&&job.stage===1&&distance(p,DELIVERY)<80;this.lifeCarry.visible=!!(job?.type==='courier'&&job.stage===1&&!this.vehicle&&!this.heliFlying);if(this.lifeCarry.visible&&!this.lifeAction){this.actor.la.rotation.x=-.9;this.actor.le.rotation.x=-.7;}
 if(job){job.remaining=Math.max(0,job.remaining-dt);if(!job.remaining){s.job=null;this.strays[0].following=false;this.cityTarget=null;this.lifeCarry.visible=false;this.toast('Mission des Docks expirée. Nora pourra vous la reproposer.');this.save();}else if(job.type==='cleanup'){this.cityTarget=job.collected.length===3?HOME:CLEAN[Number(['0','1','2'].find(i=>!job.collected.includes(i)))];if(job.collected.length===3&&distance(p,HOME)<3)this.completeLifeJob();}else if(job.type==='courier')this.cityTarget=job.stage===0?PICKUP:DELIVERY;else{const d=this.strays[0];this.cityTarget=job.stage===0?d:HOME;if(job.stage===1&&distance(p,HOME)<3&&distance(d,HOME)<5)this.completeLifeJob();}}
};
const renderCity=P.renderCity;
P.renderCity=function(){const g=this.g,id=g.place;if(!id?.startsWith('life-')){renderCity.call(this);if(id==='directory'||id==='missions'){const b=document.createElement('button');b.className='primary';b.textContent='LES DOCKS · TROIS HISTOIRES DE QUARTIER';b.onclick=()=>g.openPlace('life-missions');$('panelBody').appendChild(b);}return;}
 const body=$('panelBody');body.replaceChildren();$('panelEyebrow').textContent='MARLON / LES DOCKS';const target=g.placeTarget;const title=t=>$('panelTitle').textContent=t;const text=t=>{const p=document.createElement('p');p.textContent=t;body.appendChild(p);};const buttons=document.createElement('div');buttons.className='city-cards';body.appendChild(buttons);const button=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;buttons.appendChild(b);return b;};
 if(id==='life-person'){title(target.name);text(target.role==='leader'?'Ici, on prend soin du quartier. Vous pouvez donner un coup de main ou rencontrer les équipes des Docks.':(target.faction?target.faction.name+' · ':'' )+'Discutez, dansez ou proposez à cet habitant de rejoindre votre équipe.');if(target.role==='leader')button('LES MISSIONS DE NORA',()=>g.openPlace('life-missions'));else button('RECRUTER · 200 PIÈCES',()=>g.recruitLifePerson(target));button('DANSER ENSEMBLE',()=>{target.state='dance';g.performLifeInteraction('dance',target);});button('ME GUIDER VERS LES DOCKS',()=>{g.cityTarget=HOME;g.setMode('play');});}
 else if(id==='life-dog'){title(target.name+' · chien errant');text(target.fed?'Il vous fait confiance. Offrez-lui une maison : il pourra ensuite s’asseoir, se coucher et donner la patte.':'Approchez doucement. Une caresse peut le rassurer.');button('RASSURER ET CARESSER',()=>g.performLifeInteraction('pet',target));if(target.fed)button('ADOPTER '+target.name.toUpperCase()+' · GRATUIT',()=>g.adoptStray(target));}
 else if(id==='life-prop'){title({bench:'Une pause dans la ville',vending:'FIZZ · Boissons fraîches',bin:'Recycler et récupérer',phone:'Radio Docks',mailbox:'Le courrier du quartier',dance:'La piste est à vous',hydrant:'Fraîcheur tropicale'}[target.kind]);const map={bench:['S’ASSEOIR · E POUR SE LEVER','sit'],vending:['BOIRE · 6 PIÈCES · +12 SANTÉ','drink'],bin:['TRIER · +5 PIÈCES UNE FOIS','search'],phone:['ÉCOUTER','phone'],dance:['DANSER','dance'],hydrant:['SE RAFRAÎCHIR','hydrant']};if(target.kind==='mailbox')button('LES MISSIONS DU QUARTIER',()=>g.openPlace('life-missions'));else{const a=map[target.kind];button(a[0],()=>g.performLifeInteraction(a[1],target));}}
 else if(id==='life-missions'){title('Nora · Les histoires des Docks');text('Trois services pour le quartier. Chaque histoire récompense une seule fois, et votre progression est sauvegardée.');for(const[type,job]of Object.entries(JOBS)){const card=document.createElement('article');card.className='city-card';const h=document.createElement('h3');h.textContent=job.title;card.appendChild(h);const p=document.createElement('p');p.textContent=job.detail+' Récompense : '+job.reward+' pièces.';card.appendChild(p);const b=document.createElement('button');b.textContent=g.city.life.completed.includes(type)?'TERMINÉ':g.city.life.job?.type===type?'EN COURS':'ACCEPTER · 7 MINUTES';b.disabled=g.city.life.completed.includes(type)||!!g.city.life.job;b.onclick=()=>g.acceptLifeJob(type);card.appendChild(b);buttons.appendChild(card);}button('GUIDER JUSQU’À NORA',()=>{g.cityTarget=HOME;g.setMode('play');});if(g.city.life.job)button('ABANDONNER LA MISSION',()=>{g.city.life.job=null;g.strays[0].following=false;g.cityTarget=null;g.lifeCarry.visible=false;g.save();g.openPlace('life-missions');});}
 button('REPRENDRE LA PROMENADE',()=>g.setMode('play'));buttons.querySelector('button:not(:disabled)')?.focus();
};
const uiUpdate=P.update;
P.update=function(){uiUpdate.call(this);const g=this.g;if(!g.city?.life)return;if(g.lifeAction){const a=g.lifeAction;const names={sit:'Assis',dance:'Danse',drink:'Boisson',search:'Recyclage',pet:'Caresse',clean:'Ramassage',pickup:'Colis',deliver:'Livraison',phone:'Radio Docks',hydrant:'Fraîcheur'};$('context').textContent=names[a.kind]+' · '+Math.ceil(a.duration-a.time)+' s · E / △ ou déplacement pour arrêter';}else if(g.mode==='play'&&!g.vehicle&&!g.cityTask&&!g.action){const nearby=g.lifeNearby();if(nearby)$('context').textContent='E / △ '+nearby.label;}const job=g.city.life.job;if(job){$('objectiveType').textContent='LES DOCKS · '+Math.ceil(job.remaining)+' S';$('objectiveTitle').textContent=JOBS[job.type].title;$('objectiveText').textContent=job.type==='cleanup'?'Sacs : '+job.collected.length+' / 3 · E / △ pour ramasser':job.type==='rescue'?(job.stage?'Raccompagnez Pixel auprès de Nora.':'Approchez Pixel et rassurez-le avec E / △.'):(job.stage?'Livrez le colis dans le cercle jaune · E / △.':'Récupérez le colis orange · E / △.');}}
})(Marlon);
