(function(M){
'use strict';
function boot(){try{if(typeof THREE==='undefined')throw new Error('Moteur absent. Extrayez tout le ZIP, en conservant le dossier vendor.');const T=THREE,canvas=document.getElementById('view'),renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const scene=new T.Scene;scene.fog=new T.FogExp2('#889296',.0026);M.makeSky(scene);const ambient=new T.HemisphereLight('#c4d7e6','#827663',.7);scene.add(ambient);const sun=new T.DirectionalLight('#ffdbad',1.6);sun.position.set(-70,90,-55);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-55,right:55,top:55,bottom:-55,near:1,far:240});sun.shadow.bias=-.00025;sun.shadow.normalBias=.035;scene.add(sun);scene.add(sun.target);
 // A local environment map produces specular highlights without external assets.
 const faces=Array.from({length:6},(_,i)=>{const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),gr=ctx.createLinearGradient(0,0,0,256);gr.addColorStop(0,'#50667d');gr.addColorStop(.48,'#bca38c');gr.addColorStop(.52,'#697276');gr.addColorStop(1,'#3d4346');ctx.fillStyle=gr;ctx.fillRect(0,0,256,256);for(let j=0;j<8;j++){ctx.fillStyle=j%2?'#5b656d':'#7a8184';const h=28+(j*43+i*13)%75;ctx.fillRect(j*36,135-h,27,h);ctx.fillStyle='#a7afad';for(let y=140-h;y<132;y+=10)ctx.fillRect(j*36+4,y,19,2);}return c;});const envMap=new T.CubeTexture(faces);envMap.encoding=T.sRGBEncoding;envMap.needsUpdate=true;scene.environment=envMap;
 const camera=new T.PerspectiveCamera(62,innerWidth/innerHeight,.07,2500);const g=M.game=new M.Game(renderer,scene,camera);g.initV3();g.sun=sun;g.quality='balanced';g.setQuality=function(level){const options={performance:{ratio:.8,shadow:false,map:1024},balanced:{ratio:1,shadow:true,map:1024},high:{ratio:1.5,shadow:true,map:2048},ultra:{ratio:2,shadow:true,map:2048}},opt=options[level]||options.balanced;g.quality=options[level]?level:'balanced';renderer.setPixelRatio(Math.min(devicePixelRatio||1,opt.ratio,3840/innerWidth));renderer.shadowMap.enabled=opt.shadow;if(sun.shadow.mapSize.x!==opt.map){sun.shadow.mapSize.set(opt.map,opt.map);sun.shadow.map?.dispose();sun.shadow.map=null;}renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();};
 g.ui=new M.UI(g);if(g.store.source==='backup')g.toast('La copie de secours a restauré votre campagne.');try{const s=JSON.parse(localStorage.getItem('marlon.rebuild.settings')||'{}');g.quality=s.quality||'balanced';g.input.deadzone=M.clamp(s.deadzone??.17,.05,.4);g.input.sensitivity=M.clamp(s.sensitivity??1,.3,2);g.input.invert=!!s.invert;g.input.profile=['auto','standard','sony'].includes(s.profile)?s.profile:'auto';g.audio.enabled=s.sound!==false;g.reduceShake=!!s.reduceShake;if(typeof s.touch==='boolean')g.ui.touchEnabled=s.touch;}catch{}document.body.classList.toggle('touch',g.ui.touchEnabled);g.setQuality(g.quality);
 addEventListener('resize',()=>g.setQuality(g.quality));addEventListener('pagehide',()=>{if(g.mode!=='front')g.save();});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();g.setMode('pause');g.toast('Le contexte graphique a été perdu. Rechargez la page pour reprendre la sauvegarde.');});
 document.getElementById('loading').classList.add('hidden');let last=performance.now();function frame(now){const dt=(now-last)/1000;last=now;g.frame(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
 // Explicit developer switch: diagnostics are absent unless ?test=1 is requested.
 if(new URLSearchParams(location.search).has('test'))window.__TEST={game:g,M,teleport(x,z,yaw=0){g.player.x=x;g.player.z=z;g.player.y=0;g.player.vx=g.player.vz=0;g.player.yaw=yaw;g.cam.yaw=yaw;g.cam.target.set(x,1.4,z);if(g.vehicle){g.vehicle.x=x;g.vehicle.z=z;g.vehicle.yaw=yaw;}g.updateCamera(1);},snapshot(){return{mode:g.mode,x:g.player.x,z:g.player.z,camera:g.camera.position.toArray(),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,buildings:g.world.buildingCount,cars:g.cars.length,owned:g.sectors.filter(t=>t.owner==='player').map(t=>t.id)};}};
 }catch(e){console.error(e);const loading=document.getElementById('loading');loading.innerHTML='';const title=document.createElement('strong');title.textContent='MARLON';const msg=document.createElement('span');msg.textContent='Démarrage impossible : '+e.message;msg.style.maxWidth='80%';msg.style.textAlign='center';loading.append(title,msg);}}
setTimeout(boot,50);
})(Marlon);
