(function(M){
'use strict';const T=THREE,$=id=>document.getElementById(id);
try{const renderer=new T.WebGLRenderer({canvas:$('canvas'),antialias:true,preserveDrawingBuffer:true});renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene;scene.background=new T.Color('#34454c');scene.fog=new T.Fog('#34454c',8,22);scene.add(new T.HemisphereLight('#e8e8de','#59676f',.9));const key=new T.DirectionalLight('#ffe1b8',2);key.position.set(-3,5,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.normalBias=.025;scene.add(key);const fill=new T.DirectionalLight('#aac9da',1);fill.position.set(4,2,-2);scene.add(fill);const floor=M.mesh(scene,new T.PlaneGeometry(80,80),M.mat('#536066',.93));floor.rotation.x=-Math.PI/2;floor.castShadow=false;const grid=new T.GridHelper(30,60,'#809094','#66747a');grid.position.y=.002;grid.material.transparent=true;grid.material.opacity=.3;scene.add(grid);
const rig=M.character('#3b4b50');scene.add(rig.root);const camera=new T.PerspectiveCamera(35,1,.05,60);let yaw=.55,pitch=.18,playing=true,rate=1,clock=0,clip='idle';
const clips={idle:'Repos & respiration',walk:'Marche',run:'Course',aim:'Visée en déplacement',reload:'Rechargement',melee:'Enchaînement de coups',jump:'Saut & réception',revive:'Réanimation',death:'Chute',drive:'Conduite'};
function setClip(id){clip=id;clock=0;rig.animator=new M.Animator(rig);rig.body.rotation.set(0,0,0);rig.body.position.set(0,0,0);rig.root.position.set(0,0,0);$('clipLabel').textContent=clips[id];document.querySelectorAll('[data-clip]').forEach(b=>b.classList.toggle('active',b.dataset.clip===id));}
for(const[id,label]of Object.entries(clips)){const b=document.createElement('button');b.dataset.clip=id;b.textContent=label;b.onclick=()=>setClip(id);$('clips').appendChild(b);}
function pose(t){const q=t%3.4;const info={speed:0,armed:false,aim:false};rig.root.position.y=0;if(clip==='walk')info.speed=3.0;if(clip==='run')info.speed=6;if(clip==='aim'){info.speed=1.6;info.armed=true;info.aim=true;info.strafe=.8;info.forward=.4;info.recoil=q%1.0<.18?1-(q%1)/.18:0;}if(clip==='reload'){info.armed=true;info.reload=q<1.45?1.45-q:0;info.reloadProgress=q/1.45;}if(clip==='melee'){const p=q%1.0;info.melee=p<.62?.62-p:0;info.meleeProgress=p/.62;info.combo=Math.floor(q)+1;}if(clip==='jump'){const f=q-.4,air=f>0&&f<.706;rig.root.position.y=air?5.3*f-7.5*f*f:0;info.air=air;info.vy=air?5.3-15*f:0;info.landingSpeed=5;}if(clip==='revive')info.revive=true;if(clip==='death')info.dead=q>.4;if(clip==='drive'){info.seated=true;info.steer=Math.sin(q*2)*.35;}return info;}
function tick(dt,force=false){if(playing||force){clock+=dt*rate;const info=pose(clock);M.animateCharacter(rig,info.speed,dt*rate,clock,info.armed,info.aim,info.melee||0,0,info);}camera.position.set(Math.sin(yaw)*4.7,1.05+rig.root.position.y+Math.sin(pitch)*4.7,Math.cos(yaw)*4.7);camera.lookAt(0,.97+rig.root.position.y,0);$('time').textContent=clock.toFixed(1).replace('.',',')+' s';$('meter').firstElementChild.style.width=(clock%3.4)/3.4*100+'%';renderer.render(scene,camera);}
function resize(){const r=$('stage').getBoundingClientRect();renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();setClip('idle');$('toggle').onclick=()=>{playing=!playing;$('toggle').textContent=playing?'PAUSE':'LECTURE';};$('restart').onclick=()=>setClip(clip);$('rate').oninput=e=>{rate=+e.target.value;$('rateValue').textContent=rate+'×';};let drag=null;$('canvas').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};$('canvas').setPointerCapture(e.pointerId);};$('canvas').onpointermove=e=>{if(drag){yaw-=(e.clientX-drag.x)*.008;pitch=M.clamp(pitch+(e.clientY-drag.y)*.005,-.05,.6);drag={x:e.clientX,y:e.clientY};}};$('canvas').onpointerup=$('canvas').onpointercancel=()=>drag=null;
window.__STUDIO={setClip,tick,rig,renderer,camera,scene,get clip(){return clip},setRate(v){rate=v},setView(a,b){yaw=a;pitch=b}};let last=performance.now();function frame(t){const dt=Math.min(.06,(t-last)/1000);last=t;tick(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
}catch(e){console.error(e);const p=document.createElement('p');p.id='error';p.textContent='Studio indisponible : '+e.message;document.body.appendChild(p);}
})(Marlon);
