(function(M){
'use strict';const $=id=>document.getElementById(id),P=M.UI.prototype;
const pause=P.renderPause;P.renderPause=function(){pause.call(this);const menu=$('panelBody').querySelector('.menu-buttons'),g=this.g;const buttons=[['exportCampaign','EXPORTER LA CAMPAGNE'],['importCampaign','IMPORTER UNE CAMPAGNE…'],['animationStudio','STUDIO DES ANIMATIONS ↗']];for(const[id,text]of buttons){const b=document.createElement('button');b.id=id;b.textContent=text;menu.appendChild(b);}
 $('exportCampaign').onclick=()=>{if(g.action)return g.toast('Terminez l’animation en cours avant d’exporter.');try{const blob=new Blob([g.store.encode(g.snapshotState())],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MARLON-campagne.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);g.toast('Campagne exportée. Conservez ce fichier pour la restaurer sur un autre appareil.');}catch{g.toast('Export impossible : état de campagne invalide.');}};
 const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;menu.appendChild(input);$('importCampaign').onclick=()=>input.click();input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>500000)return g.toast('Fichier trop volumineux.');const state=g.store.decode(await file.text());if(!state)return g.toast('Fichier de campagne invalide ou modifié. Votre partie est conservée.');if(confirm('Remplacer cette campagne par celle du fichier sélectionné ?')){if(g.store.write(state)){g.skipExitSave=true;location.reload();}else g.toast('Import impossible. Votre précédente sauvegarde est conservée.');}};
 $('animationStudio').onclick=()=>window.open('studio.html','_blank','noopener');
 const warning=$('panelBody').querySelector('.warning');if(warning)warning.textContent='La simulation est suspendue dans les menus. Les opérations, attaques, véhicules et équipiers sont restaurés avec la campagne. Une copie de secours protège la dernière sauvegarde valide.';
};
const update=P.update;P.update=function(){update.call(this);const g=this.g,p=g.player;let roster=$('squadRoster');if(!roster){roster=document.createElement('div');roster.id='squadRoster';$('vitals').appendChild(roster);}const alive=g.allies.filter(a=>a.health>0).length;$('squadLabel').textContent='ÉQUIPE · '+alive+' / '+g.allies.length;
 roster.innerHTML=g.allies.map((a,i)=>`<div class="crew-row ${a.health<=0?'down':''}"><span>0${i+1} ${a.health<=0?'À TERRE · '+Math.ceil(a.downTime||0)+' S':Math.ceil(a.health)+' PV'}</span><i><b style="width:${Math.max(0,a.health)}%"></b></i></div>`).join('');
 if(g.action){const names={enter:'Entrée dans le véhicule',exit:'Sortie du véhicule',revive:'Réanimation',recover:'Repli à la planque'};$('context').textContent=names[g.action.kind]+' · '+Math.floor(g.action.time/g.action.duration*100)+' %';}
 else if(!g.vehicle&&g.allies.some(a=>a.health<=0&&Math.hypot(a.x-p.x,a.z-p.z)<2.6))$('context').textContent=(g.input.last==='pad'?'↑':'B')+' Relever l’équipier · 2,6 s';
 else if(p.melee>0)$('context').textContent='Corps à corps · Enchaînement '+(p.combo||1);
};
const settings=P.renderSettings;P.renderSettings=function(){settings.call(this);const node=document.createElement('div');node.className='setting';node.innerHTML='<label for="reduceShake">Réduire les secousses de caméra</label><input type="checkbox" id="reduceShake">';$('panelBody').querySelector('.settings-grid').appendChild(node);$('reduceShake').checked=!!this.g.reduceShake;$('reduceShake').onchange=e=>{this.g.reduceShake=e.target.checked;this.saveSettings();};};
const save=P.saveSettings;P.saveSettings=function(){save.call(this);try{const s=JSON.parse(localStorage.getItem('marlon.rebuild.settings'));s.reduceShake=!!this.g.reduceShake;localStorage.setItem('marlon.rebuild.settings',JSON.stringify(s));}catch{}};
})(Marlon);
