(function(M){
'use strict';const $=id=>document.getElementById(id),fmt=n=>Math.floor(n).toLocaleString('fr-FR');
class UI{
 constructor(g){this.g=g;this.mapCanvas=$('minimap');this.mapContext=this.mapCanvas.getContext('2d');this.toastTimer=0;this.lastMenu=0;this.returnTo='front';$('play').onclick=()=>g.start();$('settingsFront').onclick=()=>{this.returnTo='front';g.setMode('settings');};$('mapBtn').onclick=()=>g.setMode('map');$('pauseBtn').onclick=()=>g.setMode('pause');$('closeModal').onclick=()=>g.setMode(g.mode==='settings'?this.returnTo:'play');$('saveInfo').textContent=g.hasSave?'Votre progression est enregistrée sur cet appareil.':'Nouvelle campagne · Sauvegarde automatique';this.setupTouch();this.renderMode('front');}
 toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4300);}
 renderMode(mode){const modal=!['front','play'].includes(mode);$('front').classList.toggle('hidden',mode!=='front');$('hud').classList.toggle('hidden',mode==='front');$('modal').classList.toggle('hidden',!modal);$('touch').classList.toggle('hidden',mode!=='play'||!this.touchEnabled);if(modal){$('panelEyebrow').textContent='MARLON / EMPIRE URBAIN';if(mode==='map')this.renderMap();else if(mode==='missions')this.renderMissions();else if(mode==='settings')this.renderSettings();else if(mode==='victory')this.renderVictory();else this.renderPause();$('panelBody').querySelector('button,select,input')?.focus();}else if(mode==='front')$('play').focus();}
 renderPause(){const g=this.g;$('panelTitle').textContent='La ville peut attendre.';$('panelBody').innerHTML=`<div class="pause-grid"><div class="menu-buttons"><button class="primary" data-menu="resume">REPRENDRE LA PARTIE</button><button data-menu="map">CARTE STRATÉGIQUE</button><button data-menu="missions">OPÉRATIONS</button><button data-menu="settings">RÉGLAGES & COMMANDES</button><button data-menu="save">SAUVEGARDER</button><button data-menu="front">RETOUR À L’ACCUEIL</button></div><div><p class="eyebrow">VOTRE EMPIRE</p><h2>${g.sectors.filter(t=>t.owner==='player').length} quartiers sous contrôle</h2><p>Recrutez aux Forges avec B ou ↑. Affrontez les gangs, puis tenez une zone avec votre équipe pour la conquérir. Vos conquêtes doivent toucher un quartier déjà contrôlé.</p><p>Chaque quartier rapporte 75 € toutes les deux minutes. Les fortifications protègent contre les attaques annoncées. Pour gagner, contrôlez les douze territoires pendant 90 secondes.</p><p class="warning">La simulation est suspendue pendant les menus. Les opérations et attaques en cours ne sont pas reprises après fermeture du jeu.</p><div class="menu-buttons"><button id="newGame">NOUVELLE CAMPAGNE…</button></div></div></div>`;
 document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>{const a=b.dataset.menu;if(a==='save'){if(g.save())g.toast('Progression sauvegardée.');}else if(a==='resume')g.setMode('play');else{if(a==='settings')this.returnTo='pause';if(a==='front')g.save();g.setMode(a);}});$('newGame').onclick=()=>{if(confirm('Effacer la progression de cette refonte et recommencer ?'))g.reset();};}
 renderMap(){const g=this.g,t=g.sectors[g.selected],owned=t.owner==='player',can=M.canAttack(g.sectors,t);$('panelTitle').textContent='Douze quartiers. Un empire.';$('panelBody').innerHTML=`<div class="map-layout"><div><div class="territory-grid">${g.sectors.map(s=>`<button data-sector="${s.id}" class="sector ${s.owner==='player'?'owned':''} ${s.id===t.id?'selected':''}"><small>SECTEUR ${String(s.id+1).padStart(2,'0')}</small><strong>${s.name}</strong><em>${s.owner==='player'?'VOTRE ÉQUIPE':s.owner==='cendre'?'LES CENDRES':'ONYX'}${s.level?' · DÉF. '+s.level:''}</em></button>`).join('')}</div><div class="legend">N ↑ &nbsp; · &nbsp; Vert : vos quartiers &nbsp; · &nbsp; Ambre : quartiers rivaux<br>Les liaisons suivent les frontières horizontales et verticales.</div></div><div class="map-detail"><p class="eyebrow">${owned?'TERRITOIRE CONTRÔLÉ':can?'FRONTIÈRE ACCESSIBLE':'HORS DE VOS FRONTIÈRES'}</p><h3>${t.name}</h3><p>${owned?'Revenu : 75 € / 2 min. Renforcez les défenses pour repousser une attaque en votre absence.':can?'Approchez le repère, neutralisez ses défenseurs, puis tenez la zone 18 secondes avec au moins un équipier.':'Conquérez d’abord un territoire voisin du vôtre pour accéder à ce quartier.'}</p><p>Distance : ${Math.round(Math.hypot(g.player.x-t.x,g.player.z-t.z))} m<br>Défense : ${t.level} / 3<br>Trésorerie : ${fmt(g.cash)} €</p>${g.raid?.id===t.id?'<p class="warning">ATTAQUE EN COURS OU IMMINENTE</p>':''}<div class="menu-buttons"><button class="primary" id="track">PLACER UN REPÈRE</button><button id="fortify" ${!owned||t.level>=3||g.cash<120*(t.level+1)?'disabled':''}>RENFORCER · ${t.level>=3?'MAX':120*(t.level+1)+' €'}</button><button id="ops">CHOISIR UNE OPÉRATION</button><button id="backGame">RETOUR EN VILLE</button></div></div></div>`;
 document.querySelectorAll('[data-sector]').forEach(b=>b.onclick=()=>{g.selected=+b.dataset.sector;this.renderMap();document.querySelector(`[data-sector="${g.selected}"]`)?.focus();});$('track').onclick=()=>{g.waypoint=t.id;g.setMode('play');};$('fortify').onclick=()=>g.fortify(t.id);$('ops').onclick=()=>g.setMode('missions');$('backGame').onclick=()=>g.setMode('play');}
 renderMissions(){const g=this.g;$('panelTitle').textContent='Opérations';$('panelBody').innerHTML=`${g.operation?`<p>En cours : ${M.missions[g.operation.type].name} · ${Math.ceil(g.operation.remaining)} s restantes.</p><button id="abandon">ABANDONNER L’OPÉRATION</button><p></p>`:''}<div class="missions">${Object.entries(M.missions).map(([k,m],i)=>`<article class="mission-card"><span class="tag">OPÉRATION 0${i+1}${g.completed.includes(k)?' · DÉJÀ RÉUSSIE':''}</span><h3>${m.name}</h3><p>${m.desc}</p><span class="reward">${Math.floor(m.reward*(g.completed.includes(k)?.4:1))} € · +35 REP</span><button data-op="${k}" ${g.operation?'disabled':''}>LANCER L’OPÉRATION ↗</button></article>`).join('')}</div>`;document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>g.startOperation(b.dataset.op));if($('abandon'))$('abandon').onclick=()=>{g.operation=null;g.toast('Opération abandonnée, aucune récompense.');this.renderMissions();};}
 renderSettings(){const g=this.g,inp=g.input;$('panelTitle').textContent='Votre façon de jouer';$('panelBody').innerHTML=`<div class="settings-grid"><div class="setting"><label for="quality">Qualité du rendu</label><select id="quality"><option value="performance">Performance</option><option value="balanced">Équilibré</option><option value="high">Élevé</option><option value="ultra">Résolution Ultra HD</option></select></div><div class="setting"><label for="sensitivity">Sensibilité caméra</label><input id="sensitivity" type="range" min="0.3" max="2" step="0.05" value="${inp.sensitivity}"></div><div class="setting"><label for="deadzone">Zone morte des sticks <span id="deadValue">${Math.round(inp.deadzone*100)} %</span></label><input id="deadzone" type="range" min="0.05" max="0.4" step="0.01" value="${inp.deadzone}"></div><div class="setting"><label for="profile">Profil de manette</label><select id="profile"><option value="auto">Automatique</option><option value="standard">Standard navigateur</option><option value="sony">Sony HID brut</option></select></div><div class="setting"><label for="invert">Inverser la caméra verticale</label><input id="invert" type="checkbox" ${inp.invert?'checked':''}></div><div class="setting"><label for="sound">Ambiance et effets sonores</label><input id="sound" type="checkbox" ${g.audio.enabled?'checked':''}></div><div class="setting"><label for="touchSetting">Commandes tactiles</label><input id="touchSetting" type="checkbox" ${this.touchEnabled?'checked':''}></div><div class="setting"><span>Plein écran</span><button id="fullscreen">ACTIVER</button></div></div><div class="diag" id="padDiagnostic"></div><p>Branchez votre manette puis appuyez sur un bouton. Le profil automatique utilise d’abord la correspondance standard du navigateur. Si les axes sont incorrects, testez le profil adapté ci-dessus. Réglez la zone morte jusqu’à obtenir des axes au repos à zéro.</p><table class="controls"><thead><tr><th>ACTION</th><th>CLAVIER / SOURIS</th><th>DUALSENSE</th></tr></thead><tbody>${[['Déplacement / direction','ZQSD ou WASD','Stick gauche'],['Caméra','Souris (cliquer dans le jeu)','Stick droit'],['Course / recentrage','Maj / C','L3 maintenu / R3'],['Entrer / sortir du véhicule','E','△'],['Sortir / ranger l’arme','G','✕'],['Saut / corps à corps','Espace / F','◯ / ▢'],['Viser / tirer','Clic droit maintenu / clic gauche','L2 maintenue / R2'],['Recharger','R','←'],['Accélérer / freiner puis reculer','Z ou W / S','R2 / L2'],['Frein à main','Espace','R1'],['Recruter / ravitailler aux Forges','B / H','↑ / ↓'],['Carte / opérations / pause','M / J / Échap','Pavé tactile / Create / Options']].map(a=>'<tr>'+a.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')}</tbody></table><p class="warning">Résolution Ultra HD : jusqu’à 3840 pixels selon l’écran. Le niveau de détail des modèles reste celui de cette version. Les vibrations simples dépendent du navigateur ; les gâchettes adaptatives ne sont pas prises en charge.</p>`;
 $('quality').value=g.quality||'balanced';$('profile').value=inp.profile;$('quality').onchange=e=>{g.setQuality(e.target.value);this.saveSettings();};$('sensitivity').oninput=e=>{inp.sensitivity=+e.target.value;this.saveSettings();};$('deadzone').oninput=e=>{inp.deadzone=+e.target.value;$('deadValue').textContent=Math.round(inp.deadzone*100)+' %';this.saveSettings();};$('profile').onchange=e=>{inp.profile=e.target.value;inp.prev=[];this.saveSettings();};$('invert').onchange=e=>{inp.invert=e.target.checked;this.saveSettings();};$('sound').onchange=e=>{g.audio.enabled=e.target.checked;g.audio.start();this.saveSettings();};$('touchSetting').onchange=e=>{this.touchEnabled=e.target.checked;document.body.classList.toggle('touch',this.touchEnabled);this.saveSettings();};$('fullscreen').onclick=()=>{document.documentElement.requestFullscreen?.().catch(()=>g.toast('Plein écran indisponible.'));};}
 saveSettings(){const g=this.g;try{localStorage.setItem('marlon.rebuild.settings',JSON.stringify({quality:g.quality,deadzone:g.input.deadzone,sensitivity:g.input.sensitivity,invert:g.input.invert,profile:g.input.profile,sound:g.audio.enabled,touch:this.touchEnabled}));}catch{}}
 renderVictory(){$('panelTitle').textContent='La ville porte votre nom.';$('panelBody').innerHTML='<div class="victory">EMPIRE MARLON</div><p>Les douze quartiers sont sous votre contrôle. Vous les avez conservés pendant 90 secondes.</p><p>La campagne est remportée. Vous pouvez continuer à circuler, accomplir les opérations et défendre vos quartiers.</p><button id="continueCity" class="primary">CONTINUER EN VILLE</button>';$('continueCity').onclick=()=>this.g.setMode('play');}
 padMenu(u){const g=this.g,mode=g.mode;if(u.edges.has('map')&&mode==='map'){g.setMode('play');return;}if(u.edges.has('jump')&&mode!=='front'){g.setMode(mode==='settings'?this.returnTo:'play');return;}const b=g.input.prev||[],direction=u.forward<-.4||b[13]?1:u.forward>.4||b[12]?-1:0;const options=[...(mode==='front'?$('front'):$('panelBody')).querySelectorAll('button:not(:disabled),select,input')];if(direction&&g.wallTime-this.lastMenu>.22){let i=options.indexOf(document.activeElement);i=(i+direction+options.length)%options.length;options[i]?.focus();options[i]?.scrollIntoView({block:'nearest'});this.lastMenu=g.wallTime;}
 if(mode==='map'&&(u.x>.5||u.x<-.5)&&g.wallTime-this.lastMenu>.22){g.selected=M.clamp(g.selected+(u.x>0?1:-1),0,11);this.renderMap();document.querySelector(`[data-sector="${g.selected}"]`)?.focus();this.lastMenu=g.wallTime;}
 if(u.edges.has('weapon')||u.edges.has('interact')){if(document.activeElement?.tagName==='INPUT'&&document.activeElement.type==='checkbox'){document.activeElement.click();}else if(document.activeElement?.tagName==='BUTTON')document.activeElement.click();else options[0]?.click();}
 const active=document.activeElement;if(active?.tagName==='INPUT'&&active.type==='range'&&Math.abs(u.x)>.4&&g.wallTime-this.lastMenu>.12){active.value=+active.value+Math.sign(u.x)*(+active.step||1);active.dispatchEvent(new Event('input'));this.lastMenu=g.wallTime;}
 }
 setupTouch(){this.touchEnabled=matchMedia('(pointer: coarse)').matches;document.body.classList.toggle('touch',this.touchEnabled);let origin=null;const stick=$('moveStick'),nub=stick.querySelector('i');const move=e=>{if(!origin)return;const dx=M.clamp((e.clientX-origin.x)/40,-1,1),dy=M.clamp((e.clientY-origin.y)/40,-1,1);this.g.input.touch.x=dx;this.g.input.touch.y=dy;nub.style.transform=`translate(${dx*35}px,${dy*35}px)`;};stick.onpointerdown=e=>{stick.setPointerCapture(e.pointerId);origin={x:e.clientX,y:e.clientY};};stick.onpointermove=move;const end=()=>{origin=null;this.g.input.touch.x=this.g.input.touch.y=0;nub.style.transform='';};stick.onpointerup=end;stick.onpointercancel=end;let look=null;const zone=$('lookZone');zone.onpointerdown=e=>{zone.setPointerCapture(e.pointerId);look={x:e.clientX,y:e.clientY};};zone.onpointermove=e=>{if(look){this.g.input.mouse.x+=(e.clientX-look.x)*1.8;this.g.input.mouse.y+=(e.clientY-look.y)*1.8;look={x:e.clientX,y:e.clientY};}};zone.onpointerup=zone.onpointercancel=()=>{look=null;};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>this.g.input.edges.add(b.dataset.action));document.querySelectorAll('[data-hold]').forEach(b=>{const k=b.dataset.hold;const set=v=>{this.g.input.touch[k]=k==='brake'?+v:v;if(k==='fire')this.g.input.touch.gas=+v;};b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);set(true);};b.onpointerup=b.onpointercancel=()=>set(false);});}
 update(){const g=this.g,p=g.player,t=g.territory(),op=g.operation;$('cash').textContent=fmt(g.cash)+' €';$('territoryCount').textContent=String(g.sectors.filter(t=>t.owner==='player').length).padStart(2,'0')+' / 12';$('district').textContent=t.name;$('owner').textContent=t.owner==='player'?'Sous votre contrôle':t.owner==='cendre'?'Territoire des Cendres':'Territoire Onyx';$('healthBar').style.width=p.health+'%';$('healthLabel').textContent=Math.ceil(p.health);$('mag').textContent=p.reload>0?'··':p.mag;$('reserve').textContent=' / '+p.ammo;$('squadLabel').textContent='ÉQUIPE · '+g.allies.length+' / 3';$('repLabel').textContent='REP '+g.rep;$('padStatus').textContent=g.input.pad?'MANETTE CONNECTÉE':'CLAVIER / SOURIS';$('reticle').style.display=p.armed&&!g.vehicle&&g.mode==='play'?'block':'none';$('hitmarker').style.opacity=g.hitTime>0?'1':'0';$('damage').style.opacity=Math.min(.6,g.damageTime);$('carHUD').classList.toggle('hidden',!g.vehicle);$('ammo').classList.toggle('hidden',!!g.vehicle);if(g.vehicle){$('speed').textContent=Math.round(Math.abs(g.vehicle.speed)*3.6);$('carName').textContent=g.vehicle.name;$('carHealth').style.width=g.vehicle.health+'%';}
 $('captureHUD').classList.toggle('hidden',!g.captureTarget);if(g.captureTarget){$('captureLabel').textContent=g.captureReason;$('captureBar').style.width=Math.min(100,g.captureTarget.capture*100)+'%';}
 let context='';if(g.vehicle)context=g.input.last==='pad'?'△ Sortir à l’arrêt · R1 Frein à main':'E Sortir à l’arrêt · Espace Frein à main';else{const car=g.cars.find(c=>Math.hypot(c.x-p.x,c.z-p.z)<4.7&&Math.abs(c.speed)<2&&c.health>0);if(car)context=(g.input.last==='pad'?'△':'E')+' Entrer · '+car.name;else if(g.nearBase())context=g.input.last==='pad'?'↑ Recruter 200 € · ↓ Ravitaillement 60 €':'B Recruter 200 € · H Ravitaillement 60 €';else if(p.reload>0)context='Rechargement…';}$('context').textContent=context;
 let type='PREMIERS PAS',title='Constituer votre équipe',text='Recrutez aux Forges : B / ↑, puis rejoignez un quartier voisin.',dest=g.allies.length?9:8,progress=0;
 if(g.allies.length){type='VOTRE EMPIRE';title='Étendre vos frontières';text='M / pavé tactile : choisissez un quartier voisin. Éliminez ses défenseurs et tenez la zone avec votre équipe.';}
 if(g.waypoint!==null){dest=g.waypoint;type='REPÈRE PERSONNEL';title=g.sectors[dest].name;text='Suivez le losange doré sur la minicarte. M / pavé tactile : changer de destination.';}
 if(op){type='OPÉRATION · '+Math.ceil(op.remaining)+' S';title=M.missions[op.type].name;text=M.missions[op.type].desc;dest=op.ids[op.index]??g.raid?.id??dest;progress=op.index/Math.max(1,op.ids.length);}
 if(g.raid){type=g.raid.warning>0?'ATTAQUE DANS '+Math.ceil(g.raid.warning)+' S':'QUARTIER ATTAQUÉ';title=g.sectors[g.raid.id].name;text='Rejoignez le quartier et repoussez les assaillants. Une fortification peut aussi absorber l’attaque.';dest=g.raid.id;}
 if(g.victoryTimer>0&&!g.won){type='EMPIRE';title='Conservez les douze quartiers';text=Math.ceil(90-g.victoryTimer)+' secondes avant la victoire.';progress=g.victoryTimer/90;}
 $('objectiveType').textContent=type;$('objectiveTitle').textContent=title;$('objectiveText').textContent=text;$('objectiveDistance').textContent=dest!==undefined?g.sectors[dest].name+' · '+Math.round(Math.hypot(p.x-g.sectors[dest].x,p.z-g.sectors[dest].z))+' m':'';$('missionProgress').firstElementChild.style.width=progress*100+'%';this.drawMap(dest);
 if(g.mode==='settings'&&$('padDiagnostic')){const i=g.input,u=g.lastInput;$('padDiagnostic').textContent=i.pad?i.pad.id+'\nProfil : '+i.mapping+'\nDéplacement X '+u.x.toFixed(2)+' / avant '+u.forward.toFixed(2)+' · Caméra X '+u.lookX.toFixed(2)+' / Y '+u.lookY.toFixed(2)+'\nR2 '+u.gas.toFixed(2)+' · L2 '+u.brake.toFixed(2):'Aucune manette détectée. Branchez-la puis appuyez sur un bouton.';}
 }
 drawMap(dest){const g=this.g,c=this.mapContext,p=g.player,w=230,scale=1.05;const point=(x,z)=>[w/2+(x-p.x)*scale,w/2+(z-p.z)*scale];c.fillStyle='#101e28';c.fillRect(0,0,w,w);c.save();for(const t of g.sectors){const [x,y]=point(t.x-75,t.z-100);c.fillStyle=t.owner==='player'?'#193934':'#2b2a2b';c.fillRect(x,y,150*scale,200*scale);c.strokeStyle='#67706d55';c.strokeRect(x,y,150*scale,200*scale);}
 c.strokeStyle='#727b8066';c.lineWidth=7;for(let v=-300;v<=300;v+=50){let a=point(v,-320),b=point(v,320);c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();a=point(-320,v);b=point(320,v);c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();}
 if(dest!==undefined){let[x,y]=point(g.sectors[dest].x,g.sectors[dest].z);x=M.clamp(x,10,w-10);y=M.clamp(y,10,w-10);c.save();c.translate(x,y);c.rotate(Math.PI/4);c.fillStyle='#e2bc77';c.fillRect(-4,-4,8,8);c.restore();}
 for(const e of g.enemies)if(e.health>0&&Math.hypot(e.x-p.x,e.z-p.z)<100){const[x,y]=point(e.x,e.z);c.fillStyle='#c36e60';c.beginPath();c.arc(x,y,2.5,0,Math.PI*2);c.fill();}for(const a of g.allies){const[x,y]=point(a.x,a.z);c.fillStyle='#9fc9b2';c.beginPath();c.arc(x,y,2.7,0,Math.PI*2);c.fill();}
 for(const car of g.cars){const[x,y]=point(car.x,car.z);c.fillStyle='#9aa8ac';c.fillRect(x-1.3,y-2.3,2.6,4.6);}
 c.translate(w/2,w/2);c.rotate(p.yaw);c.fillStyle='#f3e6c9';c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(0,2);c.lineTo(-5,5);c.closePath();c.fill();c.restore();}
}
M.UI=UI;
})(Marlon);
