/* Vehicles 05: visible occupants, hinged doors, suspension, damage and bounded effects. */
(function(M){
'use strict';
const T=THREE,G=M.Game.prototype,V=T.Vector3;
const clamp=M.clamp,near=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),smooth=x=>{x=clamp(x,0,1);return x*x*(3-2*x);},mix=(a,b,q)=>a+(b-a)*q;
const cityValidate=M.validCity;
M.validCity=function(raw){const state=cityValidate(raw);state.cars.forEach((car,i)=>{car.driverRemoved=raw?.cars?.[i]?.driverRemoved===true;});return state;};
function seatLocal(c){return c.model.seats?.driver?.clone()||new V(.4,0,-.2);}
function dimensions(c){return c.model.bounds||{width:['bike','moto'].includes(c.spec?.id)?.8:1.95,length:c.model.len||4.6,height:1.9};}
function closedDoors(c){for(const door of c?.model?.doors||[])door.hinge.rotation.y=0;}
function chooseDoor(c,side){return(c.model.doors||[]).find(d=>d.side===-side);}
function originalPose(part){if(!part)return null;return part.userData.vehicleOriginal||(part.userData.vehicleOriginal={position:part.position.clone(),rotation:part.rotation.clone(),scale:part.scale.clone()});}
G.vehicleEvent=function(kind,c,amount=1){const events=this.vehicleEvents||(this.vehicleEvents=[]);events.push({kind,car:this.cars.indexOf(c),amount:clamp(amount,0,1),time:this.t});if(events.length>48)events.shift();const sound={crash:'impact',explosion:'explosion',jack:'carjack',door:'door',brake:'brake'}[kind];if(sound)this.soundscape?.event(sound,clamp(amount,0,1),c);};
G.makeDriver=function(c){if(c.driver||c.owned||c.driverRemoved||c.health<=0||!(c.cityTraffic||['police','tow','sweeper','works'].includes(c.spec?.id)))return;
 const index=this.cars.indexOf(c),actor=M.character(c.spec.id==='police'?'#075aff':['#ff391c','#0088ff','#ffb900','#8027ff','#0bae54'][index%5]);actor.root.name='visible-vehicle-driver';actor.root.rotation.set(0,0,0);actor.root.position.copy(seatLocal(c));M.animateCharacter(actor,0,1,this.t,false,false,0,0,{seated:true});actor.gun.visible=false;c.model.body.add(actor.root);c.driver={actor,state:'driving'};
};
G.prepareVehicle=function(c){c.driverRemoved=c.cityState?.driverRemoved===true;c.wrecked=c.health<=0;c.lastVehicleHealth=c.health;c.suspension={pitch:0,roll:0,heave:0};c.braking=0;c.lastVelocity=c.speed||0;c.smokeClock=0;c.damageStage=0;closedDoors(c);this.applyVehicleDamage(c);this.makeDriver(c);};
const init=G.initCity;G.initCity=function(){init.call(this);this.vehicleEvents=[];this.displacedDrivers=[];this.vehicleFX={pool:[],cursor:0};const geometry=new T.SphereGeometry(1,8,6);for(let i=0;i<96;i++){const material=new T.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:0,depthWrite:false,toneMapped:false});const mesh=new T.Mesh(geometry,material);mesh.visible=false;mesh.frustumCulled=false;this.scene.add(mesh);this.vehicleFX.pool.push({mesh,age:0,life:0,v:new V(),base:1,kind:'smoke'});}this.cars.forEach(c=>this.prepareVehicle(c));this.vehiclesV5Ready=true;};
const rebuild=G.rebuildCar;G.rebuildCar=function(c,state){if(c.driver){c.driver.actor.root.removeFromParent?c.driver.actor.root.removeFromParent():c.model.body.remove(c.driver.actor.root);c.driver=null;}rebuild.call(this,c,state);if(this.vehiclesV5Ready)this.prepareVehicle(c);};
G.seatPoint=function(c){c.model.root.updateMatrixWorld(true);return c.model.body.localToWorld(seatLocal(c));};
G.doorPoint=function(c,side,d){const width=dimensions(c).width;d=d===undefined?width/2+.9:Math.max(d,width/2+.64);const local=seatLocal(c);return{x:c.x+Math.cos(c.yaw)*side*d+Math.sin(c.yaw)*local.z,z:c.z+Math.sin(c.yaw)*side*d-Math.cos(c.yaw)*local.z};};
G.carAt=function(x,z,ignore=null,r=.4){for(const c of this.cars){if(c===ignore)continue;const b=dimensions(c),dx=x-c.x,dz=z-c.z,lx=dx*Math.cos(c.yaw)+dz*Math.sin(c.yaw),lz=dx*Math.sin(c.yaw)-dz*Math.cos(c.yaw);if(Math.abs(lx)<b.width/2+r&&Math.abs(lz)<b.length/2+r)return c;}return null;};
G.rayCars=function(o,d,max,ignore=null){let result={distance:max,car:null};for(const c of this.cars){if(c===ignore)continue;const b=dimensions(c),co=Math.cos(c.yaw),si=Math.sin(c.yaw),x=o.x-c.x,z=o.z-c.z;const hit=M.rayBox({x:x*co+z*si,y:o.y,z:x*si-z*co},{x:d.x*co+d.z*si,y:d.y,z:d.x*si-d.z*co},{minx:-b.width/2,maxx:b.width/2,miny:.15,maxy:b.height,minz:-b.length/2,maxz:b.length/2},max);if(hit<result.distance)result={distance:hit,car:c};}return result;};
const drive=M.drive;M.drive=function(c,u,dt){if(c.wrecked||c.health<=0){c.speed=0;c.dx=c.dz=0;c.braking=0;return 0;}const previous=c.speed,result=drive(c,u,dt);c.acceleration=(c.speed-previous)/Math.max(dt,.001);c.braking=clamp(Math.max(u.brake||0,u.handbrake?1:0),0,1);c.handbraking=!!u.handbrake;return result;};
G.spawnVehicleParticle=function(kind,point,velocity,size,life){if(!this.vehicleFX)return;const fx=this.vehicleFX.pool[this.vehicleFX.cursor++%this.vehicleFX.pool.length];fx.kind=kind;fx.age=0;fx.life=life;fx.base=size;fx.v.copy(velocity);fx.mesh.position.copy(point);fx.mesh.scale.setScalar(size);fx.mesh.material.color.set(kind==='red'?'#ff3000':kind==='blue'?'#006bff':kind==='ash'?'#252938':'#ffffff').convertSRGBToLinear();fx.mesh.material.opacity=kind==='white'?.62:.88;fx.mesh.visible=true;};
G.vehicleSmoke=function(c,dt,brake){if(Math.abs(c.speed)<6||brake<.5||c.health<=0)return;c.smokeClock=(c.smokeClock||0)+dt;if(c.smokeClock<.09)return;c.smokeClock=0;c.model.root.updateMatrixWorld(true);const wheels=c.model.wheels.filter(w=>!w.front);for(const wheel of wheels.length?wheels:c.model.wheels){const at=wheel.pivot.getWorldPosition(new V());at.y=.12;this.spawnVehicleParticle('white',at,new V(-Math.sin(c.yaw)*Math.abs(c.speed)*.08,.8,-Math.cos(c.yaw)*Math.abs(c.speed)*.02),.22,.9);}};
G.applyVehicleDamage=function(c){const ratio=clamp(1-c.health/100,0,1),parts=c.model.damageParts;c.damageStage=c.health<=0?3:c.health<35?2:c.health<70?1:0;if(!parts)return;
 if(parts.hood){const p=originalPose(parts.hood);parts.hood.position.copy(p.position);parts.hood.position.y+=ratio*.19;parts.hood.rotation.copy(p.rotation);parts.hood.rotation.x-=ratio*ratio*.32;parts.hood.rotation.z+=ratio*.13;parts.hood.scale.copy(p.scale);parts.hood.scale.z*=1-ratio*.12;}
 (parts.lights||[]).forEach((light,i)=>{light.visible=c.health>(i%2?32:65);});
 (parts.glass||[]).forEach((glass,i)=>{glass.visible=c.health>(i%2?24:43);});
 (parts.bumpers||[]).forEach((bumper,i)=>{const p=originalPose(bumper);bumper.position.copy(p.position);bumper.position.y-=ratio*.18;bumper.rotation.copy(p.rotation);bumper.rotation.z+=(i%2?1:-1)*ratio*.19;});
};
G.releaseDriver=function(c,point){const driver=c.driver;if(!driver)return null;const actor=driver.actor;this.scene.attach(actor.root);actor.root.rotation.set(0,Math.PI-c.yaw,0);actor.root.position.set(point.x,0,point.z);const from=point,dx=point.x-c.x,dz=point.z-c.z,d=Math.hypot(dx,dz)||1;const n={actor,x:from.x,z:from.z,y:0,yaw:Math.atan2(dx,-dz),target:{x:clamp(from.x+dx/d*2+Math.sin(c.yaw)*14,-306,306),z:clamp(from.z+dz/d*2-Math.cos(c.yaw)*14,-306,306)},age:0};this.displacedDrivers.push(n);if(this.displacedDrivers.length>8)this.scene.remove(this.displacedDrivers.shift().actor.root);c.driver=null;c.driverRemoved=true;if(c.cityState)c.cityState.driverRemoved=true;return n;};
G.safeVehicleExit=function(c,preferred){for(const side of [preferred||-1,-(preferred||-1)])for(const offset of [0,2.4,-2.4,4,-4]){const p=this.doorPoint(c,side,dimensions(c).width/2+1.25);p.x+=Math.sin(c.yaw)*offset;p.z-=Math.cos(c.yaw)*offset;if(this.world.grid.free(p.x,p.z,.4,0)&&!this.carAt(p.x,p.z,c,.4))return p;}for(const r of [4,6,9,12,18])for(let i=0;i<16;i++){const angle=i*Math.PI/8,p={x:clamp(c.x+Math.sin(angle)*r,-305,305),z:clamp(c.z+Math.cos(angle)*r,-305,305)};if(this.world.grid.free(p.x,p.z,.4,0)&&!this.carAt(p.x,p.z,c,.4))return p;}return{x:-225,z:250};};
G.explodeCar=function(c){if(c.wrecked)return false;c.wrecked=true;c.health=0;c.speed=0;c.dx=c.dz=0;c.traffic=false;c.explosionAt=this.t;closedDoors(c);const exit=this.safeVehicleExit(c,c.driverSide);if(c.driver)this.releaseDriver(c,exit);if(this.vehicle===c||this.action?.car===c){this.vehicle=null;this.action=null;this.cityTask=null;Object.assign(this.player,{x:exit.x,z:exit.z,y:this.world.groundHeight(exit.x,exit.z,0),vx:0,vz:0,vy:0,armed:false,aim:false,invincible:Math.max(this.player.invincible,3)});this.actor.root.visible=true;this.actor.root.position.set(this.player.x,this.player.y,this.player.z);this.releaseCrew(c);this.input.clear();this.toast('Véhicule détruit ! Mise à l’abri. La dépanneuse peut récupérer l’épave.');}
 for(let i=0;i<44;i++){const theta=i*2.4,r=.5+(i%5)*.18;this.spawnVehicleParticle(i%3?'red':'blue',new V(c.x+Math.sin(theta)*r,.5+(i%4)*.2,c.z+Math.cos(theta)*r),new V(Math.sin(theta)*(2+i%3),2+(i%7)*.7,Math.cos(theta)*(2+i%3)),.35+(i%4)*.11,.7+(i%5)*.18);}this.vehicleEvent('explosion',c,1);this.input.vibrate(.7,250);if(!this.accident)this.accident={at:this.t,car:c,stage:'dispatch',timer:0};this.save();return true;};
const animate=G.animateCar;G.animateCar=function(c,dt,brake=0){animate.call(this,c,dt,brake);if(!this.vehiclesV5Ready)return;
 if(c.health<=0&&!c.wrecked)this.explodeCar(c);else if(c.health>0&&c.wrecked){c.wrecked=false;c.explosionAt=null;c.lastVehicleHealth=c.health;}
 if(c.health<c.lastVehicleHealth){const impact=clamp((c.lastVehicleHealth-c.health)/18,.15,1);this.vehicleEvent('crash',c,impact);for(let i=0;i<6;i++)this.spawnVehicleParticle('white',new V(c.x,.6,c.z),new V(Math.sin(i)*2,1.4,Math.cos(i)*2),.08,.55);}
 c.lastVehicleHealth=c.health;const suspension=c.suspension||(c.suspension={pitch:0,roll:0,heave:0}),speed=Math.abs(c.speed),braking=Math.max(brake,c.braking||0),decel=clamp(-(c.acceleration||0)/22,0,1),bounce=Math.sin(this.t*(11+speed*.25))*Math.min(.022,speed*.0012);
 suspension.pitch=M.damp(suspension.pitch,(braking*clamp(speed/12,0,1)+decel*.25)*.07-clamp((c.acceleration||0)/15,0,1)*.035,9,dt);suspension.roll=M.damp(suspension.roll,-(c.steer||0)*Math.min(speed,32)*.009,8,dt);suspension.heave=M.damp(suspension.heave,bounce-braking*.025,10,dt);
 c.model.body.rotation.x=suspension.pitch;c.model.body.rotation.z=suspension.roll;c.model.body.position.y=(c.lower||0)+suspension.heave;
 for(const wheel of c.model.wheels){if(wheel.restY===undefined)wheel.restY=wheel.pivot.position.y;wheel.pivot.position.y=wheel.restY+(wheel.front?-1:1)*suspension.pitch*.28;}
 if(this.action?.car!==c)closedDoors(c);this.applyVehicleDamage(c);this.vehicleSmoke(c,dt,braking);if(braking>.65&&speed>8&&!c.brakeEvent)this.vehicleEvent('brake',c,.45);c.brakeEvent=braking>.4;
 if(c.driver){const actor=c.driver.actor;actor.root.visible=this.vehicle!==c&&this.action?.car!==c||this.action?.jacking===true;if(c.driver.state==='driving'&&near(c,this.player)<95){actor.root.position.copy(seatLocal(c));M.animateCharacter(actor,0,dt,this.t+this.cars.indexOf(c),false,false,0,0,{seated:true,steer:c.steer});actor.root.rotation.set(0,0,0);}}
};
G.interact=function(){if(this.action)return;if(this.cityActive&&this.cityInteract())return;const p=this.player,exiting=!!this.vehicle,c=this.vehicle||this.cars.filter(car=>car.health>0&&!car.wrecked&&Math.abs(car.speed)<(car.driver?10:2)).sort((a,b)=>near(a,p)-near(b,p))[0];if(!c||!exiting&&near(c,p)>=4.9){if(this.nearBase())this.heal();else this.toast('Approchez-vous d’une portière ; attendez que le véhicule ralentisse.');return;}if(exiting&&Math.abs(c.speed)>2)return this.toast('Ralentissez avant de sortir.');
 const lx=(p.x-c.x)*Math.cos(c.yaw)+(p.z-c.z)*Math.sin(c.yaw),preferred=exiting?(c.driverSide||-1):(lx>=0?1:-1);let side=null,point;for(const candidate of [preferred,-preferred]){const q=this.doorPoint(c,candidate,dimensions(c).width/2+(exiting?1.05:.75));if(!this.world.grid.free(q.x,q.z,.4,0)||this.carAt(q.x,q.z,c,.3))continue;if(!exiting&&(!this.nav.clearLine(p,q)||near(p,q)>4))continue;side=candidate;point=q;break;}if(side===null)return this.toast('Portière bloquée. Approchez-vous de l’autre côté.');
 const jacking=!exiting&&!!c.driver;c.speed=0;c.braking=1;c.traffic=false;if(!exiting)c.driverSide=side;closedDoors(c);const seat=this.seatPoint(c);this.action={kind:exiting?'exit':'enter',jacking,car:c,side,point,from:{x:p.x,y:p.y,z:p.z},seat:{x:seat.x,y:seat.y,z:seat.z},time:0,duration:jacking?2.8:1.45};Object.assign(p,{armed:false,aim:false,reload:0,melee:0,vx:0,vz:0});this.actor.root.visible=true;this.input.clear();this.audio.start();this.vehicleEvent('door',c,.5);if(!exiting&&!c.owned){this.crime(1,jacking?'Vol de véhicule signalé':'Véhicule volé');if(jacking)this.vehicleEvent('jack',c,1);}
};
const updateAction=G.updateAction;G.updateAction=function(dt){const a=this.action;if(!a||!['enter','exit'].includes(a.kind))return updateAction.call(this,dt);const c=a.car,p=this.player;if(c.wrecked||c.health<=0){this.explodeCar(c);this.action=null;closedDoors(c);return;}a.time+=dt;p.vy=0;p.invincible=Math.max(0,p.invincible-dt);const q=clamp(a.time/a.duration,0,1),enter=a.kind==='enter',door=chooseDoor(c,a.side);this.animateCar(c,dt);const opening=smooth(q/.2)*(1-smooth((q-.82)/.18));if(door)door.hinge.rotation.y=-door.side*opening*1.05;
 let seated,position;if(a.jacking){if(q<.24){const k=smooth(q/.24);position={x:mix(a.from.x,a.point.x,k),z:mix(a.from.z,a.point.z,k)};seated=0;}else if(q<.62){position=a.point;seated=0;const k=smooth((q-.30)/.29);if(c.driver){c.driver.state='extraction';const root=c.driver.actor.root,start=seatLocal(c),outside=this.safeVehicleExit(c,a.side);c.model.body.updateMatrixWorld(true);const end=c.model.body.worldToLocal(new V(outside.x,0,outside.z));root.position.copy(start).lerp(end,k);M.animateCharacter(c.driver.actor,0,dt,this.t,false,false,0,0,{enter:true,enterProgress:1-k});root.rotation.z=-a.side*Math.sin(k*Math.PI)*.36;if(q>=.59){a.displaced=this.releaseDriver(c,outside);}}}else{seated=smooth((q-.62)/.3);position={x:mix(a.point.x,a.seat.x,seated),z:mix(a.point.z,a.seat.z,seated)};}}
 else{seated=enter?smooth((q-.28)/.58):1-smooth((q-.16)/.66);if(enter&&q<.28){const k=smooth(q/.28);position={x:mix(a.from.x,a.point.x,k),z:mix(a.from.z,a.point.z,k)};}else position={x:mix(a.point.x,a.seat.x,seated),z:mix(a.point.z,a.seat.z,seated)};}
 p.x=position.x;p.z=position.z;p.y=mix(0,a.seat.y,seated||0);p.yaw=M.angle(p.yaw,c.yaw,10,dt);M.animateCharacter(this.actor,0,dt,this.t,false,false,0,0,{enter:true,enterProgress:seated||0});if(a.jacking&&q>.22&&q<.62){const tug=Math.sin((q-.22)/.4*Math.PI);this.actor.ra.rotation.x=-1.25;this.actor.la.rotation.x=-1.0;this.actor.re.rotation.x=-.4-tug*.5;this.actor.body.rotation.x=tug*.2;}
 this.actor.root.position.set(p.x,p.y,p.z);this.actor.root.rotation.y=Math.PI-p.yaw;if(q>=1){closedDoors(c);if(enter){this.vehicle=c;p.x=c.x;p.z=c.z;p.y=0;this.cam.yaw=c.yaw;this.cam.pitch=.2;this.actor.root.position.copy(this.seatPoint(c));}else{this.vehicle=null;p.x=a.point.x;p.z=a.point.z;p.y=this.world.groundHeight(p.x,p.z,0);this.releaseCrew(c);}this.action=null;this.input.clear();this.vehicleEvent('door',c,.65);this.save();}
};
const serviceDrive=G.serviceDrive;G.serviceDrive=function(c,target,dt){if(c.wrecked||c.health<=0||c.driverRemoved||this.vehicle===c||this.action?.car===c)return;c.driver||this.makeDriver(c);serviceDrive.call(this,c,target,dt);};
const updateCity=G.updateCity;G.updateCity=function(dt){const sweep=this.cars[33],holdSweep=sweep&&(sweep.wrecked||sweep.driverRemoved||this.vehicle===sweep||this.action?.car===sweep),savedSweep=holdSweep?{x:sweep.x,z:sweep.z,yaw:sweep.yaw,speed:sweep.speed}:null,disabled=[];
 for(const c of this.cars)if(c.spec.id==='police'&&(c.wrecked||c.driverRemoved||this.vehicle===c||this.action?.car===c)){disabled.push([c,c.spec]);c.spec={...c.spec,id:'police-unoccupied'};}updateCity.call(this,dt);for(const [c,spec]of disabled)c.spec=spec;if(savedSweep){Object.assign(sweep,savedSweep);this.animateCar(sweep,dt);}
 if(!this.vehiclesV5Ready)return;for(const c of this.cars){if(c.health!==c.lastVehicleHealth)this.animateCar(c,0);if(c.health<=0&&!c.wrecked)this.explodeCar(c);if(c.health>0&&c.wrecked){c.wrecked=false;c.explosionAt=null;this.animateCar(c,0);}if(c.health<=0)c.traffic=false;if(this.action?.car!==c)closedDoors(c);if(c.explosionAt!==undefined&&c.explosionAt!==null&&this.t-c.explosionAt<7){c.fireSmoke=(c.fireSmoke||0)+dt;if(c.fireSmoke>.15){c.fireSmoke=0;this.spawnVehicleParticle('ash',new V(c.x,.9,c.z),new V(.12,1.8,0),.3,2.4);}}}
 for(const n of this.displacedDrivers){n.age+=dt;const direction=this.nav.direction(n,n.target,this.t),dx=direction.x,dz=direction.z,d=Math.hypot(dx,dz),speed=near(n,n.target)>1&&d>.1?3.5:0;if(speed){this.world.grid.move(n,dx/d*speed*dt,dz/d*speed*dt,.28);n.yaw=M.angle(n.yaw,Math.atan2(dx,-dz),8,dt);}n.actor.root.position.set(n.x,0,n.z);n.actor.root.rotation.set(0,Math.PI-n.yaw,0);n.actor.root.visible=near(n,this.player)<90;M.animateCharacter(n.actor,speed,dt,this.t,false,false,0,0,{hit:n.age<.7?.3:0});}this.displacedDrivers=this.displacedDrivers.filter(n=>{if(n.age<40)return true;this.scene.remove(n.actor.root);return false;});
 for(const f of this.vehicleFX.pool){if(!f.mesh.visible)continue;f.age+=dt;const q=f.age/f.life;if(q>=1){f.mesh.visible=false;continue;}f.mesh.position.addScaledVector(f.v,dt);f.v.y+=(f.kind==='red'||f.kind==='blue'?-.4:.3)*dt;const size=f.base*(1+q*(f.kind==='white'?3:1.8));f.mesh.scale.set(size,size*(f.kind==='red'||f.kind==='blue'?1.5:1),size);f.mesh.material.opacity=(1-q)*(f.kind==='white'?.55:.9);}
};
})(Marlon);
